### ISSUE TITLE
store_parquet_metadata() with an entire NULL object column

### ISSUE THREAD

**Issue by thomasmeyler** [aws/aws-sdk-pandas#1379]
Much like like issue https://github.com/awslabs/aws-data-wrangler/issues/524#issue-790819816 I was wondering whether there was a way to override this error. I have a column that is nearly (99.9% of the time) and it would be great to be able to 'set/override the dtype to a string. 

`res = wr.s3.store_parquet_metadata(
    path=path',
    database="database",
    table="table",
    dataset=True,
    mode="overwrite"
)`

`We can not infer the data type from an entire null object column`

**Comment by kukushking** [comment]
To address this `ignore_null` was added to read methods in #1125. Would similar thing work for you?

**Comment by raaidarshad** [comment]
Hi, I'm running into this error and would find an `ignore_null` flag on `store_parquet_metadata` very useful. I'm happy to open a PR to make the changes (also my bad if commenting on a closed issue is less than ideal, figured it's better than opening a new one).
