### ISSUE TITLE
RedshiftDataAPI: Serverless Support

### ISSUE THREAD

**Issue by rmalecky** [aws/aws-sdk-pandas#1530]
The [Redshift Data API](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/redshift-data.html#RedshiftDataAPIService.Client.execute_statement) recently [added support for Redshift Serverless](https://awsapichanges.info/archive/changes/1dd256-redshift-data.html).   `WorkgroupName` can now be specified instead of `ClusterIdentifier`.  

Serverless also handles temporary credentials differently than provisioned capacity.  The [IAM principle is the database user](https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html#data-api-access) so the `db_user` parameter isn't required.  This will require an update to the[ logic that checks the auth credentials](https://github.com/awslabs/aws-data-wrangler/blob/35a09a0dbdbfb164715c4e4d311cbdb56fbf3823/awswrangler/data_api/redshift.py#L57).

**Comment by kukushking** [comment]
Thanks @rmalecky it definitely makes sense to support that - we'll put that on the roadmap
