### ISSUE TITLE
awswrangler.redshift.copy_from_files does not reproduce all functionalities of redshift COPY command

### ISSUE THREAD

**Issue by gloriamacia** [aws/aws-sdk-pandas#1549]
### Describe the bug

I am trying to copy some data from a parquet in s3 to redshift. I need to define the order of the columns in the copy command for it to work as it is not the same in all parquet files. It looks to me the following function does not allow it: 

https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.redshift.copy_from_files.html#awswrangler.redshift.copy_from_files

```

COPY pubmed.demo (uci,mdm_reltio_id, hcp_name, hcp_name_embeddings,country_cd)
from 's3://dev-gps-lh-s3-insights/demo/'
iam_role 'arn:aws:iam::482950716099:role/dev-gps-lh-redshift-spectrum' 
FORMAT as parquet SERIALIZETOJSON
ACCEPTINVCHARS;
```

I manage to reproduce the command except for the column order: 

```
wr.redshift.copy_from_files(
    path="s3://dev-gps-lh-s3-insights/demo/",
    con=con_redshift,
    table="demo",
    schema="pubmed",
    iam_role="arn:aws:iam::482950716099:role/dev-gps-lh-redshift-spectrum",
    sql_copy_extra_params=["ACCEPTINVCHAR"],
    serialize_to_json=True
)
```

I am reporting this as a bug as both commands should be equivalent. 

### How to Reproduce

Try to specify column order in https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.redshift.copy_from_files.html#awswrangler.redshift.copy_from_files, it seems to me there is no parameter for it. 

### Expected behavior

There should be a column order parameter.

### OS

Mac

### Python version

3.8

### AWS SDK for pandas version

latest

**Comment by kukushking** [comment]
HI @gloriamacia, there is [column_names](https://aws-sdk-pandas.readthedocs.io/en/latest/stubs/awswrangler.redshift.copy_from_files.html#awswrangler.redshift.copy_from_files) parameter that should enable you to select and order the columns. It will be available in the next release, meanwhile, to test this out you can install from main:

```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
