### ISSUE TITLE
s3.merge_upsert_table to work on empty destination

### ISSUE THREAD

**Issue by borodark** [aws/aws-sdk-pandas#1562]
### Describe the bug

I wonder why the merge upsert is not working if _destination s3_  is empty, when no files in the table's s3 bucket created yet. Somehow I expected to be able to merge into empty database:

```
{
  "errorMessage": "Parquet file size is 1 bytes, smaller than the minimum file footer (8 bytes)",
  "errorType": "ArrowInvalid",
  "requestId": "03b9e81d-879d-4155-845d-86c4c0957e6b",
  "stackTrace": [
    ...
    "  File \"/var/task/triggers-lambda.py\", line 147, in realy_save_to_avro\n    wr.s3.merge_upsert_table(delta_df= ds,\n",
    "  File \"/var/task/awswrangler/s3/_merge_upsert_table.py\", line 113, in merge_upsert_table\n    existing_df = wr.s3.read_parquet_table(database=database, table=table, boto3_session=boto3_session)\n",
    "  File \"/var/task/awswrangler/_config.py\", line 461, in wrapper\n    return function(**args)\n",
    "  File \"/var/task/awswrangler/s3/_read_parquet.py\", line 972, in read_parquet_table\n    df = read_parquet(\n",
    "  File \"/var/task/awswrangler/s3/_read_parquet.py\", line 777, in read_parquet\n    return _read_parquet(\n",
    "  File \"/var/task/awswrangler/s3/_read_parquet.py\", line 540, in _read_parquet\n    table=_read_parquet_file(\n",
    "  File \"/var/task/awswrangler/s3/_read_parquet.py\", line 480, in _read_parquet_file\n    pq_file: Optional[pyarrow.parquet.ParquetFile] = _pyarrow_parquet_file_wrapper(\n",
    "  File \"/var/task/awswrangler/s3/_read_parquet.py\", line 42, in _pyarrow_parquet_file_wrapper\n    return pyarrow.parquet.ParquetFile(\n",
    "  File \"/var/task/pyarrow/parquet.py\", line 230, in __init__\n    self.reader.open(\n",
    "  File \"pyarrow/_parquet.pyx\", line 991, in pyarrow._parquet.ParquetReader.open\n    check_status(builder.Open(rd_handle, properties, c_metadata))\n",
    "  File \"pyarrow/error.pxi\", line 99, in pyarrow.lib.check_status\n    raise ArrowInvalid(message)\n"
  ]
}
```

### How to Reproduce

* Create glue table 
* Try to call `wr.s3.merge_upsert_table(`

### Expected behavior

success with the first data written to table files

### Screenshots

<img width="917" alt="image" src="https://user-images.githubusercontent.com/7450573/187547781-62b8c6f7-1609-468c-9bf2-358e661e3450.png">

### OS

AWS lambda linux

### Python version

3.9

### AWS SDK for pandas version

2.6.1 IMO

**Comment by LeonLuttenberger** [comment]
Hey,

Thanks for submitting this issue. I agree with your idea of the expected behavior. If a Glue table is already defined but empty, we should simply perform an insert.

However, I was not able to replicate the exact error you received. In my testing, the error I received was:
```
NoFilesFound: No files Found on: s3://aws-sdk-pandas-base-awssdkpandas2c9af251-2xcd1unijfnt/table/.
```

Can you double check whether you have an empty metadata file in your path that's causing this different error?

Best regards,
Leon

**Comment by borodark** [comment]
AWESOME! 10x guys for speed!

**Comment by LeonLuttenberger** [comment]
Thank you for bringing this to our attention. We will plan this release for version `2.17.x`.
