### ISSUE TITLE
The `ray_remote` function does not support setting options such as `resources` or `max_retries`

### ISSUE THREAD

**Issue by LeonLuttenberger** [aws/aws-sdk-pandas#1563]
**Is your idea related to a problem? Please describe.**
The currently defined `ray_remote` function does not allow us to define options for the function which it is decorating. For example, I would like to be able to decorate an API blocking function with something like `resources={"CPU": 0.25}`  so that the operation does not consume all a CPU's capacity.

These settings exist on the default [ray.remote decorator](https://docs.ray.io/en/latest/ray-core/package-ref.html#ray-remote).

**Describe the solution you'd like**
TODO

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by kukushking** [comment]
Done with #1734
