### ISSUE TITLE
quicksight.create_athena_dataset(): wrong type hint for TagColumnOperation

### ISSUE THREAD

**Issue by koberghe** [aws/aws-sdk-pandas#1569]
### Describe the bug

The parameter` tag_colums` was added in added in [this issue](https://github.com/aws/aws-sdk-pandas/issues/1340) with the type hint:
`tag_columns: Optional[Dict[str, str]]`

I believe it should be
`tag_columns: Optional[Dict[str, list]],`

### How to Reproduce

Using the example `{"col_name": [{ "ColumnGeographicRole": "CITY" }]` from the docs produces a type warning in Pycharm.

### OS

Win

### Python version

3.9

### AWS SDK for pandas version

2.16.1

**Comment by LeonLuttenberger** [comment]
Hey @koberghe. Thanks for pointing out this issue. It should be fixed in #1570. We will most likely plan for this in `2.17.x`.
