### ISSUE TITLE
Empty List or Map not handled with Athena

### ISSUE THREAD

**Issue by louisdvs** [aws/aws-sdk-pandas#1577]
### Describe the bug

When querying Map/List types with an empty row (e.g. [] or {}) using `ctas=True` or `unload=True` we hit the error: 
`Parquet record is malformed: empty fields are illegal, the field should be ommited completely instead`

Using the csv method with `ctas=False` we get an unsupported type error.

Tracing back the parquet error it seems like it is due to a [known Hive bug](https://issues.apache.org/jira/browse/HIVE-11625) that we hit trying to do an unload directly in the Athena console.

Is there any thoughts around how to handle this? Handling with some coersion of empty list/map to Nulls isn't really an option for us.

### How to Reproduce

In Athena console (which uses csv under the hood) we can do something like:
```
SELECT names from foo.bar
>> names
>> []
>> ["Sarah"]
```

using AWS wrangler:
```
athena.read_sql_query(
  "SELECT names from foo.bar",
   "foo",
   workgroup="example",
   boto3_session=boto3_session,
   ctas_approach=True,
)
>> Parquet record is malformed: empty fields are illegal, the field should be ommited completely instead
```

### Expected behavior

We would like to be able to use at least one of the methods (CTAS, UNLOAD, CSV) to query map/list types using wrangler.

### OS

Linux

### Python version

3.8

### AWS SDK for pandas version

2.14

**Comment by kukushking** [comment]
Hi @louisdvs for csv-based CTAS approach we can at least handle these types including when they're empty by casting to object. These are the results after adding the casting:
```
import awswrangler as wr
import pandas as pd

df = pd.DataFrame({"c0": [[1, 2, 3], [4, 5, 6]], "c1": [[], []], "c2": [{"a": 1, "b": 2}, {"a": 3, "b": 4}], "c3": [{}, {}], "c4": [[("e", 1), ("f", 2)], [("e", 3), ("f", 4)]], "c5": [[], []]})

wr.s3.to_parquet(
    df=df,
    path=path,
    dataset=True,
    database="default",
    table=table,
    dtype={"c0": "array<double>", "c1": "array<double>", "c2": "struct<a:bigint,b:double>", "c3": "struct<c:bigint,d:double>", "c4": "map<string,int>", "c5": "map<string,int>"},
)
wr.athena.read_sql_table(table=table, database="default", ctas_approach=False)

                c0  c1            c2                c3          c4  c5
0  [1.0, 2.0, 3.0]  []  {a=1, b=2.0}  {c=null, d=null}  {e=1, f=2}  {}
1  [4.0, 5.0, 6.0]  []  {a=3, b=4.0}  {c=null, d=null}  {e=3, f=4}  {}
```

I'll also check if there is something we can do for parquet-based UNLOAD, too

**Comment by louisdvs** [comment]
@kukushking That is great, we toyed with a PR but weren't sure if it would align (feels a little clunky to map a list or map to a object but works 🤷 )

It would be great to get something working for CTAS and UNLOAD, but I think the empty List/Map bug it feels like the empty list bug in hive will need to be resolved first, to allow writing the query results out as parquet.

Thanks for your input 👍

**Comment by kukushking** [comment]
@louisdvs It does feel very clunky, but I guess it's better than nothing. If you have any alternative idea would be happy to give it a try.

Yep, with regards to CTAS/UNLOAD I agree it's ultimately Hive's issue and there's little we can do, other than obviously avoid writing null arrays/maps in the first place
