### ISSUE TITLE
s3.read_parquet(map_types) handles int and string inconsistently

### ISSUE THREAD

**Issue by marcelmindemann** [aws/aws-sdk-pandas#1589]
### Describe the bug

`awswrangler.s3.read_parquet()` has the keyword argument `map_types`. In my understanding, it should decide whether awswrangler applies dtype mapping on top of the pandas schema that already exists in the parquet header metadata. `map_types=False` should return a DataFrame with exactly the schema that's set in the metadata header. If this understanding is false, this bug report may be invalid. The problem is that setting `map_types=False` applies dtype mapping to some columns and not to others, specifically with `int64` and `string` columns.

### How to Reproduce

The problem is with a DataFrame with a column of type `int64` and `string`:
<img width="813" alt="Screen Shot 2022-09-07 at 16 41 30" src="https://user-images.githubusercontent.com/12549786/189309204-19b0c686-15e4-414f-85d4-29e935d4854c.png">
If I save this DataFrame to S3 using `s3.write_parquet`, it correctly writes these types to the parquet header:
<img width="1873" alt="Screen Shot 2022-09-07 at 16 40 49" src="https://user-images.githubusercontent.com/12549786/189309341-fd2a3734-7ef3-45ae-b620-53cf0a57137d.png">
The problem is reading back the same DataFrame using `s3.read_parquet` - neither `True` nor `False` for the `map_types` argument provides round-trip consistency. If it's `True`, the `int64` column becomes `Int64`, if it's `False`, the `string` column becomes type `object`:
<img width="1001" alt="Screen Shot 2022-09-07 at 16 37 53" src="https://user-images.githubusercontent.com/12549786/189309841-87e4dbc1-2b71-4150-b157-7ffb570baad6.png">

### Expected behavior

I would expect awswrangler to provide round-trip consistency in some way, even though it does not have to be enabled by default.

### OS

macOS

### Python version

3.9.10

### AWS SDK for pandas version

2.16.1

### Additional context

Versions:
`awswrangler 2.16.1`
`pyarrow 7.0.0`
`pandas 1.4.3`

**Comment by jaidisido** [comment]
Thanks for raising this @marcelmindemann. I can confirm that this is an issue in the current `awswrangler` versions. It stems from the fact that we don't give enough flexibility to the user when it comes to converting from an arrow table to a pandas DataFrame. As you can see [here](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/s3/_read_parquet.py#L313), we enforce `ignore_metadata=True` for instance, which leads to situations like the one you raised.

Good news is that we intend to fix [this](https://github.com/aws/aws-sdk-pandas/blob/fc612fca229780cbbb1cea5537267a828c578279/awswrangler/_data_types.py#L541) in the next major release (3.0) by enabling the user to override params passed to the `to_pandas` method. You can already test it:
```
pip install awswrangler==3.0.0a2
```
then:
```
import awswrangler as wr

path = "s3://my-bucket/my-path"

df = wr.s3.read_parquet(path=path, pyarrow_additional_kwargs={"ignore_metadata": False, "types_mapper": None})

df.dtypes
some_integer     int64
some_string     string
dtype: object
```
