### ISSUE TITLE
Navbar overflows with the new documentation website

### ISSUE THREAD

**Issue by knowsuchagency** [aws/aws-sdk-pandas#1595]
### Describe the bug

The search form in the navbar overflows on the [new documentation website](https://aws-sdk-pandas.readthedocs.io/en/latest/), covering part of the initial paragraph.

This seems to be caused by the `a.navbar-brand` element of the navbar having more characters than it previously did.

![image](https://user-images.githubusercontent.com/11974795/189442161-bdb5d389-b0a6-4fc5-bc46-257bba88d620.png)

### How to Reproduce

Replace `AWS Data Wrangler` with `AWS SDK for pandas` on the [legacy site](https://aws-sdk-pandas.readthedocs.io/en/stable/)

### Expected behavior

Navbar elements are all on the same row

### Screenshots

![image](https://user-images.githubusercontent.com/11974795/189442161-bdb5d389-b0a6-4fc5-bc46-257bba88d620.png)

### OS

Mac

### Python version

N/A

### AWS SDK for pandas version

2.16.1

**Comment by malachi-constant** [comment]
Looks like Chrome can handle, but yes this is an issue in Safari, Firefox and potentially other browsers.

<img width="1722" alt="Screen Shot 2022-09-12 at 8 21 18 AM" src="https://user-images.githubusercontent.com/6465221/189692661-fa920e14-758c-462b-b645-81b3829bcafe.png">
