### ISSUE TITLE
Inconsistent argument names

### ISSUE THREAD

**Issue by vpietilainen** [aws/aws-sdk-pandas#1612]
Argument names seem inconsistent. In `athena.read_sql_query` we have arguments `database` and `ctas_database_name`, whereas in `athena.create_ctas_table` we have `database` and `ctas_database`. It seems that `_name` suffix would not be necessary. 

In addition it would be nice if `ctas_database` could be read from environmental variables.

**Comment by jaidisido** [comment]
Appreciate that the names are inconsistent across the methods, however changing them would be a breaking change for users. We might want to consider it in our next major version (3.0).
