### ISSUE TITLE
Allow to pass in additional arguments to Timestream create table

### ISSUE THREAD

**Issue by farridav** [aws/aws-sdk-pandas#1629]
It would be great if we could pass arguments through to the boto client in the `awswrangler.timestream.create_table` call See https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.timestream.create_table.html#awswrangler.timestream.create_table

At the moment, it is quite limited

**Describe the solution you'd like**
To be able to pass in additional arguments to the boto3 client creating the table e.g  `MagneticStoreWriteProperties` as in https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/timestream-write.html#TimestreamWrite.Client.create_table

A generic solution (e.g **kwargs) might make this a big benefit across other parts of the API, especially when something is added to boto that is not yet covered by awswrangler

Thanks for all your hard work

**Comment by malachi-constant** [comment]
Thanks for opening this @farridav. Makes sense to me to add this so I'll put it in the backlog. We always welcome contributions, but will get to at as soon as time permits.

**Comment by cnfait** [comment]
added with #1819
