### ISSUE TITLE
[Support Us]: Funding Circle

### ISSUE THREAD

**Issue by pfig** [aws/aws-sdk-pandas#1639]
Thank you for letting us use your organization's name on the repository read.me page and letting other customers know that you support the project!  If you would like us to also display your organization's logo. please raise a pull request to provide an image file for the logo.

Please add any files to *docs/source/_static/*

Organization Name: [Funding Circle](https://fundingcircle.com/)
Your Name: Pedro Figueiredo
Your Position: Data Architect
I have included a logo: n

*By raising a Support Us issue (and related pull request), you are granting AWS permission to use your company’s name (and logo) for the limited purpose described here and you are confirming that you have authority to grant such permission.*

**Comment by kukushking** [comment]
Thank you! Added to the [list](https://github.com/aws/aws-sdk-pandas/commit/cdb185f1b23beb8a415bcf1b3e61227629ba33df)
