### ISSUE TITLE
s3.copy_objects() replace filenames wild card

### ISSUE THREAD

**Issue by spencervoorend** [aws/aws-sdk-pandas#1643]
I can't seem to get the wild card to work with the replace_filenames parameter. I may be doing it incorrectly but I want to change the file type suffix with the code: 
`replace_filenames= {'*.dat': '*.csv'}`

**Comment by jaidisido** [comment]
I don't believe that parameter supports UNIX shell wild cards, did you see that somewhere in the docs?
