### ISSUE TITLE
unload does not support quotes in query string

### ISSUE THREAD

**Issue by gloriamacia** [aws/aws-sdk-pandas#1652]
### Describe the bug

```
country_cd = "FR"
crm_names_query = f"""select hlc.hcp_crm_pk, hcn.hcp_name, hcn.hcp_name_embeddings from pubmed.hcp_crm_names_embeddings hcn join informa.hcp_linking_cnet hlc on hcn.hcp_crm_pk = hlc.hcp_crm_pk where hlc.country_cd = \'{country_cd}\' and hlc.investigator_id is null"""
```

While the following query works perfectly in wr.read_sql_query, it throws an error in unload, complaining of unsupported character around "FR" (I pasted the query to essentially show that I even tried escape characters) 

```
df_iterator = wr.redshift.unload(
    sql=crm_names_query,
    path="<path>",
    con=con_redshift,
    iam_role="arn:aws:iam::<role>",
    chunked=True,
    keep_files=False,
    use_threads=True,
)
```

### How to Reproduce

Run any SQL with quotes in it. Same happens with limit statement or where conditions, as if unload was only able to deal with "select * from table" kind of statements but there is no explanation on the docs of its behavior and the reasons behind. 

### OS

Linux

### Python version

3.8

### AWS SDK for pandas version

1.16.0

**Comment by jaidisido** [comment]
Hi @gloriamacia, have you tried the following?
https://stackoverflow.com/questions/55191070/how-to-handle-quoted-values-in-aws-redshift-unload-command

**Comment by gloriamacia** [comment]
it worked! thanks a lot @jaidisido
