### ISSUE TITLE
How do we increase retry attempts and timeout for read_parquet?

### ISSUE THREAD

**Issue by VijayDeyTR** [aws/aws-sdk-pandas#1655]

**Comment by jaidisido** [comment]
If you are referring to the retries from the botocore configuration, please follow this [tutorial](https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/021%20-%20Global%20Configurations.html) (botocore_config). Otherwise please provide more details

**Comment by VijayDeyTR** [comment]
Yup ! t

**Comment by VijayDeyTR** [comment]
Yup, thanks!
