### ISSUE TITLE
s3 read_json doesn't support parameter "lines"

### ISSUE THREAD

**Issue by adaspadas** [aws/aws-sdk-pandas#1658]
pandas read_json has parameter "lines", which by default is to False.

As I understand aws-sdk-pandas doesn't support this feature, so on lambda I tried to use pandas library, which comes together with sdk layer. 

`df = pd.read_json(f"s3://{bucket}/{file}", lines=True)`

However, I'm facing this error:

`[ERROR] ImportError: Missing optional dependency 'fsspec'.  Use pip or conda to install fsspec.`

**Comment by jaidisido** [comment]
I believe `lines=True` should already be supported in the [wr.s3.read_json](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.s3.read_json.html#awswrangler.s3.read_json) method (see example 4)
