### ISSUE TITLE
Do you plan to support passing full pyarrow schema in awswrangler.s3.read_parquet method?

### ISSUE THREAD

**Issue by tsaluszewski** [aws/aws-sdk-pandas#1662]
The current [read_parquet](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.s3.read_parquet.html#awswrangler.s3.read_parquet) supports limited `pyarrow_additional_kwargs` arguments. 

We do require passing an explicit pyarrow `schema` into this method in order to avoid issues with inferring incorrect schema from "schema mixed" parquet files (i.e. one file with `updated_at` field and the other without produce wrong merged schema effectively loosing `updated_at` content).

This can be solved with `pyarrow` as dependency from version >=8, see [pyarrow.parquet.read_table](https://arrow.apache.org/docs/8.0/python/generated/pyarrow.parquet.read_table.html), but it is not compatible with the latest version of `aws-sdk-pandas` :(

We can see two options really:
- abandon `aws-sdk-pandas` and re-implement `read_parquet` with the bare bone `pyarrow.parquet.read_table`;
- wait for `aws-sdk-pandas` to be upgraded to pyarrow >=8.0 supporting `pyarrow` schema in the `awswrangler.s3.read_parquet` method.

Do you plan to support pyarrow `schema` in the future, if so when we can expect this feature to be included? :)

Regards,
Samotics Data Engineering.

**Comment by kukushking** [comment]
Hi @tsaluszewski, thanks for opening this. At the moment schema is read from the files and then validated. It should be possible to add a parameter to pass the schema and use that for validation. I'll look into adding this.

**Comment by kukushking** [comment]
Unfortunately looks like indeed the ability to pass the schema is only available starting from pyarrow 8. 

We do try to keep our dependencies up-to-date but I can't provide a specific timeline of the upgrade at this point as we have other dependencies that have their own pyarrow version constraints. 

I will keep this open so it's on the radar

**Comment by bt-** [comment]
I would find this a useful feature as well, thanks!
