### ISSUE TITLE
Bad output of `awswrangler.athena.read_sql_query()` when specifying `chunksize` and query is empty

### ISSUE THREAD

**Issue by AlexMetsai** [aws/aws-sdk-pandas#1683]
### Describe the bug

When the query result is empty, `awswrangler.athena.read_sql_query()` returns a list of strings that correspond to the _column names_ instead of an empty dataframe. This silent error results into pretty cryptic error messages in subsequent parts of the code. It is therefore my opinion that this should not be the default behanior, instead the function should return an empty _pandas DataFrame_, that can be easily checked whether it contains rows or not.

### How to Reproduce

```
import awswrangler as wr
query = """A query that will return empty result."""
for df in wr.athena.read_sql_query(query, ctas_approach=True, chunksize=100):
    print(type(df))  # <class 'str'> (column names)
```

### Expected behavior

I would expect the the function to return an empty `pd.DataFrame`.

### OS

GNU/Linux

### Python version

3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]

### AWS SDK for pandas version

2.16.1

**Comment by LeonLuttenberger** [comment]
Hey,

Thank you for bringing this to our attention. I have merged a PR which fixes this issue. We will publish this with our next release.

Best regards,
Leon
