### ISSUE TITLE
Athena no longer creates a default query results location but Wrangler still does

### ISSUE THREAD

**Issue by koberghe** [aws/aws-sdk-pandas#1707]
I just noticed that Athena no longer creates a default query results location ( s3://aws-athena-query-results-ACCOUNT-REGION/) according to their [documentation](https://docs.aws.amazon.com/athena/latest/ug/querying.html). In wrangler, however, this is still the case (`create_athena_bucket()`).

I don't know why AWS decided to remove this feature. I found it useful. But I wonder if this could now be considered as an inconsistency between wrangler and Athena which could lead to confusion. Probably not terribly important but I thought I would share this observation anyways.

**Comment by kukushking** [comment]
Thank you @koberghe for sharing this. I agree it's a useful feature. Let me discuss this with the team
