### ISSUE TITLE
New timestream endpoint url uses incorrect service name 

### ISSUE THREAD

**Issue by zreyn** [aws/aws-sdk-pandas#1710]
For the recent timestream_endpoint_url addition, there's a check for service name being 'timestream':
https://github.com/aws/aws-sdk-pandas/blob/be0bbe4b7d481d57bcf61432c528fcbf420b136a/awswrangler/_utils.py#L102

However, timestream service names are 'timestream-query' and 'timestream-write':
https://github.com/aws/aws-sdk-pandas/blob/c5d534351d44607835cbc96a6fb581976f347f34/awswrangler/timestream.py#L149
https://github.com/aws/aws-sdk-pandas/blob/c5d534351d44607835cbc96a6fb581976f347f34/awswrangler/timestream.py#L42

So, setting the endpoint url has no effect.  

![Screen Shot 2022-10-25 at 10 04 07 AM](https://user-images.githubusercontent.com/10354900/197795043-4186e801-e6a6-455f-88e8-40b1a7f697e1.png)

**Comment by malachi-constant** [comment]
Thanks @zreyn for catching this and alerting the team. [PR](https://github.com/aws/aws-sdk-pandas/pull/1716) above 🐼
