### ISSUE TITLE
Revise index recovery tests

### ISSUE THREAD

**Issue by kukushking** [aws/aws-sdk-pandas#1718]
### Describe the bug

A while ago 8 s3 parquet tests were marked as xfail supposedly due to regression in pandas. We need to revise if the problem is still present and if it's possible to resolve it now.

Enabled the tests in the branch [tests/remove-index-eq-xfail](https://github.com/aws/aws-sdk-pandas/tree/tests/remove-index-eq-xfail)

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### OS

OSX

### Python version

3.9

### AWS SDK for pandas version

2.17.1

**Comment by jaidisido** [comment]
Tested this and the `AssertionError` is still present with pandas 1.5.3 and modin 0.19.0
