### ISSUE TITLE
why aws-data-wrangler-layer-py3-9 is deprecated?

### ISSUE THREAD

**Issue by ijtarano** [aws/aws-sdk-pandas#1719]
Hi everybody, I would like to know why official lambda layer of this library is deprecated in AWS. Thank you!

![image](https://user-images.githubusercontent.com/78363326/197997130-9e81a82d-c14b-412b-afa5-137182316c71.png)

https://serverlessrepo.aws.amazon.com/applications/us-east-1/336392948345/aws-data-wrangler-layer-py3-9

**Comment by jaidisido** [comment]
Hi @ijtarano, the library has recently gone through a rename from `aws-data-wrangler` to `aws-sdk-pandas`. The SAR app is still available but simply under a different name:
<img width="939" alt="image" src="https://user-images.githubusercontent.com/16362107/197998861-8f47bcba-cff3-454d-ab3b-0b35a4d433fa.png">

As result of that change we have deprecated the old versions to avoid confusion.

**Comment by ijtarano** [comment]
OMG, thank you so mucho @jaidisido!!
