### ISSUE TITLE
enforce right data types in awswrangler.redshift.copy_from_files with error throwing type checks

### ISSUE THREAD

**Issue by gloriamacia** [aws/aws-sdk-pandas#1726]
My team was facing a very strange error (see below) due to a very silly mistake. 

Essentially the docs ask for the primary key to be a list of strings:

`primary_keys (List[str], optional) – Primary keys.
`
From https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.redshift.copy_from_files.html#awswrangler.redshift.copy_from_files

Now the problem is that my developer decided to pass a string "hcp_crm_pk" instead of "[hcp_crm_pk]". What the code did is to parse the string as a list, being the first element the letter h. Strings are also iterables so no error at this point was thrown, instead later on the following messaged appeared. 
```

KeyError                                  Traceback (most recent call last)
File ~/.conda/envs/informa/lib/python3.8/site-packages/redshift_connector/core.py:1631, in Connection.execute(self, cursor, operation, vals)
   1630 try:
-> 1631     ps = cache["ps"][key]
   1632     [cursor.ps ](https://support.console.aws.amazon.com/support/cursor.ps) = ps

KeyError: ('DELETE FROM "informa"."test" USING temp_redshift_6803a4db551b4aa3a266c50c4a0ad4f8 WHERE test.h = temp_redshift_6803a4db551b4aa3a266c50c4a0ad4f8.h AND test.c = temp_redshift_6803a4db551b4aa3a266c50c4a0ad4f8.c AND test.p = temp_redshift_6803a4db551b4aa3a266c50c4a0ad4f8.p AND test._ = temp_redshift_6803a4db551b4aa3a266c50c4a0ad4f8._ AND test.c = temp_redshift_6803a4db551b4aa3a266c50c4a0ad4f8.c AND test.r = temp_redshift_6803a4db551b4aa3a266c50c4a0ad4f8.r AND test.m = temp_redshift_6803a4db551b4aa3a266c50c4a0ad4f8.m AND test._ = temp_redshift_6803a4db551b4aa3a266c50c4a0ad4f8._ AND test.p = temp_redshift_6803a4db551b4aa3a266c50c4a0ad4f8.p AND test.k = temp_redshift_6803a4db551b4aa3a266c50c4a0ad4f8.k', ())

During handling of the above exception, another exception occurred:

ProgrammingError: {'S': 'ERROR', 'C': '42703', 'M': 'column test.h does not exist', 'F': '../src/pg/src/backend/parser/parse_func.c', 'L': '3654', 'R': 'unknown_attribute'}


```

Though now seems very obvious to us it took us a day to realize the reason, we believe type checking (throwing an error if not list) would be very useful to avoid this type of errors.

**Comment by malachi-constant** [comment]
Hi @gloriamacia thanks for opening this. I agree it would be valuable to do parameter validation here. I'll get a PR started.
