### ISSUE TITLE
Configurable Block Size for Parquet Files

### ISSUE THREAD

**Issue by stewmi** [aws/aws-sdk-pandas#1737]
**Is your idea related to a problem? Please describe.**
I am using to create parquet files, but the block size of the generated files is too big for S3 select and I cannot see any options to configure that (I would have assumed the default would work with S3 select, but ...)

**Describe the solution you'd like**
I would like to see a flag or a configuration file that a block size can be set for Parquet as S3 Select and other services use different parquet files.

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
I am not sure I understand the ask here @stewmi, are you referring to a specific input parameter to the S3 select [call](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.select_object_content) that you feel is missing?
