### ISSUE TITLE
When using the EMR client, the code does not use extra_public_registries argument

### ISSUE THREAD

**Issue by vikramsg** [aws/aws-sdk-pandas#1755]
### Describe the bug

If I setup an EMR cluster using the `extra_public_registries` argument, I expect it to be available in the EMR cluster that is created. But I only see the default registries. 

I think this is because of the code that is here. 
https://github.com/aws/aws-sdk-pandas/blob/d0e82c0fb3bc09c6a13aa2de19c13c0c32192489/awswrangler/emr.py#L161

```
if pars["docker"] is True:
        if pars.get("extra_registries") is None:
            extra_registries: List[str] = []
        else:
            extra_registries = pars["extra_registries"]
```

So, the argument should be `extra_registries` instead of `extra_public_registries`. I can open a PR if I am correct.

### How to Reproduce

```
cluster_id = wr.emr.create_cluster(
    cluster_name="vikram-emr-cluster",
    logging_s3_path=f"s3://{emr_bucket}/logs/",
    emr_release="emr-6.7.0",
    subnet_id=subnet,
    emr_ec2_role="EMR_EC2_DefaultRole",
    emr_role="EMR_DefaultRole",
    instance_type_master="m5.xlarge",
    instance_type_core="m5.xlarge",
    instance_ebs_size_master=50,
    instance_ebs_size_core=50,
    instance_num_on_demand_master=0,
    instance_num_on_demand_core=0,
    instance_num_spot_master=1,
    instance_num_spot_core=2,
    spot_bid_percentage_of_on_demand_master=100,
    spot_bid_percentage_of_on_demand_core=100,
    spot_provisioning_timeout_master=5,
    spot_provisioning_timeout_core=5,
    spot_timeout_to_on_demand_master=False,
    spot_timeout_to_on_demand_core=False,
    python3=True,
    spark_glue_catalog=True,
    hive_glue_catalog=True,
    presto_glue_catalog=True,
    debugging=True,
    applications=["Hadoop", "Spark", "Hive", "Zeppelin", "Livy", "JupyterEnterpriseGateway", "JupyterHub"],
    visible_to_all_users=False,
    maximize_resource_allocation=True,
    keep_cluster_alive_when_no_steps=True,
    termination_protected=False,
    spark_pyarrow=True, 
    docker=True,
    extra_public_registries="9xxxxx.dkr.ecr.eu-west-1.amazonaws.com"
)
```

### Expected behavior

In the EMR cluster created I expect to see the following. 

```
container-executor.docker | docker.privileged-containers.registries | local,centos,6xxxx.dkr.ecr.eu-west-1.amazonaws.com, 9xxxxx.dkr.ecr.eu-west-1.amazonaws.com| 
```

### OS

Mac

### Python version

3.8

### AWS SDK for pandas version

2.17

**Comment by LeonLuttenberger** [comment]
Hey @vikramsg, thanks for opening the issue. Yes, this is indeed a bug in our codebase.

I would keep the input parameter as `extra_public_registries` in order to avoid API changes. Instead, line 161 in `emr.py` can simply be changed to reference `extra_public_registries` instead of `extra_registries`.

**Comment by vikramsg** [comment]
Hi @LeonLuttenberger ,

Thanks for the response. I have opened a PR. Please have a look.
