### ISSUE TITLE
Swap JDBC for Arrow ADBC

### ISSUE THREAD

**Issue by jaidisido** [aws/aws-sdk-pandas#1756]
Leveraging the Arrow ADBC Driver has a number of advantages:
- A single, universal driver would replace all existing, proprietary drivers (mssql, postgres...)
- Better performance due to not processing each row separately and tapping into pyarrow to avoid serialization/deserialization

**Additional context**
https://arrow.apache.org/docs/dev/format/ADBC.html

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by LeonLuttenberger** [comment]
The implementation for this is in progress for Postgresql (see [development branch](https://github.com/aws/aws-sdk-pandas/tree/feat/arrow-dbc)). However, we are currently blocked by this bug in Pandas: https://github.com/pandas-dev/pandas/issues/57539
