### ISSUE TITLE
ResponseParserError: Unable to parse response (no element found: line 2, column 0), invalid XML received. Further retries may succeed: b'<?xml version="1.0" encoding="UTF-8"?>\n'

### ISSUE THREAD

**Issue by pedromonteiro18** [aws/aws-sdk-pandas#1769]
### Describe the bug

ResponseParserError when SDK executes s3 delete operation within AWS. Possibly related to this [issue](https://github.com/boto/boto3/issues/1961) which occurs when boto3 client is shared between threads, however from what I can see, the client is not being shared between threads (although I may be wrong) so I am unable to determine the root cause. Error happens intermittently and cannot be reproduced by running with the same inputs. 

Error occurs when executing awswrangler.s3._delete._delete_objects:

@timestamp | 1668185640811
-- | --
lambda_request_id | ada5dcda-007c-548e-b4ad-8732801a4b71
level | DEBUG
location | awswrangler.s3._delete._delete_objects:40
message | len(keys): 1
timestamp | 2022-11-11 16:54:00,811`

Error log:
`ResponseParserError: Unable to parse response (no element found: line 2, column 0), invalid XML received. Further retries may succeed:
b'<?xml version="1.0" encoding="UTF-8"?>\n'
Traceback (most recent call last):
    response = wr.s3.to_parquet(
  File "/var/task/awswrangler/_config.py", line 450, in wrapper
    return function(**args)
  File "/var/task/awswrangler/s3/_write_parquet.py", line 640, in to_parquet
    paths, partitions_values = _to_dataset(
  File "/var/task/awswrangler/s3/_write_dataset.py", line 210, in _to_dataset
    paths, partitions_values = _to_partitions(
  File "/var/task/awswrangler/s3/_write_dataset.py", line 68, in _to_partitions
    delete_objects(
  File "/var/task/awswrangler/s3/_delete.py", line 155, in delete_objects
    _delete_objects(
  File "/var/task/awswrangler/s3/_delete.py", line 48, in _delete_objects
    res = client_s3.delete_objects(Bucket=bucket, Delete={"Objects": batch}, **extra_kwargs)
  File "/var/task/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 921, in _make_api_call
    http, parsed_response = self._make_request(
  File "/var/task/botocore/client.py", line 944, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/var/task/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/var/task/botocore/endpoint.py", line 199, in _send_request
    success_response, exception = self._get_response(
  File "/var/task/botocore/endpoint.py", line 241, in _get_response
    success_response, exception = self._do_get_response(
  File "/var/task/botocore/endpoint.py", line 308, in _do_get_response
    parsed_response = parser.parse(
  File "/var/task/botocore/parsers.py", line 251, in parse
    parsed = self._do_parse(response, shape)
  File "/var/task/botocore/parsers.py", line 880, in _do_parse
    self._add_modeled_parse(response, shape, final_parsed)
  File "/var/task/botocore/parsers.py", line 890, in _add_modeled_parse
    self._parse_payload(response, shape, member_shapes, final_parsed)
  File "/var/task/botocore/parsers.py", line 931, in _parse_payload
    original_parsed = self._initial_body_parse(response['body'])
  File "/var/task/botocore/parsers.py", line 1032, in _initial_body_parse
    return self._parse_xml_string_to_dom(xml_string)
  File "/var/task/botocore/parsers.py", line 505, in _parse_xml_string_to_dom
    raise ResponseParserError(`

### How to Reproduce

Unable to reproduce. Error happens intermittently. 

### OS

Running in AWS lambda

### Python version

3.8

### AWS SDK for pandas version

2.13.0

**Comment by kukushking** [comment]
HI @pedromonteiro18 thanks for opening this. We do end up sharing sessions between the threads (or rather constructing different session objects from the same credentials using [boto3_to_primitives](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/_utils.py#L40). Boto3 sessions and clients aren't thread-safe but probably re-using the credentials is what's causing this is in the first place

**Comment by nurdann** [comment]
I tried using threading and multiprocessing and received the same exception occasionally. And even creating session with a threaded/multiprocessed function did not eliminate the error from happening,
```
boto3.Session(profile_name="myprofile").client("s3")
```
Do you mean there's no way to around this problem? Or what is its cause?

**Comment by Irinucc** [comment]
Hello @kukushking, is there a plan to fix the issue? In our case, we implemented alarms that gets triggered multiple times during a week due to this issue.

**Comment by kukushking** [comment]
@Irinucc As discussed in private convo, we're working on a fix. Unfortunately this touches a couple of core things about our library (the way we manage sessions and clients) so the fix will take a bit of time

**Comment by kukushking** [comment]
Hi @Irinucc @nurdann @pedromonteiro18 , we've merged the [PR](https://github.com/aws/aws-sdk-pandas/pull/1957) that removes session serialization/deserialization logic. It will be shipped with the next release, meanwhile you can give it a try by installing from main and let us know if that fixes your problem:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```
Thank you!
