### ISSUE TITLE
Pytest Coverage Distributed / Non Distributed

### ISSUE THREAD

**Issue by malachi-constant** [aws/aws-sdk-pandas#1776]
**Is your idea related to a problem? Please describe.**
- Implement pytest coverage reports consistently across library testing.
- Agree upon acceptable thresholds testing should meet.
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
Coverage now in place in CBs
