### ISSUE TITLE
Support CTAS write_compression in `wr.athena.read_sql_query`

### ISSUE THREAD

**Issue by morokosi** [aws/aws-sdk-pandas#1793]
**Describe the solution you'd like**
If we could specify write_compression in `wr.athena.read_sql_query(ctas_approach=True)`, we could reduce network transfers and further speed up data reading.

**Comment by LeonLuttenberger** [comment]
Hey, thanks for opening this issue up. We'll add it to our backlog.

**Comment by LeonLuttenberger** [comment]
I have merged the PR and we will release this as part of [2.18.0](https://github.com/aws/aws-sdk-pandas/pull/1807)
