### ISSUE TITLE
Where do we find the endpoint url in order to connect to it with AWS Data Wrangler?

### ISSUE THREAD

**Issue by AdrianoNicolucci** [aws/aws-sdk-pandas#1794]
I am running a lambda within a VPC and would like to read data from AWS S3 in which an endpoint has already been established. 

I believe I need to connect to it with AWS Data wrangler using `wr.config.s3_endpoint_url = s3_endpoint_url`.
Where do I find the full URL in my AWS Account in order to establish the endpoint for AWS S3 with AWS Data Wrangler? If there is no one location to find it, how do I calculate what the endpoint url should be? I believe it should be something like "https://bucket.vpce-xxxxxxxxxxxxxxxxx-xxxxxxxx.s3.ca-central-1.vpce.amazonaws.com"

**Comment by malachi-constant** [comment]
If this is an interface endpoint you should be able to find the DNS entry for the endpoint in the [console](https://ca-central-1.console.aws.amazon.com/vpc/home?region=ca-central-1#Endpoints:) under **Details/DNS Names** or via the cli: 
```
aws ec2 describe-vpc-endpoints
```

[More info ](https://docs.aws.amazon.com/AmazonS3/latest/userguide/privatelink-interface-endpoints.html#types-of-vpc-endpoints-for-s3)on S3 Gateway & Interface endpoints and their differences.

**Comment by AdrianoNicolucci** [comment]
For Amazon S3, it is a gateway and there is no entry in the DNS Names unfortunatelty.

**Comment by malachi-constant** [comment]
So as long as the request originates from a subnet with routes to the S3 Gateway endpoint there is no additional configuration required. If your lambda is in a subnet with the above, you do not need to set `wr.config.s3_endpoint_url`.

**Comment by AdrianoNicolucci** [comment]
Thank you! You are correct this works no additional configuration is required if the lambda function is in the vpc with the gateway endpoint configured. I'm closing this question.
