### ISSUE TITLE
AWS Wrangler S3 reading parquet, writing to DynamoDB - Unsupported type numpy.ndarray

### ISSUE THREAD

**Issue by NNM-UV** [aws/aws-sdk-pandas#1796]
I am trying to read parquet into dataframe with AWS wrangler, while writing this data to DynamoDB its erroring out with unsupported type error - Unsupported type numpy.ndarray for value.......

```
wr.s3.read_parquet(path=s3_path, dataset=dataset, chunked=True)

and writing like 

wr.dynamodb.put_df(df=df, table_name=table_name)
```

Is there a way, I can convert the ndarray type to dynamoDB list ? I dont want to lose the readability of the array if I use np.tobytes() to write and np.frombuffer() to read again. Also, users will not have access Numpy to read the data from DynamoDB, they will be using dynamoDB API for data read

**Comment by jaidisido** [comment]
Could you please provide an example of the data you are trying to read. It does not need to be the exact data, a dummy example with a data frame would help us debug this, thanks

**Comment by NNM-UV** [comment]
["APS3200", "APS3240A", "APS3240E", "APS3400"]
or
![image](https://user-images.githubusercontent.com/118927963/203802069-8a4e2bc8-e2b2-4462-ad93-33eee1618968.png)


errors out like this

```
"errorMessage": "Unsupported type \"<class 'numpy.ndarray'>\" for value \"['APS3200' 'APS3240A' 'APS3240E' 'APS3400']\"",
  "errorType": "TypeError",
```

**Comment by jaidisido** [comment]
The error is raised [here](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/dynamodb/_write.py#L192) by the boto3 dynamodb batch writer which does not recognize the data type that you are trying to write (i.e. a numpy array). It only supports native python types such as integer, string and list.

```
import awswrangler as wr
import numpy as np
import pandas as pd


df=pd.DataFrame({'id': ["1"], 'key': [np.array([1, 2, 3])]})
wr.dynamodb.put_df(df, "test_table")  # error raised
```
raises the error you mentioned. But converting the column to a list solves it:
```
df["key"] = df["key"].apply(lambda x: x.tolist())

wr.dynamodb.put_df(df, "test_table")  # no error raised
```

**Comment by NNM-UV** [comment]
thanks @jaidisido this solution will fulfill out requirement
