### ISSUE TITLE
A Nov/Dec 2022 release maybe ?

### ISSUE THREAD

**Issue by Sanix-Darker** [aws/aws-sdk-pandas#1797]
Is it possible to have a 2022 release since there is been so much work/update since April 2021 (>1 year)... just wishing... ? 🙏🏽

**Comment by jaidisido** [comment]
The latest [release](https://pypi.org/project/awswrangler/) 2.17.0 was in September 2022

**Comment by Sanix-Darker** [comment]
Oohhh 🤦🏽‍♂️  my bad !
Sorry for the issue !
