### ISSUE TITLE
opensearch.index_df stops without error but does not complete full index

### ISSUE THREAD

**Issue by chris-wynne** [aws/aws-sdk-pandas#1798]
I'm trying to write a dataframe to AWS opens search but it seems to fail on specific rows without error. 

Is there any way to debug what the issue is?

`
wr.opensearch.index_df(
    client,
    df=project_df,
    index="project_index",
    id_keys=["index_no"],
    bulk_size=1000, #number of documents
)
`

Result:

'''
Indexing:   0% (0/8540)|                                 |Elapsed Time: 0:00:00
Indexing:  11% (1000/8540)|###                           |Elapsed Time: 0:00:30
Indexing:  23% (2000/8540)|#######                       |Elapsed Time: 0:01:15
Indexing:  35% (3000/8540)|##########                    |Elapsed Time: 0:01:34
Indexing:  46% (4000/8540)|##############                |Elapsed Time: 0:01:48
{'success': 4000, 'errors': []}
'''

There should be  8k rows.

**Comment by jaidisido** [comment]
@chris-wynne could you please turn on [logging](https://github.com/aws/aws-sdk-pandas#logging) to obtain more details on what goes wrong

**Comment by chris-wynne** [comment]
@jaidisido thanks for that. It returns error 413, so the content is tool large.

**Comment by jaidisido** [comment]
Understood - you might want to tweak some of the default input [arguments](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.opensearch.index_documents.html#awswrangler.opensearch.index_documents) to the method if that helps (e.g. bulk_size, chunk_size...)

**Comment by chris-wynne** [comment]
Thanks, a combination of setting bulk_size and stripping some of the content out worked.
