### ISSUE TITLE
Lambda layer deployment to af-south-1 region

### ISSUE THREAD

**Issue by TassoAbsa** [aws/aws-sdk-pandas#1799]
We would like to make use of the latest lambda layer in the af-south-1 region, however none of the versions exist in the desired region, can this please be deployed to af-south-1 (at least the AWSSDKPandas-Python39 version but of course ideally all of them for anyone else working in the region), this would be much appreciated as we're currently busy with a production deployment that would use this region

**Comment by jaidisido** [comment]
We will look to add this for our 2.18.0 release. @kukushking, af-south-1 is not available by default, so we will have to enable the region in our account first

**Comment by TassoAbsa** [comment]
Thanks @jaidisido appreciate the feedback and await the release

**Comment by kukushking** [comment]
@jaidisido enabled

**Comment by malachi-constant** [comment]
@TassoAbsa layers have been added for the `af-south-1` region. Please note these will not be managed and available via drop down until we release the next minor version `2.18.0`. You will need to `Specify an Arn` when adding these layers for this current version. 
<img width="826" alt="Screen Shot 2022-11-29 at 8 44 51 AM" src="https://user-images.githubusercontent.com/6465221/204590352-e63167d8-b4be-4146-ada1-61a634276791.png">


```
| af-south-1     | 3.7    | x86_64| arn:aws:lambda:af-south-1:336392948345:layer:AWSSDKPandas-Python37:1              |
+----------------+--------+-------+-----------------------------------------------------------------------------------+
| af-south-1     | 3.8    | x86_64| arn:aws:lambda:af-south-1:336392948345:layer:AWSSDKPandas-Python38:1              |
+----------------+--------+-------+-----------------------------------------------------------------------------------+
| af-south-1     | 3.8    | arm64 | arn:aws:lambda:af-south-1:336392948345:layer:AWSSDKPandas-Python38-Arm64:1        |
+----------------+--------+-------+-----------------------------------------------------------------------------------+
| af-south-1     | 3.9    | x86_64| arn:aws:lambda:af-south-1:336392948345:layer:AWSSDKPandas-Python39:1              |
+----------------+--------+-------+-----------------------------------------------------------------------------------+
| af-south-1     | 3.9    | arm64 | arn:aws:lambda:af-south-1:336392948345:layer:AWSSDKPandas-Python39-Arm64:1        |
```

**Comment by TassoAbsa** [comment]
This is great news, thanks so much!
