### ISSUE TITLE
Missing --auto-termination-policy in emr.create_cluster

### ISSUE THREAD

**Issue by vikramsg** [aws/aws-sdk-pandas#1800]
**Is your idea related to a problem? Please describe.**
When using AWSWrangler to create an EMR cluster, there's no option to add a termination policy based on Idle time. This is present in the CLI by using `aws ear create-cluster --auto-termination-policy IdleTimeout=long`. This is useful since if we use an orchestration tool for  cluster creation we want to make sure that the cluster is eventually terminated.  

**Describe the solution you'd like**
It would be useful to add an argument like `wr.emr.create_cluster(idle_timeout: int)` which would do the same as `--auto-termination-policy IdleTimeout=long`. I would be happy to do a PR if this seems ok.

**Comment by malachi-constant** [comment]
Our method `wr.emr.create_cluster()` uses boto3's [`run_job_flow()`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr.html#EMR.Client.run_job_flow) so I'd recommend we add `AutoTerminationPolicy` as `auto_termination_policy: Dict[str, Any]`.

Example:

```
wr.emr.create_cluster(
    auto_termination_policy={
        'IdleTimeout': 123
    }
)
```

If you are open to implementation we would welcome your PR.

**Comment by vikramsg** [comment]
Thanks. I will submit a PR but shouldn't the type be `auto_termination_policy: Dict[str, int]`?

**Comment by malachi-constant** [comment]
@vikramsg The `Any` would take into account any **future** attributes added to the `AutoTerminationPolicy` that may not be integer values and allow seamless addition without updates to the method. But, yes at this time that's the only supported parameter so `Dict[str, int]`.
