### ISSUE TITLE
Add support for Python 3.11

### ISSUE THREAD

**Issue by Thijss** [aws/aws-sdk-pandas#1802]
Currently when using pip or poetry to install `awswrangler`, I am getting:
> awswrangler (2.17.0) requires Python >=3.7.1,<3.11

**Describe the solution you'd like**
I would like teo able to install `awswrangler` on Python 3.11

**Comment by jaidisido** [comment]
Duplicate of https://github.com/aws/aws-sdk-pandas/issues/1714
