### ISSUE TITLE
Delete Row Redshift without Primary Key

### ISSUE THREAD

**Issue by nfbalbontin** [aws/aws-sdk-pandas#1814]
Hi!
**Problem:** I'm trying to upsert rows to a redshift table that hasn't have primary keys. I've been trying with the `to_sql` function, like the following example: 
```{python}
_db_redshift.to_sql(df=df, con=con, table='table_name', schema='schema_name', mode='upsert')
```
But i get the following error: 
```
File "D:\WinApps\Miniconda\lib\site-packages\awswrangler\redshift.py", line 67, in _get_primary_keys
    result: str = result[0][0]
IndexError: tuple index out of range
```
And is because the execution in line awswrangler/redshift.py/64:
 ```cursor.execute(f"SELECT indexdef FROM pg_indexes WHERE schemaname = '{schema}' AND tablename = '{table}'")```
 returns `()` 

Because of this, I tryed first eliminating the data and then appending it. But I found out that you can't eliminate specific data. 
I tryied doing: 
```{python}
_db_redshift.read_sql_query("DELETE FROM <my_schema>.<my_table> WHERE foo = 1")
```
And got the following error: 
```
File "D:\WinApps\Miniconda\lib\site-packages\awswrangler\_databases.py", line 176, in _get_cols_names
    cols_names = [col[0].decode("utf-8") if isinstance(col[0], bytes) else col[0] for col in cursor_description]
TypeError: 'NoneType' object is not iterable
(base)
```
I checked all the 'overwrite' methods in `to_sql`, but non of them uses the given df to eliminate the specific rows, they just operate over the whole table. 

**Question**: So,  my question is, it is possible to upsert data into a table without primary keys, and if not, is there a way I can eliminate specific rows via query or other methods?

Thank you very much! 
**PD:** First of all, thank you really much for the library, it has been really usefull for a lot of projects.

**Comment by jaidisido** [comment]
Hi @nfbalbontin, from the best practices Redshift [guide](https://docs.aws.amazon.com/redshift/latest/dg/t_updating-inserting-using-staging-tables-.html), it's not recommended to perform an upsert without primary keys. This is because there is a significant risk of creating duplicates.

As for running queries on specific rows, you can use the redshift connector directly to perform that:
```
con =  wr.redshift.connect("aws-sdk-pandas-redshift")
con.execute("DELETE FROM <my_schema>.<my_table> WHERE foo = 1")
con.commit() # to commit the transaction
```

**Comment by nfbalbontin** [comment]
Thanks!
