### ISSUE TITLE
Missing script CLI args for emr.submit_spark_step

### ISSUE THREAD

**Issue by vikramsg** [aws/aws-sdk-pandas#1820]
**Is your idea related to a problem? Please describe.**
After creating an EMR cluster, we can submit a python script using `emr.submit_spark_step(path="s3://path/to/script.py")`. This is then translated to `spark-submit --deploy-mode {deploy_mode} {path}` for submission. 

However, when submitting the script we often want to add CLI args to the script, for eg. `spark-submit s3://path/to/script.py --args hello-world`. We can currently do this using a hacky compromise via `emr.submit_spark_step(path="s3://path/to/script.py --args hello-world")`. 

**Describe the solution you'd like**
Instead of doing it in the above hacky way, we could use something like `emr.submit_spark_step(path="s3://path/to/script.py", args=["--args", "hello-world"])` which would be a much nicer way of using this function. Does this sound good? I can do a PR for this.

**Comment by kukushking** [comment]
Good idea @vikramsg, would make the experience a bit nicer
