### ISSUE TITLE
Unexpected exception `TypeError: 'NoneType' object is not subscriptable` reading parquet files with timezone aware timestamps

### ISSUE THREAD

**Issue by enricomarchesin** [aws/aws-sdk-pandas#1823]
### Describe the bug

I'm getting the following exception while reading a parquet file from S3:

```py
    timezone: datetime.tzinfo = pa.lib.string_to_tzinfo(c["metadata"]["timezone"])
TypeError: 'NoneType' object is not subscriptable
```

### How to Reproduce

```
from datetime import datetime, timezone
import awswrangler as wr

df = pd.DataFrame(
    [
        {"ts": datetime(2022, 11, 30, 0, 0, tzinfo=timezone.utc), "value":0},
        {"ts": datetime(2022, 11, 30, 1, 0, tzinfo=None), "value":1},
    ]
)
wr.s3.to_parquet(df=df, path="s3://tests-bucket/wr_bug.parquet")
df = wr.s3.read_parquet(path="s3://tests-bucket/wr_bug.parquet")
```

It will throw the error above.

### Expected behavior

I would have expected the file to be read with no issues.

### Your project

n/a

### Screenshots

![image](https://user-images.githubusercontent.com/7022619/204853326-25a25c2f-bae7-4a37-ba00-22290210e0a8.png)

### OS

Mac

### Python version

tested on 3.9 and 3.10

### AWS SDK for pandas version

2.17.0

### Additional context

In the 2.x branch, this can be easily fixed with a more defensive code around the logic that converts the tzaware timestamps to the inferred timezone.

For v2.17.0, it's here:
* https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/s3/_read_parquet.py#L279-L280

```py
        if col_name in df.columns and c["pandas_type"] == "datetimetz":
            timezone: datetime.tzinfo = pa.lib.string_to_tzinfo(c["metadata"]["timezone"])
```

A simple fix can be something like:

```py
        is_col_tz_aware = col_name in df.columns and c["pandas_type"] == "datetimetz"
        is_col_tz_set = c.get("metadata") and c["metadata"].get("timezone")
        if is_col_tz_aware and is_col_tz_set:
            timezone: datetime.tzinfo = pa.lib.string_to_tzinfo(c["metadata"]["timezone"])
```

I guess that it can happen, like in my example, when it's not possible to actually identify a timezone to associate to the column.

**Comment by kukushking** [comment]
Thanks for opening this @enricomarchesin - the fix is in merged in main now.

**Comment by enricomarchesin** [comment]
Thanks a lot for the quick turnaround @kukushking !
