### ISSUE TITLE
AWS Wrangler not maintaining the Map structure

### ISSUE THREAD

**Issue by NNM-UV** [aws/aws-sdk-pandas#1825]
my pandas dataframe have a map column like below - 

![image](https://user-images.githubusercontent.com/118927963/204899156-fe409687-f9ca-4523-a9de-e99a93302ad8.png)
```
b = {'01AB': {"ABC":5,"XYZ":4,"LMN":1},
     '02AB_QTY': {"Other":20,"not_Other":150}}
```
While writing into dynamoDB, Wrangler is converting it from Map to List type, saving the record as below - 

![image](https://user-images.githubusercontent.com/118927963/204900046-732f7a56-0c0a-44ed-b101-af523a07b9b4.png)

```
a = {'01AB': [["ABC",5],["XYZ",4],["LMN",1]],
     '02AB_QTY': [["Other",20],["not_Other",150]]}
```
instead of saving this as Dict Column, its saving the data as list of lists.
How can we maintain the orientation ?

**Comment by LeonLuttenberger** [comment]
Hello,

I am using the example you provided but I'm unable to recreate the error. I have used the following commands:

```python
b = {'01AB': {"ABC":5,"XYZ":4,"LMN":1}, '02AB_QTY': {"Other":20,"not_Other":150}}

frame = pd.DataFrame.from_records([b])
frame["id"] = "0"  # adding this so that I have a partition key of type string

wr.dynamodb.put_df(frame, table_name="test_table")
```

When I ran these commands, the data frame was stored properly. Can you please help correct my example so that I can recreate your error? Also, please provide which version of `awswrangler` you are using.

Best regards,
Leon

**Comment by NNM-UV** [comment]
so here is more information, I am using AWSSDKPandas-Python39  layer version 1 for AWS-Lambda
1) My parquet file have the data in object form
![image](https://user-images.githubusercontent.com/118927963/204934632-59dd6dea-c7e6-4456-9b3a-160677da2d32.png)

![image](https://user-images.githubusercontent.com/118927963/204934841-69bc1e11-fd94-4a03-a0b2-671ceeeecc6f.png)

2) wr.s3.read_parquet is reading in format below- 
![image](https://user-images.githubusercontent.com/118927963/204934991-509bcf2d-617b-499f-99ca-763743b5617f.png)

3) we.dynamodb.put_df is inserting data as below - 
![image](https://user-images.githubusercontent.com/118927963/204935141-d02cb015-a62d-48fb-b375-4f1a36f3cf96.png)


hope this will help reproduce the issue

**Comment by NNM-UV** [comment]
I was able to resolve this issue with the dict(), as below - 
```
import pandas as pd

# {'01AB': {"ABC":5,"XYZ":4,"LMN":1}, '02AB_QTY': {"Other":20,"not_Other":150}}

df = pd.DataFrame.from_records([{'01AB': [("ABC", 5),("XYZ", 4),("LMN", 1)], '02AB_QTY': [("Other", 20),("not_Other", 150)]}])

df_a = pd.DataFrame.from_records({'01AB': {"ABC":5,"XYZ":4,"LMN":1}, '02AB_QTY': {"Other":20,"not_Other":150}})
col_list = ["01AB", "02AB_QTY",]

print(df)

for col in col_list:
    df[col] = df[col].apply(lambda x: {} if x is None else dict(x))

print(df)
```

this issue can be closed now
