### ISSUE TITLE
Can wr.redshift.read_sql_query return timestamp with timezone?

### ISSUE THREAD

**Issue by jackexu** [aws/aws-sdk-pandas#1829]
If I extract a timestamp from Redshift, the result won't have any timezone info
```
df = wr.redshift.read_sql_query(
    sql="SELECT max(created_at) as max_ts FROM public.a_table",
    con=con,
    timestamp_as_object=True
)
max_ts=df['max_ts'][0]
```
Then I got 
```
max_ts
>> datetime.datetime(2022, 12, 1, 17, 7, 34)
print(max_ts.tzinfo)
>> None
```
Is there anyway to also extract timezone? like UTC in above case

**Comment by jaidisido** [comment]
My hunch is that the column you are reading from does not hold the timezone information. Is it stored as a `TIMETZ` type in Redshift and are you able to obtain the timezone info from reading the column in the console for instance.

Here is a simple example where I am able to obtain the tzinfo back:
```
import awswrangler as wr
import pandas as pd


con = wr.redshift.connect(connection="aws-sdk-pandas-redshift")
table = "timezone"

df = pd.DataFrame({
    "id": [1, 2],
    "timestamp": [
        datetime.datetime(2020, 10, 26, 23, 3, 54, 756497, tzinfo=datetime.timezone.utc),
        datetime.datetime(2020, 10, 26, 23, 3, 55, 756496, tzinfo=datetime.timezone.utc),
    ],
})

wr.redshift.to_sql(
    df=df,
    con=con,
    table=table,
    schema="public",
)

df2 = wr.redshift.read_sql_query(sql=f"SELECT * FROM public.{table}", con=con, timestamp_as_object=True)
ts = df["timestamp"][0]

print(ts)
print(ts.tzinfo)
```
which returns:
```
2020-10-26 23:03:54.756497+00:00
UTC
```

**Comment by jackexu** [comment]
@jaidisido your hunch is correct: the column type is `timestamp` not `timestamptz`.

however, the timestamp has default UTC timezone per [AWS document](https://docs.aws.amazon.com/redshift/latest/dg/r_Datetime_types.html) 
```
By default, TIMESTAMP values are UTC in both user tables and Amazon Redshift system tables.
```

So I am wondering if possible to read this info and return back with UTC timezone info?

P.S. it's strange that need to use `convert_timezone('US/Eastern', created_at_with_tz::timestamp)` if `created_at_with_tz` is `timestamptz`
