### ISSUE TITLE
module 'awswrangler.athena' has no attribute 'create_ctas_table'

### ISSUE THREAD

**Issue by trad957** [aws/aws-sdk-pandas#1836]
when i try 
`wr.athena.create_ctas_table("""SELECT * FROM "sku"."dws_vip_users" limit 10;""", datsbase='sku', ctas_table='dws_vip_user_test')`
get
`AttributeError: module 'awswrangler.athena' has no attribute 'create_ctas_table'
`
what happend?

**Comment by jaidisido** [comment]
The method `create_ctas_table` was only introduced from version 2.15.0 of the library. Most likely that you have an older version installed
