### ISSUE TITLE
`NoCredentialsError: Unable to locate credentials` with `s3.describe_objects` and a valid `boto3_session` argument when processing multiple s3 objects

### ISSUE THREAD

**Issue by ataghavey** [aws/aws-sdk-pandas#1843]
### Describe the bug

I am experiencing a similar issue as reported [here](https://github.com/aws/aws-sdk-pandas/issues/1491) with the awswrangler.s3.describe_objects() method and a valid boto3 session.

Method works just file when a single string with path to a single s3 object is passed in, however, when a path that's upstream to multiple s3 objects, or a list of paths (len > 1) is passed in for the path arg, this error is retrieved:

NoCredentialsError: Unable to locate credentials

### How to Reproduce

```
source_path_fmi = "s3://<bucket>/<path/upstream/of/multiple/s3/objects>"
awswrangler.s3.describe_objects(path=source_path_fmi, boto3_session=boto3_session)
```

### Expected behavior

---------------------------------------------------------------------------
NoCredentialsError                        Traceback (most recent call last)
Cell In [33], line 2
      1 source_path_fmi = "s3://jrd-orbit-publish-prod/oncology/staging/FMI/fmi_psst"
----> 2 awswrangler.s3.describe_objects(path=source_path_fmi, boto3_session=boto3_session)

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\awswrangler\s3\_describe.py:156, in describe_objects(path, version_id, use_threads, last_modified_begin, last_modified_end, s3_additional_kwargs, boto3_session)
    154     versions = [version_id.get(p) if isinstance(version_id, dict) else version_id for p in paths]
    155     with concurrent.futures.ThreadPoolExecutor(max_workers=cpus) as executor:
--> 156         resp_list = list(
    157             executor.map(
    158                 _describe_object_concurrent,
    159                 paths,
    160                 versions,
    161                 itertools.repeat(_utils.boto3_to_primitives(boto3_session=boto3_session)),
    162                 itertools.repeat(s3_additional_kwargs),
    163             )
    164         )
    165 desc_dict: Dict[str, Dict[str, Any]] = dict(resp_list)
    166 return desc_dict

File ~\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py:609, in Executor.map.<locals>.result_iterator()
    606 while fs:
    607     # Careful not to keep a reference to the popped future
    608     if timeout is None:
--> 609         yield fs.pop().result()
    610     else:
    611         yield fs.pop().result(end_time - time.monotonic())

File ~\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py:446, in Future.result(self, timeout)
    444     raise CancelledError()
    445 elif self._state == FINISHED:
--> 446     return self.__get_result()
    447 else:
    448     raise TimeoutError()

File ~\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py:391, in Future.__get_result(self)
    389 if self._exception:
    390     try:
--> 391         raise self._exception
    392     finally:
    393         # Break a reference cycle with the exception in self._exception
    394         self = None

File ~\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py:58, in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\awswrangler\s3\_describe.py:50, in _describe_object_concurrent(path, boto3_primitives, s3_additional_kwargs, version_id)
     43 def _describe_object_concurrent(
     44     path: str,
     45     boto3_primitives: _utils.Boto3PrimitivesType,
     46     s3_additional_kwargs: Optional[Dict[str, Any]],
     47     version_id: Optional[str] = None,
     48 ) -> Tuple[str, Dict[str, Any]]:
     49     boto3_session = _utils.boto3_from_primitives(primitives=boto3_primitives)
---> 50     return _describe_object(
     51         path=path, boto3_session=boto3_session, s3_additional_kwargs=s3_additional_kwargs, version_id=version_id
     52     )

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\awswrangler\s3\_describe.py:37, in _describe_object(path, boto3_session, s3_additional_kwargs, version_id)
     35 if version_id:
     36     extra_kwargs["VersionId"] = version_id
---> 37 desc = _utils.try_it(
     38     f=client_s3.head_object, ex=client_s3.exceptions.NoSuchKey, Bucket=bucket, Key=key, **extra_kwargs
     39 )
     40 return path, desc

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\awswrangler\_utils.py:348, in try_it(f, ex, ex_code, base, max_num_tries, **kwargs)
    346 for i in range(max_num_tries):
    347     try:
--> 348         return f(**kwargs)
    349     except ex as exception:
    350         if ex_code is not None and hasattr(exception, "response"):

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\botocore\client.py:508, in ClientCreator._create_api_method.<locals>._api_call(self, *args, **kwargs)
    504     raise TypeError(
    505         f"{py_operation_name}() only accepts keyword arguments."
    506     )
    507 # The "self" in this scope is referring to the BaseClient.
--> 508 return self._make_api_call(operation_name, kwargs)

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\botocore\client.py:898, in BaseClient._make_api_call(self, operation_name, api_params)
    896 else:
    897     apply_request_checksum(request_dict)
--> 898     http, parsed_response = self._make_request(
    899         operation_model, request_dict, request_context
    900     )
    902 self.meta.events.emit(
    903     'after-call.{service_id}.{operation_name}'.format(
    904         service_id=service_id, operation_name=operation_name
   (...)
    909     context=request_context,
    910 )
    912 if http.status_code >= 300:

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\botocore\client.py:921, in BaseClient._make_request(self, operation_model, request_dict, request_context)
    919 def _make_request(self, operation_model, request_dict, request_context):
    920     try:
--> 921         return self._endpoint.make_request(operation_model, request_dict)
    922     except Exception as e:
    923         self.meta.events.emit(
    924             'after-call-error.{service_id}.{operation_name}'.format(
    925                 service_id=self._service_model.service_id.hyphenize(),
   (...)
    929             context=request_context,
    930         )

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\botocore\endpoint.py:119, in Endpoint.make_request(self, operation_model, request_dict)
    113 def make_request(self, operation_model, request_dict):
    114     logger.debug(
    115         "Making request for %s with params: %s",
    116         operation_model,
    117         request_dict,
    118     )
--> 119     return self._send_request(request_dict, operation_model)

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\botocore\endpoint.py:198, in Endpoint._send_request(self, request_dict, operation_model)
    196 context = request_dict['context']
    197 self._update_retries_context(context, attempts)
--> 198 request = self.create_request(request_dict, operation_model)
    199 success_response, exception = self._get_response(
    200     request, operation_model, context
    201 )
    202 while self._needs_retry(
    203     attempts,
    204     operation_model,
   (...)
    207     exception,
    208 ):

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\botocore\endpoint.py:134, in Endpoint.create_request(self, params, operation_model)
    130     service_id = operation_model.service_model.service_id.hyphenize()
    131     event_name = 'request-created.{service_id}.{op_name}'.format(
    132         service_id=service_id, op_name=operation_model.name
    133     )
--> 134     self._event_emitter.emit(
    135         event_name,
    136         request=request,
    137         operation_name=operation_model.name,
    138     )
    139 prepared_request = self.prepare_request(request)
    140 return prepared_request

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\botocore\hooks.py:412, in EventAliaser.emit(self, event_name, **kwargs)
    410 def emit(self, event_name, **kwargs):
    411     aliased_event_name = self._alias_event_name(event_name)
--> 412     return self._emitter.emit(aliased_event_name, **kwargs)

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\botocore\hooks.py:256, in HierarchicalEmitter.emit(self, event_name, **kwargs)
    245 def emit(self, event_name, **kwargs):
    246     """
    247     Emit an event by name with arguments passed as keyword args.
    248 
   (...)
    254              handlers.
    255     """
--> 256     return self._emit(event_name, kwargs)

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\botocore\hooks.py:239, in HierarchicalEmitter._emit(self, event_name, kwargs, stop_on_response)
    237 for handler in handlers_to_call:
    238     logger.debug('Event %s: calling handler %s', event_name, handler)
--> 239     response = handler(**kwargs)
    240     responses.append((handler, response))
    241     if stop_on_response and response is not None:

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\botocore\signers.py:103, in RequestSigner.handler(self, operation_name, request, **kwargs)
     98 def handler(self, operation_name=None, request=None, **kwargs):
     99     # This is typically hooked up to the "request-created" event
    100     # from a client's event emitter.  When a new request is created
    101     # this method is invoked to sign the request.
    102     # Don't call this method directly.
--> 103     return self.sign(operation_name, request)

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\botocore\signers.py:187, in RequestSigner.sign(self, operation_name, request, region_name, signing_type, expires_in, signing_name)
    184     else:
    185         raise e
--> 187 auth.add_auth(request)

File d:\users\ataghave\onedrive - jnj\documents\code\customers-janssen-orbit\.venv-customers-janssen-orbit\lib\site-packages\botocore\auth.py:407, in SigV4Auth.add_auth(self, request)
    405 def add_auth(self, request):
    406     if self.credentials is None:
--> 407         raise NoCredentialsError()
    408     datetime_now = datetime.datetime.utcnow()
    409     request.context['timestamp'] = datetime_now.strftime(SIGV4_TIMESTAMP)

NoCredentialsError: Unable to locate credentials

### OS

Win

### Python version

 3.9.12

### AWS SDK for pandas version

2.18.0

**Comment by malachi-constant** [comment]
Hi @ataghavey. Can you provide me with the exact calls you are making? Are they failing consistently or intermittently?

I am unable to replicate with the following 

```
import boto3
import awswrangler as wr

session = boto3.Session()
bucket = "MYBUCKETNAME"

# Single File
wr.s3.describe_objects(path=f"s3://{bucket}/parquet/file1.parquet", boto3_session=session)

# Multiple Files (Implicit)
wr.s3.describe_objects(path=f"s3://{bucket}/parquet/", boto3_session=session)

# Multiple Files (Explicit)
wr.s3.describe_objects(path=[f"s3://{bucket}/parquet/file1.parquet", f"s3://{bucket}/parquet/file2.parquet"], boto3_session=session)
```

It would be best to see a script with the working and failing calls running serially so we can make sure there are no inconsistencies in usage.

**Comment by ataghavey** [comment]
Please see the screen capture below - and this is consistently taking place for all single paths leading to multiple s3 objects, or a list of more than one s3 paths: 
![image](https://user-images.githubusercontent.com/77649523/207139096-5c8a7183-da4b-44d0-a043-0aa1227fefd2.png)

**Comment by jaidisido** [comment]
My guess here is that the error is thrown [here](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/_utils.py#L43). `boto3.get_credentials` is trying to obtain the local credentials from the notebook but fails for some reason and throws the NoCredentials error. You should see a similar error if you try: `boto3_session.get_credentials()`

**Comment by ataghavey** [comment]
@jaidisido - the ^^^ mentioned method works fine with my boto3 session - please see below:
![image](https://user-images.githubusercontent.com/77649523/208097565-1da7e494-c1c7-45b9-bf59-13d9b9659653.png)
Even the `describe_objects()` method works fine with the my boto3 session when a single s3 object is at the end of the input path. Others had also reported the same issue when trying the describe method on multiple objects - please see this ticket: 
https://github.com/aws/aws-sdk-pandas/issues/1843#:~:text=issue%20as%20reported-,here,-with%20the%20awswrangler

**Comment by jaidisido** [comment]
The difference between a single and multiple paths is that it's run multithreaded and the boto3 session is broken down into primitives so they can be passed in the thread.

After running the above method, are you actually able to access the credentials from the returned dictionary?

**Comment by ataghavey** [comment]
Hi @jaidisido - yes - I am able to extract creds from this function call - please see partial screen capture below:
![image](https://user-images.githubusercontent.com/77649523/208525383-d9c775e1-fb32-4e9a-a792-02fdba608222.png)

**Comment by bmeares** [comment]
Was able to reproduce this bug with version 2.17.0 of `awswrangler` on Python 3.7. Setting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` is a temporary workaround to let `awswrangler` build its own session, but I'm still running into an issue when using wildcards in a list with `wr.s3.describe_objects()`, e.g.:

```python
>>> import awswrangler as wr
>>> wr.s3.describe_objects(['s3://bucket/prefix/*pattern*'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/venvs/s3/lib/python3.7/site-packages/awswrangler/s3/_describe.py", line 139, in describe_objects
    s3_additional_kwargs=s3_additional_kwargs,
  File "/home/username/venvs/s3/lib/python3.7/site-packages/awswrangler/s3/_describe.py", line 38, in _describe_object
    f=client_s3.head_object, ex=client_s3.exceptions.NoSuchKey, Bucket=bucket, Key=key, **extra_kwargs
  File "/home/username/venvs/s3/lib/python3.7/site-packages/awswrangler/_utils.py", line 345, in try_it
    return f(**kwargs)
  File "/home/username/venvs/s3/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/username/venvs/s3/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

Will try with 2.19.0 and see if the issue persists.
