### ISSUE TITLE
Extra blank lines added when copy-pasting code snippets

### ISSUE THREAD

**Issue by mdavis-xyz** [aws/aws-sdk-pandas#1852]
### Describe the bug

When copying code snippets, extra blank lines get added. Deleting them manually is a bit annoying.

### How to Reproduce

1. Go to a doc page which has a code snippet, e.g. [this page](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.timestream.write.html)
2. Highlight the code snippet, and copy
3. Open a text editor
4. paste it in

### Expected behavior

The text in the text editor matches what was in the web page

# Actual behavior

The text in the text editor has blank lines inserted between each real line.

### OS

Mac

### Python version

N/A

### AWS SDK for pandas version

N/A

**Comment by jaidisido** [comment]
I am on Mac as well and did not face this issue. I have tried on several code/text editors (Sublime, VSCode and Word), and in each case the code is pasted as is without extra blank lines

**Comment by kukushking** [comment]
Same, but perhaps a copy button will make the experience a bit more convenient - added in the PR above.
