### ISSUE TITLE
Unable to write timestamps to Timestream measure columns

### ISSUE THREAD

**Issue by mdavis-xyz** [aws/aws-sdk-pandas#1853]
### Describe the bug

The [Timestream documentation](https://docs.aws.amazon.com/timestream/latest/developerguide/writes.html) says:

> TIMESTAMP datatype for measures – You can use the TIMESTAMP data type to store data from the past, present, or future. A multi-measure record can have multiple attributes of TIMESTAMP data type, in addition to the time field in a record. TIMESTAMP attributes, in a multi-measure record, can have timestamps in the future or the past and behave like the time field except that Timestream does not index on the values of type TIMESTAMP in a multi-measure record.
Note

> The TIMESTAMP datatype is supported only for multi-measure records.

But when I try to write timestamps with awswrangler, when passing multiple measure columns, I get errors saying that type is not supported.

### How to Reproduce

```
import datetime as dt
from datetime import datetime
import awswrangler as wr
import pandas as pd
import boto3
db_name = 'mwe'
table_name = 'test_tz_a'
tags = {
    'person': 'matt',
    'delete after': 'Dec 2022'
}
w_client = boto3.client('timestream-write')
# create database
try:
    wr.timestream.create_database(
        database=db_name,
        tags=tags
    )
except w_client.exceptions.ConflictException:
    # database already exists
    pass
try:
    wr.timestream.create_table(
        database=db_name,
        table=table_name,
        memory_retention_hours=5, 
        magnetic_retention_days=1, 
        tags=tags)
except w_client.exceptions.ConflictException:
    # database already exists
    pass
# same as the awswrangler documentation
df = pd.DataFrame(
    {
        "time": [datetime.now()]*3,
        "dim0": ["foo", "boo", "bar"],
        "dim1": [1, 2, 3],
        "measure": [1.0, 1.1, 1.2],
    }
)
rejected_records = wr.timestream.write(
    df=df,
    database=db_name,
    table=table_name,
    time_col="time",
    measure_col="measure",
    dimensions_cols=["dim0", "dim1"],
)
assert len(rejected_records) == 0
# timezone aware index time
df = pd.DataFrame(
    {
        "time": [datetime.now(dt.timezone.utc)]*3,
        "dim0": ["foo", "boo", "bar"],
        "dim1": [1, 2, 3],
        "measure": [1.0, 1.1, 1.2],
    }
)
rejected_records = wr.timestream.write(
    df=df,
    database=db_name,
    table=table_name,
    time_col="time",
    measure_col="measure",
    dimensions_cols=["dim0", "dim1"],
)
assert len(rejected_records) == 0
# Same as awswrangler docs,
# but adding timezone unaware timestamp to measure column
df = pd.DataFrame(
    {
        "time": [datetime.now()]*3,
        "dim0": ["foo", "boo", "bar"],
        "dim1": [1, 2, 3],
        "measure_f": [1.1, 1.2, 1.3],
        "measure_t": [datetime.now()]*3,
    }
)
rejected_records = wr.timestream.write(
    df=df,
    database=db_name,
    table=table_name,
    time_col="time",
    measure_col=["measure_f", "measure_t"],
    dimensions_cols=["dim0", "dim1"],
)
assert len(rejected_records) == 0
# Same as awswrangler docs,
# but adding timezone aware timestamp to measure column
df = pd.DataFrame(
    {
        "time": [datetime.now()]*3,
        "dim0": ["foo", "boo", "bar"],
        "dim1": [1, 2, 3],
        "measure_f": [1.1, 1.2, 1.3],
        "measure_t": [datetime.now(dt.timezone.utc)]*3,
    }
)
rejected_records = wr.timestream.write(
    df=df,
    database=db_name,
    table=table_name,
    time_col="time",
    measure_col=["measure_f", "measure_t"],
    dimensions_cols=["dim0", "dim1"],
)
assert len(rejected_records) == 0
```

### Expected behavior

The script should pass.

### Actual behavior

I get errors with the last 2 writes.

> UnsupportedType: Unsupported Amazon Timestream measure type: timestamp[ns]

and

> UnsupportedType: Unsupported Amazon Timestream measure type: timestamp[ns, tz=UTC]

### OS

Amazon Linux 2

### Python version

3.10.1

### AWS SDK for pandas version

2.15.1

### Additional context

I actually don't understand why [the example in the docs for writing to timestream](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.timestream.write.html#awswrangler.timestream.write) works. I would expect it to fail because awswrangler is being asked to convert a timezone unaware datetime (`datetime.now()`) to unix epoch time. But that's a separate issue. The behavior I mention in this ticket is the same regardless of whether the measure is timezone aware or unaware.

**Comment by mdavis-xyz** [comment]
I haven't looked at the code yet. I assumed that the serialisation (e.g. datetime to int or string) happens based on the original type.

e.g. to save a float you must convert it to a string. But the code doesn't then infer that the column is of type string. Isn't this the same thing?

**Comment by jaidisido** [comment]
Data types are inferred from the pandas data frame type via pyarrow. Above PR should introduce a fix.
