### ISSUE TITLE
S3 _validate_schemas_from_files always uses threading, causing slow tests

### ISSUE THREAD

**Issue by robert-schmidtke** [aws/aws-sdk-pandas#1868]
### Describe the bug

When reading Parquet files from S3, `_validate_schemas_from_files` always uses `use_threads=True`. This works fine in practice, but slows down my tests dramatically. I found 40% of the time spent waiting on these locks, see the attached excerpt from a test profile. When setting `use_threads=False` I discovered the issue persisted because it would always use `True`.

### How to Reproduce

Pass `validate_schema=True` to `wr.s3.read_parquet` and see that `use_threads=False` has no effect.

### Expected behavior

`use_threads` be respected throughout the call chain.

### Screenshots

![image](https://user-images.githubusercontent.com/1101741/207823415-0735522e-8b1b-4e16-8105-9b72b5a6674a.png)

### OS

Ubuntu 20.04.5 LTS (Focal Fossa)

### Python version

3.9.13

### AWS SDK for pandas version

2.16.0

### Additional context

I'll open a PR in a second.

**Comment by jaidisido** [comment]
Thanks for the issue @robert-schmidtke, your PR was merged. Out of curiosity, may I ask which tool you used to create the diagram above?

**Comment by robert-schmidtke** [comment]
As always super quick, many thanks! I used the `pytest-profiling` plugin for `pytest`: https://pypi.org/project/pytest-profiling/ and ran my tests with `--profile-svg`.
