### ISSUE TITLE
awswrangler.s3.upload not working with io.BytesIO

### ISSUE THREAD

**Issue by lasdem** [aws/aws-sdk-pandas#1870]
### Describe the bug

wr.s3.upload does not upload to S3 if using a BytesIO buffer.
After the call is executed the object is not found on S3. 
According to the documentation it should work with a file-like object. 

### How to Reproduce

```python
from io import BytesIO
from PIL import Image

src_file = "s3://my-bucket/my-image.jpeg"
tmp_file = "s3://my-bucket/testfile.jpeg"
local_file = "testfile.jpeg"

with BytesIO() as buffer:
    # dowload file into the buffer
    wr.s3.download(path=src_file, local_file=buffer)
    # verify image loaded correctly
    display(Image.open(buffer))
    # upload from buffer to different s3 location
    wr.s3.upload(local_file=buffer, path=tmp_file)
    
# download file to local storage
wr.s3.download(path=tmp_file, local_file=local_file)
# display local file to verify
display(Image.open(local_file))
# delete local file
os.unlink(local_file)
```

This code will fail on the second wr.s3.download, because the image was not actually uploaded during wr.s3.upload. 

### Expected behavior

I need to transfer a list of images from one bucket to another bucket in a different account using different boto3 sessions. 
I tried to download the images into a memory buffer and upload from there to the other accounts bucket.

The expected behavior is that after calling `wr.s3.upload(local_file=buffer, path=tmp_file)` the file should exist on s3 or an error should be given if it failed. 

### OS

Linux

### Python version

3.8.13

### AWS SDK for pandas version

2.18.0

**Comment by eldritchideen** [comment]
I believe what you are seeing here, is the result of the byte stream being read by the `Image.open` method. Hence the call to `wr.s3.upload` when it tries to read the byte stream, the offset is already at the end of the stream. Before calling `wr.s3.upload` you can reset the stream by calling `buffer.seek(0)`. The following modification to you code works:


```python
 with BytesIO() as buffer:
    # dowload file into the buffer
    wr.s3.download(path=src_file, local_file=buffer)
    # verify image loaded correctly
    display(Image.open(buffer))
    # upload from buffer to different s3 location
    buffer.seek(0)  # Reset buffer offset
    wr.s3.upload(local_file=buffer, path=tmp_file)
```

**Comment by lasdem** [comment]
Thank you!
It can't be the Image.open, since I can reproduce the error by just doing:
```python
with BytesIO() as buffer:
    wr.s3.download(path=src_file, local_file=buffer)
    wr.s3.upload(local_file=buffer, path=tmp_file)
```
But the seek in between definitely makes it work, thank you!
