### ISSUE TITLE
When `wr.opensearch.search` query has no-matching-result , it throws a [KeyError]

### ISSUE THREAD

**Issue by dydc** [aws/aws-sdk-pandas#1876]
**Is your idea related to a problem? Please describe.**
- When `wr.opensearch.search` query has no-matching-result , it throws a [KeyError](https://github.com/aws/aws-sdk-pandas/blob/10fdfb323629d1172d10dbc7cf026cbe2c8ce4cf/awswrangler/opensearch/_read.py#L120); 

**Describe the solution you'd like**
- On  `wr.opensearch.search` query has no-matching-result , Return an empty list or pd.Dataframe().

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by kukushking** [comment]
Thanks for opening this @dydc, fixed in the linked PR
