### ISSUE TITLE
Preserve NoneType types in UUID fields

### ISSUE THREAD

**Issue by joshmatthews-ch** [aws/aws-sdk-pandas#1880]
### Discussed in https://github.com/aws/aws-sdk-pandas/discussions/1873

<div type='discussions-op-text'>

<sup>Originally posted by **joshmatthews-ch** December 15, 2022</sup>
I am using this library to read data from Postgres into a Pandas dataframe and have noticed that when the datatype in the source table is uuid, null values in those columns appear in the resulting dataframe as the `"None"`.

To me this seems unexpected behaviour as it is caused by [the Python decision to have `str(None) == "None"`](https://github.com/aws/aws-sdk-pandas/blob/10fdfb323629d1172d10dbc7cf026cbe2c8ce4cf/awswrangler/_data_types.py#L564).

Should this be changed so that `NoneType` types are not cast to strings?</div>

### Proposed change
Change the above linked line from
```
        array: pa.Array = pa.array(obj=[str(x) for x in values], type=dtype, safe=True)
```
to
```
        array: pa.Array = pa.array(obj=[str(x) if x is not None else None for x in values], type=dtype, safe=True)
```

### Testing
I ran a Docker container using the postgres 10-alpine image. I created a table and populated it
```
create table example (col1 uuid, col2 text, col3 bigint);
insert into example (col1, col2, col3) values (gen_random_uuid(), 'lorem ipsum', 42);
insert into example (col1, col2, col3) values (null, null, null);
```

I ran the following Python snippet without making changes
```
import pg8000
conn = pg8000.connect(...)
from awswrangler import postgresql
df = postgresql.read_sql_table("example", conn)
df
```
which returned
```
                                   col1         col2  col3
0  ae6fb54b-729e-485f-8616-9f55afc23f26  lorem ipsum    42
1                                  None         <NA>  <NA>
```
where `<NA>` is an instance of `<class 'pandas._libs.missing.NAType'>`.

I then ran the same snipped but applying the change and this returned
```
                                   col1         col2  col3
0  ae6fb54b-729e-485f-8616-9f55afc23f26  lorem ipsum    42
1                                  <NA>         <NA>  <NA>
```
as desired.

### Performance
I ran the following on my laptop to demonstrate performance of the new list comprehension isn't much worse
```
>>> import uuid
>>> import time
>>> 
>>> n = int(10e6)
>>> 
>>> uuids = [uuid.uuid4()] * n
>>> start = time.time()
>>> a = [str(x) for x in uuids]
>>> end = time.time()
>>> print(end - start)
12.15282917022705
>>> 
>>> 
>>> start = time.time()
>>> a = [str(x) if x is not None else None for x in uuids]
>>> end = time.time()
>>> print(end - start)
13.189699649810791
>>> 
>>> 
>>> nones = [None] * n
>>> start = time.time()
>>> a = [str(x) for x in nones]
>>> end = time.time()
>>> print(end - start)
3.240807056427002
>>> 
>>> 
>>> start = time.time()
>>> a = [str(x) if x is not None else None for x in nones]
>>> end = time.time()
>>> print(end - start)
0.5311591625213623
```

**Comment by jaidisido** [comment]
Thanks for the fix, it was merged and will be available in the next release
