### ISSUE TITLE
Specify measure_name as explicit optiona arg when writing multi-measure values to Timestream

### ISSUE THREAD

**Issue by mdavis-xyz** [aws/aws-sdk-pandas#1885]
**Is your feature request related to a problem? Please describe.**

When writing a dataframe to Timestream, the `measure_name` value is just the name of the first column.

https://github.com/aws/aws-sdk-pandas/blob/3ec0145fc1e95ff879a547fc36c961adb5ee83f6/awswrangler/timestream.py#L74

There are two issues with this, for multi-measure writes:

* I want to ingest files which may have an unpredictable column ordering. That means that the metric_name value is not consistent, and will differ between each set of records
* the first column is no more important than any other column. e.g. if I have a weather sensor giving me temperature and humidity, it doesn't make sense to call the pair of them just "humidity" or just "temperature". It would make more sense to set measure_name='weather'.

**Describe the solution you'd like**

For [awswrangler.timestream.write](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.timestream.write.html#awswrangler.timestream.write), add an optional argument, `measure_name`, which is a string.
If present, it will be used for the measure_name, instead of the first column-name.

Since it's optional, this is backwards compatible.

We may as well accept this argument for single-measure writes as well.

**Describe alternatives you've considered**
Asking the user to manually sort columns before writing seems like unnecessary effort for each write, and will likely be forgotten.

**Comment by malachi-constant** [comment]
Hi @mdavis-xyz does the parameter `measure_col` of [`wr.timestream.write()`](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.timestream.write.html#awswrangler.timestream.write) not work for your use case?

**Comment by mdavis-xyz** [comment]
No. `measure_col` is used to specify which column(s) in the dataframe to write as measures. (Other columns will be used for time and dimensions. And I assume you can have columns in the dataframe that you want ignored and not written.)

 What I want is an argument to pass that will be used as the value of the extra column `measure_name` which timestream adds to all records.

e.g. if I run this:

```
import awswrangler as wr
from datetime import datetime

import pandas as pd

df = pd.DataFrame(
    {
        "time": [datetime.now(), datetime.now(), datetime.now()],
        "dim0": ["foo", "boo", "bar"],
        "dim1": [1, 2, 3],
        "temperature": [1.0, 1.1, 1.2],
        "humidity": [2.0, 2.1, 2.2],
    }
)

rejected_records = wr.timestream.write(
    df=df,
    database="mwe",
    table="gh1885",
    time_col="time",
    measure_col="weather",
    dimensions_cols=["dim0", "dim1"],

)

assert len(rejected_records) == 0
```

I get:

```
Traceback (most recent call last):
  File "/Users/matthew/Downloads/ts-test.py", line 16, in <module>
    rejected_records = wr.timestream.write(
  File "/Users/matthew/.local/lib/python3.10/site-packages/awswrangler/timestream.py", line 228, in write
    measure_types: List[str] = [
  File "/Users/matthew/.local/lib/python3.10/site-packages/awswrangler/timestream.py", line 229, in <listcomp>
    _data_types.timestream_type_from_pandas(df[[measure_col_name]]) for measure_col_name in measure_cols_names
  File "/Users/matthew/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3511, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/Users/matthew/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5782, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/Users/matthew/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5842, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['weather'], dtype='object')] are in the [columns]"
```

If I change `measure_col` to `measure_col=["temperature", "humidity"]`, then the script runs without throwing an exception. But now in my table there's a column called `measure_name` with value `temperature`. It doesn't make sense to have a record with humidity labelled as temperature. (Even though the humidity column is still called humidity.)

**Comment by malachi-constant** [comment]
@mdavis-xyz Thanks for the clarification I have opened a PR for review by the team.
