### ISSUE TITLE
Applying LTRIM automatically while copying files from S3 to redshift

### ISSUE THREAD

**Issue by ahmadapahmad** [aws/aws-sdk-pandas#1886]
### Describe the bug

My data (parquet) in S3 have some leading & trailing spaces (intensional). when I use (wr.redshift.connect) command to load it into Redshift table. The (wr.redshift.connect) command is applying LTRIM on my rows automatically which should not be applied.

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

The leading and trailing spaces should propagate to redshift unless I apply LTRIM/RTRIM on it intensionally.

### Screenshots

data = {'visitor': [' foo', 'bar', 'jelmer'], 
        'A': [0, 1, 0],
        'B': [1, 0, 1],
        'C': [1, 0, 0]}
        

df = spark.createDataFrame(pd.DataFrame(data))
df.write.mode("overwrite").parquet(S3_URI)

con = wr.redshift.connect(connection  = REDSHIFT_CONNECTOR, dbname = TARGET_DATABASE)
wr.redshift.copy_from_files(
        path = S3_URI,
        con = con,
        table = TARGET_TABLE,
        schema = TARGET_SCHEMA,
        iam_role = args['REDSHIFT_ROLE_ARN'],
        mode = 'overwrite',
        overwrite_method = 'truncate'
      )

### OS

linux

### Python version

3.8

### AWS SDK for pandas version

2.17

**Comment by jaidisido** [comment]
I am afraid I am unable to reproduce this. The below script asserts that the trailing space is preserved:
```
import awswrangler as wr
import pandas as pd

con = wr.redshift.connect(connection="aws-sdk-pandas-redshift")

data = {
    "visitor": [" foo", "bar", "jelmer"],
    "A": [0, 1, 0],
    "B": [1, 0, 1],
    "C": [1, 0, 0],
}

df = pd.DataFrame(data)

wr.s3.delete_objects(path=path)

wr.s3.to_parquet(df=df, path=path, dataset=True)

df_s3 = wr.s3.read_parquet(path)
assert df_s3["visitor"].isin(data["visitor"]).all()

wr.redshift.copy_from_files(
    path=path,
    con=con,
    table=table,
    schema=schema,
    iam_role=iam_role,
    mode="overwrite",
    overwrite_method="truncate"
)

df_redshift = wr.redshift.read_sql_table(con=con, table=table, schema=schema)
assert df_redshift["visitor"].isin(data["visitor"]).all()
```

The only difference with your script is that the data frame is not written via Spark. Did you check that it's not the Spark write that caused the trailing space to go missing?
