### ISSUE TITLE
pandas FutureWarning in to_parquet with length-1 partition_cols argument

### ISSUE THREAD

**Issue by abefrandsen** [aws/aws-sdk-pandas#1894]
### Describe the bug

When writing a parquet dataset via `to_parquet` and setting the `partition_cols` argument as a length-1 list (to just partition on a single column), I get the following warning:

> .../awswrangler/s3/_write_dataset.py:92: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
    for keys, subgroup in df.groupby(by=partition_cols, observed=True):

### How to Reproduce

awswrangler version 2.18.0
pandas version 1.5.1

```python
from awswrangler.s3 import to_parquet
import pandas as pd

df = pd.DataFrame(data={'col1':[1,2,2,3], 'col2':['a','b','c','d']})
to_parquet(df, 's3://my-bucket/dataset/', dataset=True, partition_cols = ['col1'])
```

### Expected behavior

No warning should be given, since awswrangler should properly call pandas `groupby` when given a single column as the partition column. I suggest allowing the `partition_cols` argument to be either a list of strings or a single string.  

### OS

Linux

### Python version

3.9.13

### AWS SDK for pandas version

2.18.0

**Comment by jaidisido** [comment]
Thank you for flagging this @abefrandsen, we will have a look asap

**Comment by agu3rra** [comment]
FYI: I believe this could be related to https://github.com/pandas-dev/pandas/issues/42795.

**Comment by kukushking** [comment]
Hi @agu3rra in the current versions of the library this is already handled by [L94](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/s3/_write_dataset.py#L94). This warning will disappear with pandas 2.x and L94 will no longer be needed because the behaviour will become consistent and will always return keys tuple if passed a list.

It is possible to avoid the warning in the current versions by changing as follows:
```
for keys, subgroup in df.groupby(
        by=partition_cols[0] if len(partition_cols) == 1 else partition_cols, observed=True
    ):
```
But IMO this is redundant since i the future behaviour is going to become consistent anyways. I'm open to suggestions though

**Comment by agu3rra** [comment]
I wasn't really using `aws-sdk-pandas`, but I was able to get rid of this warning by replacing my `groupby`'s single string entry array for a `string`. So where I had `df.groupby(["some_column"])` I turned it into `df.groupby("some_column")`. Pasting it here in case someone ends up here same as I did when looking for this answer. ☺️
Cheers!

**Comment by kukushking** [comment]
@agu3rra thank you!

**Comment by jpcaram** [comment]
Hi!
Can I get some clarification? I'm not sure what this warning really means and what the behavior will become.
The behavior of `for x in df.groupby(names)` has been that `x` is a two-element tuple. Is this saying that the length `x` (1 or 2) will become a function of `len(names)` (1 or more) and that `x` will still be a two-element tuple if `type(names)==str`?
Thanks!
