### ISSUE TITLE
Add integration with OpenSearch Serverless

### ISSUE THREAD

**Issue by RobotCharlie** [aws/aws-sdk-pandas#1917]
**Is your feature request related to a problem? Please describe.**
Given AWS OpenSearch Service now has OpenSearch Serverless in [preview](https://aws.amazon.com/opensearch-service/features/serverless/), if would be nice if AWS Panda SDK supports OpenSearch Serverless just like how it support OpenSearch.

**Describe the solution you'd like**
AWS Panda SDK start integrating with OpenSearch Serverless like it does with OpenSearch. Knowing it might need to make sure some of the dependencies integrated with OpenSearch Serverless first.

**Describe alternatives you've considered**
N/A

**Additional context**
AWS Panda SDK should be able to
- Initialize collections in OpenSearch Serverless
- index data to collections
- search data in collections
- delete data in collections

Similar to how it supports AWS OpenSearch https://github.com/aws/aws-sdk-pandas/blob/main/tutorials/031%20-%20OpenSearch.ipynb

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by cnfait** [comment]
Thanks for the feature request - this is something I started working on before the end of the year, I should be able to open a PR soon!

**Comment by kukushking** [comment]
Hi @RobotCharlie, there is an open PR for this feature and it's already available to try if you install from the feature branch:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@feat/opensearch-serverless
```
It features ability to create collections with all (network, encryption, data) required policies and indexing / searching through the same OpenSearch API client. Check out the [tutorial](https://github.com/aws/aws-sdk-pandas/blob/dc4002524f34929a5eb792b1c548ceddff83c8bb/tutorials/035%20-%20OpenSearch%20Serverless.ipynb) for more

**Comment by RobotCharlie** [comment]
> Hi @RobotCharlie, there is an open PR for this feature and it's already available to try if you install from the feature branch:
> 
> ```
> 
> pip uninstall awswrangler -y
> 
> pip install git+https://github.com/awslabs/aws-data-wrangler.git@feat/opensearch-serverless
> 
> ```
> 
> It features ability to create collections with all (network, encryption, data) required policies and indexing / searching through the same OpenSearch API client. Check out the [tutorial](https://github.com/aws/aws-sdk-pandas/blob/dc4002524f34929a5eb792b1c548ceddff83c8bb/tutorials/035%20-%20OpenSearch%20Serverless.ipynb) for more 

Awesome! I will try it out sometime this weekend!
