### ISSUE TITLE
Add toggle to allow empty dataframes

### ISSUE THREAD

**Issue by tbranscombe** [aws/aws-sdk-pandas#1921]
I would like the write_parquet() function to not fail when the input dataframe is empty

There is a check in _validate_args():
```
if df.empty is True:
        raise exceptions.EmptyDataFrame("DataFrame cannot be empty.")
```

I would like an additional argument to write_parquet, something like allow_empty_df to toggle whether empty dataframes are allowed.

```
if df.empty is True and allow_empty_df is not True:
        raise exceptions.EmptyDataFrame("DataFrame cannot be empty.")
```

**Comment by jaidisido** [comment]
Hi @tbranscombe, as a general rule we try to limit the number of input arguments to a minimum by avoiding avoid edge cases. As you can see from the [docs](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html#awswrangler.s3.to_parquet) of the `to_parquet` method for example, it's already overloaded with numerous arguments.

What is the actual use case for an empty data frame? If there is no data in it, then what would be written?

**Comment by tbranscombe** [comment]
There are downstream pipelines which manipulate and combine a folder of parquets created with the `to_parquet` method. It would fail if a file is missing, but will consume an empty parquet file, as long as it has the correct datatypes. Ideally, it would right a parquet file with no rows, but the correct columns and column data types using the dtype argument.

**Comment by jaidisido** [comment]
I am afraid that is too much of an edge case for us to overload the method and it can be handled client side with a simple if condition to process it separately

**Comment by tbranscombe** [comment]
I understand, thank you for looking into it!
