### ISSUE TITLE
Support keeping Athena CTAS temporary tables until explicitly deleted

### ISSUE THREAD

**Issue by ddrinka** [aws/aws-sdk-pandas#1924]
I love the awswrangler Athena support--there are a multitude of ways to get data from my SQL query to Pandas.  However, one spot that's lacking is the ability to use the output of one query as the input for another without re-uploading the query results using `s3.to_parquet`.

I would like an option for `athena.read_sql_query` in CTAS mode to keep the temporary table created from the query results, embed the temporary table name in `query_metadata`, and provide a destructor method that deletes the temporary table and S3 data.

If this were available I could run a query in one Jupyter cell, view the results (potentially in batches), and then query against those results in Athena or join in additional data, while finally cleaning up the temporary state in a later cell.

**Comment by jaidisido** [comment]
Hi @ddrinka, would the [create_ctas_table](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.create_ctas_table.html#awswrangler.athena.create_ctas_table) achieve what you have in mind? It creates a CTAS table, returns the query metadata and keeps the S3 objects. Setting the `wait` argument to True ensures that the query completes. In fact, `read_sql_query` is using this same method under the hood.

Also note the `keep_files` argument in [read_sql_query](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.read_sql_query.html#awswrangler.athena.read_sql_query) which preserves the S3 objects from the CTAS

**Comment by ddrinka** [comment]
@jaidisido In my use case I'd still like the results delivered locally, but with the table as well as the S3 files left behind.  The benefit to me is the notebook user gets a preview of the intermediate query results (optionally just the first batch of results), but the data also exists as a temporary table that future Athena queries can use.

If you think of a Spark workflow where you might combine a series of operations or SQL queries, while being able to view any of the intermediate results, but with the power of Athena backing each workflow step, that's what I'm trying to emulate using wrangler.

**Comment by jaidisido** [comment]
I feel this is too opinionated and specific of a use case. The library aims to provide decoupled methods to help develop your own workflow like the one you are describing but we want to avoid catering for narrow ones if they are not generic enough
