### ISSUE TITLE
Bug using pyarrow_additional_kwargs parameter in awswrangler.s3.to_parquet 

### ISSUE THREAD

**Issue by aarana95** [aws/aws-sdk-pandas#1940]
### Describe the bug

I want save a pandas dataframe in s3 using to_parquet, but I have this error  `pyarrow.parquet.ParquetWriter() got multiple values for keyword argument 'use_dictionary'`. My code is this:

```
wr.s3.to_parquet(df=df, index=False, compression='zstd', database='database', table='sites_parquet_zstd', dataset=True,
                           partition_cols=['country'], pyarrow_additional_kwargs={'use_dictionary': True})
```

I try to execute directly from pandas and runs. This code works:

```
df.to_parquet('df.parquet', index=False, compression='zstd', use_dictionary= False)
```

In both cases df is a pandas dataframe

### How to Reproduce

I'm executing in Lambda with Docker image.
This is the set up:
```
python 3.9
awswrangler = "~=2.17.0"
boto3 = "~=1.26.17"
pyarrow = "~=8.0.0"
zstandard= "~=0.19.0"
```

### OS

Docker

### Python version

3.9

### AWS SDK for pandas version

2.17.0

**Comment by kukushking** [comment]
Hi @aarana95 , `use_dictionary=True` is passed by default: [L70](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/s3/_write_parquet.py#L70)

**Comment by kukushking** [comment]
Added the ability to override it through `pyarrow_additional_kwargs`.
