### ISSUE TITLE
Athena - SHOW VIEWS Query returns empty 

### ISSUE THREAD

**Issue by yuval-illumex** [aws/aws-sdk-pandas#1980]
### Describe the bug

When trying to run the "SHOW VIEWS" as sql command, an empty dataframe returns.
The query works when running directly using boto3

### How to Reproduce

Using Athena Engine V2:

```
wr.athena.read_sql_query("SHOW VIEWS;", database="first-db",ctas_approach=False)
```

### Expected behavior

Dataframe with list of views are returned.

### OS

mac m1

### Python version

3.9.10

### AWS SDK for pandas version

2.19.0

**Comment by jaidisido** [comment]
`SHOW VIEWS` is a DDL statement which does not produce results in a csv or parquet file and that is required by the `wr.athena.read_sql` method to pull the results from S3

**Comment by yuval-illumex** [comment]
@jaidisido how can I run a SHOW VIEWS query using wr?
information_schema is not working as expected so I have to use SHOW VIEWS
