### ISSUE TITLE
`wr.lakeformation.read_sql_query` doesn't pass `boto3_session` to `commit_transaction`

### ISSUE THREAD

**Issue by henriblancke** [aws/aws-sdk-pandas#2007]
### Describe the bug

`commit_transaction` [here](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/lakeformation/_read.py#L222) does not pass along the `boto3_session` from it's parent function `read_sql_query`.

### How to Reproduce

```
Without default aws credentials configured on your machine, create a boto3 session and pass it to `wr.lakeformation.read_sql_query`
```

### Expected behavior

`commit_transaction` uses the `boto3_session` passed to `read_sql_query`

### OS

Mac

### Python version

3.10

### AWS SDK for pandas version

2.19.0

**Comment by jaidisido** [comment]
Good catch, thanks. Now fixed in `main`
