### ISSUE TITLE
Issue using boto3 session with assumed role credentials to list and copy files from S3

### ISSUE THREAD

**Issue by brunomenegotto** [aws/aws-sdk-pandas#2014]
### Describe the bug

Hello,

I'm trying to use a custom Boto3 session with credentials obtained from Boto3 STS Assume Role to list files from another AWS Account bucket (let's call it Account A) and copy them to a bucket in my account (let's call it Account B). I'm able to create the session with assumed role credentials [as described here](https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/002%20-%20Sessions.html#Using-a-new-custom-Boto3-Session) but when I try to list the files from the bucket using this session, I get a `botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied`. 

I've tried to do the same thing copying only one object using Boto3 and it works as expected. Is this a known issue?

Thanks

### How to Reproduce

Have a role on account A with below policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetObjectAcl",
                "s3:GetBucketAcl",
                "s3:GetObject",
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::account_a_bucket/*",
                "arn:aws:s3:::account_a_bucket/"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetObjectAcl",
                "s3:GetBucketAcl",
                "s3:GetObject",
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::account_b_bucket",
                "arn:aws:s3:::account_b_bucket/*"
            ]
        }
    ]
}
```

Assume this role in boto3:

```
sts_client = boto3.client('sts')
    assumed_role_object = sts_client.assume_role(
        RoleArn="arn:aws:iam::<account_id>:role/<role_name>",
        RoleSessionName="Session1"
    )
```

Get the credentials from role:

`credentials = assumed_role_object['Credentials']`

Create the session using role's credentials:

`my_session = boto3.Session(aws_access_key_id=credentials['AccessKeyId'], aws_secret_access_key=credentials['SecretAccessKey'], aws_session_token=credentials['SessionToken'], region_name="us-west-2")`

Try to list the objects from Account A bucket using the session:

`objs_list = wr.s3.list_objects("s3://some-bucket-name/", boto3_session=my_session)`

### Expected behavior

List and copy files using custom session

### OS

Docker Linux - python:3.9.7-slim-bullseye

### Python version

3.9

### AWS SDK for pandas version

2.19.0

**Comment by brunomenegotto** [comment]
Hi @kukushking , tks for your quick reply!

I've tested what you asked and the issue still occurring, I'm attaching some screenshots from `pip install` and the error trace.

Just to let you know, we have tested the `copy_objects`  passing a list with only one object path from the source bucket using the same session used in `list_objects` and it worked as expected. I guess this is issue may be related to the list action only.

I've attached some screenshots below:

![Screen Shot 2023-02-13 at 15 55 59](https://user-images.githubusercontent.com/12800798/218552168-18a85e66-bf25-46f5-93c8-6bfddb6a285a.png)
![Screen Shot 2023-02-13 at 15 59 49](https://user-images.githubusercontent.com/12800798/218552181-0941f9eb-67a0-430e-9938-0bdece7f2164.png)
![Screen Shot 2023-02-13 at 15 57 09](https://user-images.githubusercontent.com/12800798/218552186-75baddfd-47fc-4a72-93c4-e1b4ae9fbe0b.png)
![Screen Shot 2023-02-13 at 15 56 36](https://user-images.githubusercontent.com/12800798/218552187-48054453-e90f-4db2-9cef-c30c6165b83a.png)

**Comment by jaidisido** [comment]
@brunomenegotto have you tested listing using your x-account session and the [list_objects_v2](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.list_objects_v2) boto3 call directly? Trying to understand if it's related to the library or to your IAM role

**Comment by brunomenegotto** [comment]
Hi @jaidisido , I've tested both listing and copying via boto3 using the cross account assumed role and it works as expected.

**Comment by brunomenegotto** [comment]
Hi guys @kukushking and @jaidisido , I'm here to bring some good news:

We found the issue, the bucket from `Account A` has a bucket policy and the role we are using wasn't in the statement allowing the `s3:Get` and `s3:List` actions. After adding the role to the principals list, the list and copy actions worked like a charm. 

Thanks for your attention and sorry for my misunderstanding, I'm closing this issue.
