### ISSUE TITLE
Loosen boto version constraints to include Lambda

### ISSUE THREAD

**Issue by mdavis-xyz** [aws/aws-sdk-pandas#2017]
**Is your feature request related to a problem? Please describe.**

I want to use awswrangler with the version of boto3 and botocore that's installed in Lambda functions.

awswrangler is a large library. I also need to install other libraries in my lambda. I can't fit them all in. But Lambda comes with boto3 and botocore already, which don't count to the size limit. So I want to use those versions of boto3 and botocore, instead of duplicating those with slightly different versions.

Today, [the versions of boto3 and botocore in AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) are boto3-1.20.32 and botocore-1.23.32. The latest version of awswrangler is  2.19.0. (I want a feature that didn't exist in earlier versions of awswrangler.)

If you try to pip install these together, it doesn't work.

```
$ pip install botocore==1.23.32 awswrangler==2.19.0
Collecting botocore==1.23.32
  Using cached botocore-1.23.32-py3-none-any.whl (8.5 MB)
Collecting awswrangler==2.19.0
  Using cached awswrangler-2.19.0-py3-none-any.whl (267 kB)
Collecting urllib3<1.27,>=1.25.4
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of botocore to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install awswrangler==2.19.0 and botocore==1.23.32 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested botocore==1.23.32
    awswrangler 2.19.0 depends on botocore<2.0.0 and >=1.27.11

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

The boto3 and botocore dependencies of awswrangler are defined [here](https://github.com/aws/aws-sdk-pandas/blob/main/pyproject.toml#L30-L31):

```
boto3 = "^1.24.11"
botocore = "^1.27.11"
```

Why are they those values?

Realistically, not much changes between boto3 and botocore versions. Will awswrangler still work with those slightly older versions?

**Describe the solution you'd like**

The boto3 and botocore version constraints in pyproject.toml should be loosened to include the versions [in the lambda docs here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).

**Describe alternatives you've considered**

I could install duplicate copies of boto3 and botocore in my lambda. That would increase total size above the size limit for lambda zip files.

I could switch to deploying lambda as docker images not zips, which have a larger size limit. But then I lose the ability to use Lambda Layers for my project's shared libraries.

I could use the layer for awswrangler that is already provided by AWS, but then I'd lose the ability to do local unit testing with exactly the files that will be deployed.

**Comment by mdavis-xyz** [comment]
I just ran the moto tests with the lambda versions of boto3 and botocore. The tests passed. So the version doesn't need to be as recent as it is in the requirements.

**Comment by malachi-constant** [comment]
@mdavis-xyz I think it's a reasonable request. @cnfait I see we increased the lower constraint of `boto` and `botocore` in your [PR](https://github.com/aws/aws-sdk-pandas/pull/1591/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711) do you recall the reason for that (maybe redshift data api support) ?.

**Comment by jaidisido** [comment]
There are a number of APIs that require later versions of botocore/boto3 to work. Examples include the Redshift API, Glue Data Quality, Opensearch Serverless and a few more. Our moto tests do not cover those.

My only worry about lowering the constraint is that it might represent a breaking change. Say I am using the Glue Data Quality feature in 2.19.0. I upgrade to 2.20 and pip resolves boto3/botocore to a lower version that does not cover that feature then my scripts would start failing for no good reason.

**Comment by mdavis-xyz** [comment]
> pip resolves boto3/botocore to a lower version

Why would it do that?

Doesn't pip just maximise versions within the constraints, and we're not changing the upper constraint.

**Comment by jaidisido** [comment]
It would do it if the user is trying to install another package besides awswrangler which is constraining the upper version of boto3/botocore. As it's now, it would raise an error as it did for you, but would happily oblige if we lower our constraint.

**Comment by mdavis-xyz** [comment]
Having an error where botocore is too low a version, so the user just increases it themselves, sounds like a far better situation for the user than a pip install error refusing to install what they want.

This wouldn't even be a new problem. The current constraints in pyproject.toml are 

> boto3 = "^1.24.11"
> botocore = "^1.27.11"

That includes 162 versions of boto3, and about the same again for botocore. So there are 26 *thousand* combinations of just those two libraries, compliant with pyproject.toml. You don't currently test all those combinations. Theoretically someone could install awswrangler and another library, and end up with a pair of those that you haven't tested. That's the same issue.

This library already allows a range of boto* versions, not an exact version. Expanding that range doesn't change anything qualitatively, it just expands the risk that's already present.

You *could* just pin the exact version of boto3 and botocore that you test. But if every library did that to their dependencies, it would be impossible to install any non-trivial dependency tree. In my view libraries should have dependencies as loose as possible, and only applications should have narrow dependencies. This library should have the version constraint set to one above the highest version of boto* that's known to not work, not the lowest version of boto that is known to work. 

If the concern is that in the future this library will start to use a feature that's not in the lower version, well can we mitigate that by just running the CICD tests with the lowest versions of botocore and boto3? (And not testing the 26 thousand combinations in between.)

What's the current approach for choosing the existing version constraints? Won't it remain the same?

**Comment by jaidisido** [comment]
Latest release (3.0) pins boto3 and botocore to the lambda equivalent versions. Closing as a result
