### ISSUE TITLE
Timestream.write - optional arg to ignore record rejection due to version

### ISSUE THREAD

**Issue by mdavis-xyz** [aws/aws-sdk-pandas#2018]
# Is your feature request related to a problem? Please describe.

The documentation for [awswrangler timestream write](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.timestream.write.html#awswrangler.timestream.write) says the return value is:

> Returns: Rejected records.

That's not really clear. Why would records be rejected?

Timestream has inbuilt record versioning. I was expecting either the service, or this library, to gracefully ignore any records that I try to write where the version is not newer than what's already in the table. But I wasn't sure. It's not clear from the documentation which way that works. From testing, it seems that's not the case. Instead those records are returned in rejected records. 

But are there any other reasons why a record might be rejected? It's not clear.

# Describe the solution you'd like

Two parts.

## Doc update

First, update the documentation to describe today's behavior. 
State that records which are old versions will be rejected.
Provide an example of rejected records.

```
[{'ExistingVersion': 200,
  'Reason': 'The record version 2 is lower than the existing version 200. A '
            'higher version is required to update the measure value.',
  'RecordIndex': 0}]
```

This example is required so that users can figure out how to check the reason for record rejection, to not ignore other reasons for record rejection.

## Functional update

I would like to pass an argument to awswrangler to make it ignore records which are rejected due to version issues, but not ignore records which are rejected due to any other reason. (Is there any other reason?)

I can maybe write this myself. I just need clarity on the other reasons why a record might be rejected.

**Comment by jaidisido** [comment]
The reasons why a record is rejected are listed [here](https://docs.aws.amazon.com/timestream/latest/developerguide/API_RejectedRecord.html). They include records with duplicate data, timestamps that lie outside the retention duration of the memory store and records that exceed Timestream defined limits.

We can add the link above to our API docs.

**Comment by mdavis-xyz** [comment]
Yes I can add that link. Should I also add the example response payload?

**Comment by jaidisido** [comment]
I would think the link is enough but the example response can be added too if you think it will be helpful. Thank you
