### ISSUE TITLE
Execution error : field account_sharing_list: ArrayType(LongType,true) can not accept object array([1252682, 1501458]) in type <class 'numpy.ndarray'>

### ISSUE THREAD

**Issue by cotrariello84** [aws/aws-sdk-pandas#2021]
Dear Team, 
I am triyng to create a spark dataframe from a pandas dataframe created by aws.wrangler.
here my code
**Athena DDL**:
`    account_sharing_list array<bigint> COMMENT ''     `

**Glue Job**:
`df = wr.athena.read_sql_query(sql=query, database="silver")`
`registration_schema =  StructType([`
`        StructField("account_sharing_list",ArrayType(LongType(), True),nullable=True)`
`])`
`df_delta = spark.createDataFrame(df,schema=registration_schema)`

_dl.info_:
`account_sharing_list  438 non-null    object `

I get this error: 
`Execution error : field account_sharing_list: ArrayType(LongType,true) can not accept object array([1252682, 1501458]) in type <class 'numpy.ndarray'>`

How could I solve it? and why this happen?

thank you.

**Comment by jaidisido** [comment]
I am no pyspark expert but from the error it seems that the schema you are trying to apply simply does not match the column type. I was able to reproduce this with similar error:
```
df = pd.DataFrame(np.array([1252682, 1501458]), columns=["account_sharing_list"])

registration_schema =  StructType([
        StructField("account_sharing_list",ArrayType(LongType(), True),nullable=True)
])
df_delta = spark.createDataFrame(df, schema=registration_schema)
```
which raises TypeError: field account_sharing_list: ArrayType(LongType(), True) can not accept object 1252682 in type <class 'int'>

Not supplying the schema did not raise an issue. Perhaps you could first let spark infer the data type and then try to build/adjust the schema based on that

**Comment by cotrariello84** [comment]
Hi @jaidisido, first of all , thank you for oyu support and answer.
I tried you tips but I get this error: Unable to infer the type of the field account_sharing_list.
