### ISSUE TITLE
wr.s3.to_parquet returns  "Both SchemaReference and Columns are populated, only one of them should be populated"

### ISSUE THREAD

**Issue by skinofstars** [aws/aws-sdk-pandas#2027]
### Describe the bug

When writing a data frame to an existing table with glue schema using the following

```python
wr.s3.to_parquet(
    df=df,
    path=path,
    dataset=True,
    partition_cols=["country", "year", "month", "day"],
    mode="overwrite_partitions", 
    database=database,
    table=table,
)
```

I get the following error

`botocore.errorfactory.InvalidInputException: An error occurred (InvalidInputException) when calling the UpdateTable operation: Both SchemaReference and Columns are populated, only one of them should be populated.`

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### OS

mac

### Python version

3.10.3

### AWS SDK for pandas version

2.19.0

**Comment by kenrickveit** [comment]
@skinofstars I encountered this error message when I had column names defined with upper cased first characters.  I believe under the covers schema evolution was being attempted to rectify this.  So one failure mode to check is column name rules in Athena:
https://docs.aws.amazon.com/athena/latest/ug/tables-databases-columns-names.html

The error message is very vague though.

**Comment by skinofstars** [comment]
@kenrickveit thanks very much, that solved my issue
