### ISSUE TITLE
Mocked test environment instruction issues

### ISSUE THREAD

**Issue by mdavis-xyz** [aws/aws-sdk-pandas#2035]
I want to write a PR for this library. I'm struggling to install from a git clone.

I did a `git clone`. Then I created a virtual env and tried `pip install ./` at both the root of the repo, and `awswrangler` subdirectory.

```
$ pip3 install -e ./aws-sdk-pandas/
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/ec2-user/environment/scratch/timestream-null/aws-sdk-pandas
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```

```
$ pip3 install -e ./aws-sdk-pandas/awswrangler/ 
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/ec2-user/environment/scratch/timestream-null/aws-sdk-pandas/awswrangler
```

[contributing.md](https://github.com/aws/aws-sdk-pandas/blob/main/CONTRIBUTING.md) says:

> Then run the command bellow to install all dependencies:
> `poetry install --extras "sqlserver oracle sparql deltalake"`

Well I've never used poetry before, so that's not installed. Can we add it to the steps here?
I'm guessing it's just `pip3 install poetry`. Obviously this is such a trivial change that it's not worth writing a PR for just that. But if we're going to make other changes to these instructions (see below), we should add that.

So now I run:

```
poetry install --extras "sqlserver oracle sparql deltalake"
```

Then `./validate.sh`, which failed.

```
awswrangler/oracle.py:43: error: Name "oracledb.Connection" is not defined  [name-defined]
awswrangler/oracle.py:44: error: "Module oracledb" does not explicitly export attribute "Connection"  [attr-defined]
awswrangler/oracle.py:58: error: Name "oracledb.Cursor" is not defined  [name-defined]
awswrangler/oracle.py:74: error: Name "oracledb.Cursor" is not defined  [name-defined]
awswrangler/oracle.py:82: error: Name "oracledb.Cursor" is not defined  [name-defined]
awswrangler/oracle.py:117: error: Name "oracledb.Connection" is not defined  [name-defined]
awswrangler/oracle.py:178: error: "Module oracledb" does not explicitly export attribute "makedsn"  [attr-defined]
awswrangler/oracle.py:180: error: "Module oracledb" does not explicitly export attribute "connect"  [attr-defined]
awswrangler/oracle.py:193: error: Name "oracledb.Connection" is not defined  [name-defined]
awswrangler/oracle.py:259: error: Name "oracledb.Connection" is not defined  [name-defined]
awswrangler/oracle.py:332: error: Name "oracledb.Connection" is not defined  [name-defined]
awswrangler/oracle.py:434: error: "Module oracledb" does not explicitly export attribute "Cursor"  [attr-defined]
awswrangler/oracle.py:437: error: Module has no attribute "DB_TYPE_NUMBER"  [attr-defined]
awswrangler/oracle.py:448: error: "Module oracledb" does not explicitly export attribute "LOB"  [attr-defined]
awswrangler/oracle.py:450: error: "Module oracledb" does not explicitly export attribute "LOB"  [attr-defined]
Found 15 errors in 1 file (checked 83 source files)
```

Hmm. Ok so why did the validation fail? What do I do if validation fails?

Let's try the next step, which also fails.

```
$ pytest tests/test_moto.py::test_get_bucket_region_succeed
ImportError while loading conftest '/home/ec2-user/environment/scratch/timestream-null/aws-sdk-pandas/tests/conftest.py'.
tests/conftest.py:12: in <module>
    import awswrangler as wr
awswrangler/__init__.py:10: in <module>
    from awswrangler import (  # noqa
awswrangler/sqlserver.py:22: in <module>
    import pyodbc  # pylint: disable=import-error
E   ImportError: libodbc.so.2: cannot open shared object file: No such file or directory
```

Is that a related error, or unrelated error?
This looks like I need to `yum/apt install` some ODBC drivers. But I'm following the instructions for "Mocked test environment", which I expect doesn't involve any real database connectivity.

Playing around, it looks like validation and tests pass if I **don't** install the extras.
Because there's a try/except somewhere (in the sqlserver library?) which will ignore the absence of pyodbc, but if pyodbc is present, it expects odbc drivers to be present too. I want to write a PR for something that doesn't use ODBC (timestream). I expect that I don't have to install ODBC drivers for every database flavor that this library supports.

**Comment by jaidisido** [comment]
Thanks for raising these points @mdavis-xyz, I have gone through the exercise of updating the contributing guide in #2054. I was able to successfully run the `validate.sh` and `moto` tests on my local machine by following these [instructions](https://github.com/aws/aws-sdk-pandas/blob/971a96dd5f8038e1bf196d2b3a032020ccac0799/CONTRIBUTING.md#step-by-step). Please let us know if they work for you too and we will merge the PR.

**Comment by mdavis-xyz** [comment]
Yep, those instructions work for me.

`validate.sh` is passing now.
