### ISSUE TITLE
Expose CTAS `storage_format` when using `read_sql_query`

### ISSUE THREAD

**Issue by ClementAcher** [aws/aws-sdk-pandas#2041]
[Parquet doesn't handle well empty arrays](https://stackoverflow.com/questions/59674324/parquet-record-is-malformed-while-column-count-is-not-0#:~:text=Turns%20out%20Parquet%20does%20not,empty%20arrays%20to%20NULL%20values.) which can cause issue when using the CTAS feature in Athena queries (https://repost.aws/questions/QUSMCQJ1R-QcWBxHOhX_yJdA/ctas-cant-handle-empty-arrays-or-maps). I am having this issue using `awswrangler.athena.read_sql_query`

According to the post above, a simple fix is to use the ORC format instead of the default parquet format when creating the CTAS table.

It seems that it is possible to pass the `storage_format` in the `create_ctas_table` function
https://github.com/aws/aws-sdk-pandas/blob/96640ad399958a7590522816e689145a4bbefeb0/awswrangler/athena/_utils.py#L774

This parameter is however not available in the `read_sql_query` method. Would it be possible to add it in order to use OCR instead of parquet?

**Comment by jaidisido** [comment]
I am afraid it's not that simple. The reason `storage_format` is not exposed is that CTAS approach in `wr.athena.read_sql_query` reads the results of the CTAS query expecting a [parquet](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/athena/_read.py#L291) file. So we would first need to create a similar method that can read ORC instead. A similar [issue](https://github.com/aws/aws-sdk-pandas/issues/615) for ORC was created in the past and pyarrow support was deemed insufficient and not part of the roadmap.

**Comment by ClementAcher** [comment]
Thanks for the answer @jaidisido - I missed that indeed!
