### ISSUE TITLE
Redshift.unload should still produce parquet file when query returns no data

### ISSUE THREAD

**Issue by WillAyd** [aws/aws-sdk-pandas#2052]
Right now if you try 

```python
df = wr.redshift.unload(
    sql="SELECT a, b FROM public.maybe_empty_table"
)
```

The library will yield a `wr.exceptions.NoFilesFound` exception. This can be caught, but it then puts the onus on the end user to build an empty dataframe with the proper columns and data types, which can be pretty verbose when selecting multiple columns

**Comment by jaidisido** [comment]
The `wr.redshift.unload` method relies on reading the output S3 files to build the data frame and its metadata (columns and types). Without those files we would have to find an alternative way to recreate this metadata, effectively mimicking what the Redshift engine would have produced if data was available. It does not seem like a straightforward operation but happy to hear if you have any suggestions?

**Comment by WillAyd** [comment]
I am naive on what elements are performing which actions here, but my assumption is that a file with only schema information would be placed on S3 to read in

**Comment by jaidisido** [comment]
We simply execute this UNLOAD [query](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/redshift.py#L1069) against the Redshift service. My understanding in your case is that the resulting query does not produce S3 objects at all, so there wouldn't be a file to read a schema from

**Comment by WillAyd** [comment]
Correct there is no file produced. Hmm ok - must be a feature request for UNLOAD to produce the file then. Thanks for the info

**Comment by jaidisido** [comment]
Closing for now but let us know if you hear from the Redshift folks
