### ISSUE TITLE
Create Database - Support Passing DatabaseInput Dict

### ISSUE THREAD

**Issue by bradleyhurley** [aws/aws-sdk-pandas#2064]
It would be nice if the calls to [create_database](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/catalog/_create.py#L673) supported the additional options that are supported when creating a database via [boto](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.create_database).

AWS SDK for pandas is already passing `DatabaseInput` to the call to create the database, but is not exposing it in a way that can be extended by the caller.

The specific use case is that the `LocationUri` needs to be set on databases when Glue is configured to act as the Hive Metastore for EMR.

**Comment by malachi-constant** [comment]
Thanks @bradleyhurley, I think that's a fair ask, I'll propose a change.

**Comment by malachi-constant** [comment]
@bradleyhurley We just released last week so it will most likely be several weeks before another. As of now you'll need to pull the library into your codebase from git.
