### ISSUE TITLE
Support Athena INSERT INTO statement

### ISSUE THREAD

**Issue by sfanous** [aws/aws-sdk-pandas#2068]
**Is your idea related to a problem? Please describe.**
awswrangler supports [create_ctas_table](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.create_ctas_table.html#awswrangler.athena.create_ctas_table).

CTAS is often used in combination with `INSERT INTO` to work around the 100 partitions limitation as explained [here](https://docs.aws.amazon.com/athena/latest/ug/ctas-insert-into.html) but there are many use cases for `INSERT INTO`

The current workaround is to use [read_sql_query](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.read_sql_query.html#awswrangler.athena.read_sql_query) to execute `INSERT INTO` statements

**Describe the solution you'd like**
Expose a new API `insert_into_table(sql: str, database: str | None = None, table: str | None = None, mode: str | None = None, partitions_values: List[List[str]])`

- With `mode == append` the method would just insert new rows into the table. This is the mode to use when working around the 100 partitions limitation
- With `mode == overwrite` the method would delete all existing data (partitions + underlying S3 objects) and insert the new data into the table
- With `mode == overwrite_partitions` it is up to the user to provide the `partitions_values` that are to be deleted (Along with their underlying S3 objects) based on the user's knowledge of the data to be inserted (Usually determined by inspecting the `where` clause). If the table is not partitioned raise an exception. If `partitions_values` is `None` raise an exception

Thanks

**Comment by kukushking** [comment]
Thanks @sfanous, I think that's a fair ask. I'll have a look.

**Comment by kukushking** [comment]
Hi @sfanous I've given it a try in [feat/athena-insert-into](https://github.com/aws/aws-sdk-pandas/tree/feat/athena-insert-into). 

Ultimately what you are proposing can be achieved by a combination of `catalog.delete_all_partitions` or `catalog.delete_partitions` and `wr.s3.start_query_execution` for the insert. IMO it doesn't justify a dedicated method, but I would be interested to hear what are other use cases for this.

**Comment by sfanous** [comment]
@kukushking My thoughts on this are the following

1. The `INSERT` statement is used often and as I previously stated is required to work around the 100 partitions limitation
2. `awswrangler` provides identical functionality if the data is loaded locally onto a `dataframe` through the `s3.to_` methods. This new method would address use cases where you want to insert data using "AWS compute side" processing (i.e. Without having to load the data into a dataframe and then insert it)
3. The new method is a good example of how AWS takes care of the "undifferentiated heavy lifting". While I might be the first person to have made an official request for the API to be added, it is extremely unlikely that I'm the only one that has had the need to use `INSERT` statements while using `awswrangler`.

Ultimately, it is up to you and the `awswrangler` team to make a decision.

In any case, thanks for looking into it regardless of the final decision.

**Comment by kukushking** [comment]
@sfanous we have received another request for a similar Athena INSERT INTO feature with Iceberg support, with approximately the following API:
```
wr.athena.to_sql(df=df, database=glue_database, table=glue_table, ...)
```
I think accepting a dataframe is more in the spirit of the library, in addition it would help to avoid [limits](https://docs.aws.amazon.com/athena/latest/ug/insert-into.html#insert-into-values) of `INSERT INTO ... VALUES` and use `INSERT INTO ... SELECT`.  Would that work for your use case?

**Comment by sfanous** [comment]
@kukushking I'm a little confused.

Doesn't such a method already exist for Athena using the `s3.to_csv`, `s3.to_json`, and `s3.to_parquet` with `mode= append`?

My request was to have a new method based on "server-side" compute where the insert is based on an SQL query that's executed by the Athena engine remotely (i.e. No data is returned back to the client and therefore no dataframe being involved).

**Comment by kukushking** [comment]
Yes, but those do not support Iceberg tables unfortunately.

Regarding your original request, it's possible to achieve effectively the same result by `wr.s3.start_query_execution`  which does not involve a data frame. I do see the value add in overwrite_partition mode but other than that it would be just running an Athena query

**Comment by sfanous** [comment]
It's ok @kukushking. I implemented my own version of `insert_into` with the logic I explained earlier using a mix of `wr.catalog.delete_partitions` and `wr.athena.read_sql_query`

I was hoping something similar to my implementation would become part of awswrangler as it nicely compliments `create_ctas_table`

**Comment by kbroughton** [comment]
[sherif-fanous](https://github.com/sherif-fanous) I liked your suggestion. Could you describe your workaround with read_sql_query a bit more?  Or @kukushking  yours with
catalog.delete_partitions and wr.s3.start_query_execution ?  In particular, how to you recover the partitioning.  I find the error messaging on athena really poor and figuring it out usually requires calling AWS support cause they can see more error messages.

**Comment by dendihandian** [comment]
this is very interesting topic, but I'm still wondering can we push pandas df to iceberg table with append mode in existing iceberg table? (s3 table)
