### ISSUE TITLE
Pandas 1.5.0+ support

### ISSUE THREAD

**Issue by aeural** [aws/aws-sdk-pandas#2080]
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
Hi Team,

`pandas = "^1.2.0, <=1.5.1, !=1.5.0" # Exclusion per: https://github.com/aws/aws-sdk-pandas/issues/1678`

This issue is closed, and tagged with 2.18 release. Is there another reason why pandas is still capped at 1.5.1?

Thanks!

**Comment by jaidisido** [comment]
Hi @aeural we have had several discussions about pinning dependencies with arguments on both sides. See #805, #1983 and #1328 for examples.
In the end, we have made the decision to stop pinning dependencies. However, the change won't be implemented until the next major version (3.0) which we hope to release in the coming weeks.
