### ISSUE TITLE
Add Common Attributes to Timestream write

### ISSUE THREAD

**Issue by ddemarco96** [aws/aws-sdk-pandas#2082]
Writing to Timestream with common attributes like dimensions can make a massive cost difference (size of the attributes * number of rows). Right now, you can supply dimension columns, but that requires two things that are inefficient. 

1) adding a repetitive column to a potentially massive dataframe if it does not already exist 
2) writing these repetitive values to each record rather than once per 100-record batch

**Describe the solution you'd like**
One thing that would be great would be to specify, at the dataframe level, a dictionary of common attributes to be passed with all record batches in the frame, assuming they are all consistent.

e.g., if I have a CSV I am reading from that will all be from the same IOT device, I should be able to specify comething like
```
common_attributes = {
            'Dimensions': {‘Name’: ‘device_id’, ‘Value’: ‘12345’},
            'MeasureValueType': 'DOUBLE',
            'MeasureName': measure_name,
        }
````

The most flexible solution would be for a user to supply common_attribute columns when calling `wr.timestream.write`. When processing the dataframe, the library should groupby the specified columns and then send the batches from subgroups with the specified common attributes.
 
**Describe alternatives you've considered**
The solution I’m using on my end right now involves specifying a group id column to the dataframe and looping through using a dictionary specifying the common attributes for that group.

**Comment by jaidisido** [comment]
Thanks @ddemarco96, I agree that adding a `common_attributes` parameter to the api is warranted. However, I am not in favour of fetching it via a data frame column. The library focuses on I/O operations and we tend to avoid manipulating data frames with groupbys. The simplest implementation is to enable passing a `common_attributes` dictionary like in the boto3 [call](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/timestream-write/client/write_records.html). The user can always handle the groupby themselves if they wish.
