### ISSUE TITLE
`read_parquet` throws `NoFilesFound` when the dataset exists

### ISSUE THREAD

**Issue by tiansu-yu-idealo** [aws/aws-sdk-pandas#2083]
### Describe the bug

`wr.s3.read_parquet` will throw `NoFilesFound` error when the dataset exists but there is no matching files after the filtering (e.g. specify `last_modifed_begin` and there is no files exist after this timestamp). 

From my point of view, `NoFilesFound` error usually indicates that the dataset is missing or the machine that runs the script does not have the right access rights. When there is no file match the filtering criterion, the `read_parquet` should return an empty dataframe with a matching schema instead of throwing this error. This would be more inline with how CRON ETL pipeline works. 

### How to Reproduce

Suppose we have a dataset created a while ago, then we read it using the following command: 
```
df = wr.s3.read_parquet(<some_dataset>, last_modified_begin=datatime.now()) 
```
this will return a `NoFilesFound` error. 

### Expected behavior

Returns a df with the dataset schema but no records.

### OS

Linux / Mac

### Python version

3.8

### AWS SDK for pandas version

2.19.0

**Comment by kukushking** [comment]
Hi @tiansu-yu-idealo yes, `last_modified_begin` filters based on files last modified date so no files matching the filter means `NoFilesFound`. I agree the error message is debatable, but I don't think it would be possible to read the schema as no files match the criteria so unclear what file to read the schema from.
