### ISSUE TITLE
Support newer versions of pandas 1.x

### ISSUE THREAD

**Issue by dhatch-niv** [aws/aws-sdk-pandas#2089]
**Is your idea related to a problem? Please describe.**

The requirements for `aws-sdk-pandas` cap the pandas version at 1.5.1. I'd like to use version 1.5.2 because I use `aws-sdk-pandas` with airflow. Airflow's most recent version requires pandas 1.5.2. Can the requirements safely be updated to allow any pandas 1.x version?

**Describe the solution you'd like**

Set pandas requirement to `^1.2.0, !=1.5.0`

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
Duplicate of https://github.com/aws/aws-sdk-pandas/issues/2080

**Comment by dhatch-niv** [comment]
Hi @jaidisido . Sorry for the duplicate. I will use the 3.0 rc. Thanks for your work on this library.
