### ISSUE TITLE
Ability to fetch file.parquet name when uploading

### ISSUE THREAD

**Issue by matthewyakubiw** [aws/aws-sdk-pandas#2114]
Given the following code:
```
df.to_parquet(
       path=s3_endpoint,
       engine="pyarrow",
       compression="snappy",
       partition_cols=partitions
 )
```
How can I reasonably extract the output filename in S3? It generates a random string `5f622c660f844ab39e84a6fed6cdb868-0.parquet` - I would love to store this file name in my log.

Thanks for your help,
Matt

**Comment by jaidisido** [comment]
@matthewyakubiw I think there might be a little confusion here. Your example references `df.to_parquet` which is a native pandas API. Our library (`awswrangler`) exposes its own [API](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html#awswrangler.s3.to_parquet) which is used differently:
```
wr.s3.to_parquet(df=df, path="s3://...")
```
That API will indeed return a dictionary with the list of parquet S3 objects.

**Comment by matthewyakubiw** [comment]
Ah thanks so much...I totally missed that. Cheers.
