### ISSUE TITLE
Allow aws.redshift.copy to work with an Iterator over DataFrames

### ISSUE THREAD

**Issue by WillAyd** [aws/aws-sdk-pandas#2116]
**Is your idea related to a problem? Please describe.**
`pandas.read_sql` has `pd.DataFrame | Iterator[pd.DataFrame]` as its return type. The latter is useful in conjunction with the `chunksize` argument to prevent having to read an entire DataFrame into memory. awswrangler won't let you forward the result when specifying `chunksize` to the aws.redshift.copy function because it explicitly requires a DataFrame

**Describe the solution you'd like**
Allow the first argument to `aws.redshift.copy` to accept `Iterator[pd.DataFrame]`. This can roughly be handled as:

```python
if isinstance(df, pd.DataFrame):
    copy(path)
else:
    for index, chunk in enumerate(df):
        wr.s3.write_objects(f"{path}/{index}.parquet")
        copy_from_files(path)
        wr.s3.delete_objects(path)
```

It can be a little wonky that the first argument to `aws.redshift.copy` is named `df` when it could accept `Iterator[pd.DataFrame]`, but I think API breakage from renaming that wouldn't be too bad compared to the benefit of this

**Comment by jaidisido** [comment]
Thanks for the suggestion but I think this would make the API unnecessarily complex when it can be easily handled by the user in their code. For example:
```
for df in wr.redshift.read_sql(...., chunked=True):
     # Do smt transforming the df and then write back
     wr.redshift.copy(df...)
```
I believe it's preferable to limit the API to one thing that they do well

**Comment by jaidisido** [comment]
The [copy](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.redshift.copy.html#awswrangler.redshift.copy) API has a `commit_transaction` set to `True` by default. Setting it to `False` would enable the user to control when a transaction is committed. At that point they can wrap the multiple copy calls within a single transaction, only committing it if the whole operation succeeds, thus ensuring atomicity.

**Comment by WillAyd** [comment]
Ah cool. I see that was added this month so there's some potential there. How do you actually commit things then though?

I don't think the loop would know how much is left in the iterator until is exhausted. Is there another function you can use to actually run the commit?

**Comment by jaidisido** [comment]
All redshift APIs take a redshift connection argument which can be committed at the end:
```python
con_redshift = wr.redshift.connect("aws-sdk-pandas-redshift")

for df in wr.redshift.read_sql(con=con_redshift, chunked=True...):
     # Do smt transforming the df and then write back
     wr.redshift.copy(df=df, con_con_redshift, commit_transaction=False...)
con_redshift.commit()
con_redshift.close()
```
