### ISSUE TITLE
`date` type columns have `object` data type in df returned by athena.read_sql_query

### ISSUE THREAD

**Issue by sfanous** [aws/aws-sdk-pandas#2124]
### Describe the bug

Columns of type `date` are mapped to the `object` datatype whereas columns of type `timestamp` are correctly mapped to `datetime64[ns]` in the dataframe returned by `athena.read_sql_query`

I did do some tracing and interestingly the dataframe returned by `s3.read_csv` [here](https://github.com/aws/aws-sdk-pandas/blob/f8d419bb3e7cbd5327bb3c772e74e71ecc6350fa/awswrangler/athena/_read.py#L172) has the correct/expected datatype `datetime64[ns]` for `date` columns, but then following the invocation of the function `_fix_csv_types` [here](https://github.com/aws/aws-sdk-pandas/blob/f8d419bb3e7cbd5327bb3c772e74e71ecc6350fa/awswrangler/athena/_read.py#L188) the dataframe has the datatype `object`.

### How to Reproduce

```python
query = '''
select timestamp_column, date_column
from table;'''

query_results = wr.athena.read_sql_query(
                sql=query,
                database=database_name,
                ctas_approach=False,
            )

print(query_results.dtypes)
```

```
timestamp_column                   datetime64[ns]
date_column                                object
dtype: object
```

### Expected behavior

Columns of type `date` or `timestamp` should be mapped to `datetime64[ns]` in the dataframe returned by `athena.read_sql_query`

### OS

macOS 13.2.1

### Python version

3.9.16

### AWS SDK for pandas version

2.19.0

**Comment by kukushking** [comment]
Hi @sfanous does your date column contain empty values / `None`? If so the column type must be object, because `datetime64` can't hold `None`. It should be fine if it's `NaT` though. I've added a test case below to demonstrate:

https://github.com/aws/aws-sdk-pandas/compare/fix/athena-date-csv

**Comment by kukushking** [comment]
Can you share pip freeze, please? I'm interested in Pandas version in particular

**Comment by kukushking** [comment]
Ah, I see. The issue is that Athena's date type effectively [maps](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/_data_types.py#L366) to pandas object with date values (since there is no dedicated date type in pandas). When you provide Athena destination type, the original data is casted, and it's difficult to trace it back to `datetime64`.

**Comment by sfanous** [comment]
> Basically, if you would want to keep the original types, do not pass `dtypes` when writing the file as it overrides them.

Not following you here. `read_sql_query` doesn't take a dtypes parameter. If it did, it'd actually solve the problem as it'd allow the caller to dictate the dataframe datatypes.

**Comment by kukushking** [comment]
[to_parquet](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/s3/_write_parquet.py#L231) does, and this is what registers the table in Glue, setting the column to `date`. An alternative is to read the data from S3 using `read_parquet` which will preserve original types in the file but Athena will read and cast types according to the schema in Glue.

**Comment by sfanous** [comment]
> Ah, I see. The issue is that Athena's date type effectively [maps](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/_data_types.py#L366) to pandas object with date values (since there is no dedicated date type in pandas). When you provide Athena destination type, the original data is [casted](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/s3/_write_parquet.py#L177), and it's difficult to trace it back to datetime64 after.

Then does it make sense to map Athena `date` to `datetime64` in this function?

```python
if dtype in ("date", "timestamp", "timestamp with time zone"):
        return "datetime64"
```

This would give a better user experience.

**Comment by sfanous** [comment]
> It looks like since the original data is datetime64, the most direct solution would be to use the timestamp column in Glue instead of date - is that possible in your case?

Not really but that's ok since I've wrapped `read_sql_query` into a function that takes a `dtype` like parameter and casts the returned dataframe columns. Basicly looks like this

```python
query_results = wr.athena.read_sql_query(
    sql=query,
    database=f'{database_name}',
    ctas_approach=False,
)

if dtype:
    query_results = query_results.astype(dtype)

return query_results
```

> We also do want to be able to distinguish between the three cases which would not be possible if they all map to datetime64. It would also be a breaking change for the users who use object type with date values.

To me it's a question of whether this is the right/expected behavior or not.

Perhaps the right thing to do here is to have `read_sql_query` accept a `dtype` parameter. This wouldn't be a breaking change since by default `date` columns would be returned as `object` and gives others the ability to cast columns to their liking. So something similar to what I explained earlier in this post.

**Comment by kukushking** [comment]
If the source data is `datetime64`, Glue schema should match that with a `timestamp` (not the `date`) field, and you should get expected `datetime64` when reading the data back via Athena. 
 
I agree `dtypes` could be a solution to escape / override casting types. Would you shed some light on the logic that writes the original files / created the schema in your use case, please? Or was it created manually / outside of your control?

**Comment by sfanous** [comment]
The source data is an ISO formatted `date` column `YYYY-mm-dd` that is being mapped to the Glue/Athena type `date` not `timestamp`.

I have no control over the logic that creates the schema and just have to work with it.

**Comment by jaidisido** [comment]
If the only thing a `dtypes` argument will do is convert the data frame types as a last step in the API call then I would just leave that to the user

**Comment by jaidisido** [comment]
As you mention, the `dtypes` argument is not explicitly exposed in the `s3.read_csv` API, it just happens to be available via the `pandas_kwargs` keyword arguments. Replicating the same approach in `athena.read_sql_query` would not be wise as read_csv is just one way to read via Athena (reading via parquet is another and other formats like orc could be supported in the future), so `pandas_kwargs` wouldn't be uniform in that case

**Comment by sfanous** [comment]
Good point @jaidisido.

Feel free to close the issue then and thanks for the support.
