### ISSUE TITLE
bucketing info parameter does not accept camel cased column names

### ISSUE THREAD

**Issue by ashishkumarazuga** [aws/aws-sdk-pandas#2153]
### Describe the bug

The `awswrangler.s3.to_parquet` takes the name of the column to bucket the data. And fails if a column name is camel case or contains caps.

My assumption is, somewhere before the bucketing step, we are doing a to_lower operation, and then applying group by, which means we should also apply the to_lower operation to the bucketing column name.

### How to Reproduce

```
1. Pass a df with came cased column names.
2. Pass a camel case column name to bucketing_info.
```

### Expected behavior

Expected behaviour should be to handle the bucketing column name irrespective of camel case.

### OS

linux

### Python version

python3.8

### AWS SDK for pandas version

2.20.1

**Comment by kukushking** [comment]
Hi @ashishkumarazuga the columns are [sanitized](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/s3/_write_parquet.py#L566) to respect Athena standards. I agree `bucketing_info` should also be sanitized (just like the `partition_cols`), we'll have that fixed. Thanks!

**Comment by kukushking** [comment]
You are welcome @ashishkumarazuga !
