### ISSUE TITLE
Test case for wr.athena.read_sql_query failing with empty DataFrame  Body

### ISSUE THREAD

**Issue by tomascortes** [aws/aws-sdk-pandas#2166]
Hi there,

"I am trying to create unit tests for my code, and I am attempting to replicate the functionality of the test_athena_read_sql_ctas_bucketing test (located at https://github.com/aws/aws-sdk-pandas/blob/main/tests/test_athena.py#L126). Specifically, I am trying to use the wr.athena.read_sql_query function in my tests. Any guidance on how to do this successfully would be greatly appreciated. Thank you!"

the minimal example i can set is this: 

``` python
BUCKET_EMPTY = "my_bucket"
BUCKET_ATHENA = "my_athena_bucket"
REGION = "us-east-1"
DATABASE_NAME = "test_db"
TABLE_NAME = "test_table"


@pytest.fixture(scope="function")
def aws_context():
    with patch.dict(os.environ, {"AWS_DEFAULT_REGION": REGION}):
        with moto.mock_s3():
            with moto.mock_athena():
                with moto.mock_glue():
                    s3_client = boto3.client("s3", region_name=REGION)
                    s3_client.create_bucket(Bucket=BUCKET_EMPTY,)
                    s3_client.create_bucket(Bucket=BUCKET_ATHENA,)
                    wr.catalog.create_database(name=DATABASE_NAME)
                    yield True


def test_athena_read_sql_ctas_bucketing(aws_context):
    df = pd.DataFrame({"c0": [0, 1], "c1": ["foo", "bar"]})
    path = f"s3://{BUCKET_EMPTY}/database/{TABLE_NAME}"
    path2 = f"s3://{BUCKET_ATHENA}"
    wr.s3.to_parquet(
        df=df,
        path=path,
        dataset=True,
        database=DATABASE_NAME,
        table=TABLE_NAME,
    )
    df_no_ctas = wr.athena.read_sql_query(
        sql=f"SELECT * FROM {TABLE_NAME}",
        ctas_approach=False,
        database=DATABASE_NAME,
        s3_output=path2,
        keep_files=False
    )
    print(df_no_ctas)
    assert df_no_ctas.shape[0] == 2
```

However, when I run this test case, it fails because df_no_ctas is an empty DataFrame. I suspect that this might be related to the s3_output parameter, because when i remove it I receive `InvalidClientTokenId` but i'm not entirely sure

I apologize if this is a very basic question. I've been trying to solve it for a while now, but I can't seem to figure out why it's not working.

Thank you!

**Comment by jaidisido** [comment]
From the moto Athena [docs](http://docs.getmoto.org/en/latest/docs/services/athena.html):
> Queries are not executed by Moto, so this call will always return 0 rows by default.

This is not surprising as moto is not able to mock the Presto/Trino engine that the Athena uses under the hood. This is also why Athena is not in our own moto tests.

Their docs do mention:
> You can use a dedicated API to override this, by configuring a queue of expected results.
and provide an example. So you can give it a shot, but I cannot vouch for it as I haven't tested it.
