### ISSUE TITLE
Cannot insert records in table having calculated columns

### ISSUE THREAD

**Issue by sohailanjum99** [aws/aws-sdk-pandas#2170]
### Describe the bug
import awswrangler as wr

con = wr.mysql.connect('MysqlRDS')
wr.mysql.to_sql(    df=df_inserted,    table="tablename",    schema="dbname",    con=con  )

I have a table in which there are three fields, connectedat , disconnectedat and elapsedseconds , all are type of bigint,  
connectedat and disconnectedat  store the linux epoch or unix timestamp. i.e(  1680520084 for Monday, April 3, 2023 11:08:04 UTC)
elapsedseconds  is calculated field as disconnectedat  - connectedat , 

in above method when I provided the elapsedseconds as None, in pandas dataframe (df_inserted) I got the below error
(3105, "The value specified for generated column 'elapsedseconds' in table 'tablename' is not allowed.")

When the removed the  elapsedseconds column in pandas dataframe (df_inserted) I got the below error
(1136, "Column count doesn't match value count at row 1")

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

Should Insert the records in table which have calculated fields. 

### Your project

aws /aws-sdk-pandas

### OS

Window

### Python version

3.7

### AWS SDK for pandas version

2.20.0

### Additional context

Name: awswrangler
Version: 2.20.0
Summary: Pandas on AWS.
Home-page: https://aws-sdk-pandas.readthedocs.io/
Author: Amazon Web Services
Author-email:
License: Apache-2.0
Location: c:\users\sohail.a\appdata\roaming\python\python39\site-packages
Requires: backoff, boto3, botocore, gremlinpython, jsonpath-ng, numpy, openpyxl, opensearch-py, pandas, pg8000, progressbar2, pyarrow, pymysql, redshift-connector, requests-aws4auth
Required-by:

**Comment by LeonLuttenberger** [comment]
Hey,

Have you tried passing a frame which doesn't have the calculated column at all? I was able to get it working that way:
```python
create_table_sql = (
        f"CREATE TABLE test.{mysql_table} (c1 INT, c2 INT GENERATED ALWAYS AS (c1 + 1) STORED);"
    )
    with mysql_con.cursor() as cursor:
        cursor.execute(create_table_sql)
        mysql_con.commit()

    df = pd.DataFrame({"c1": [1, 2]})
    schema = "test"

    wr.mysql.to_sql(df=df, con=mysql_con, schema=schema, table=mysql_table, mode="append", use_column_names=True)

    df_output = wr.mysql.read_sql_table(table=mysql_table, con=mysql_con, schema=schema)

    df["c2"] = df["c1"] + 1
    df["c1"] = df["c1"].astype("Int64")
    df["c2"] = df["c2"].astype("Int64")

    assert df.equals(df_output)
```

Let me know if this works for you.

Best regards,
Leon

**Comment by sohailanjum99** [comment]
Using parameter  use_column_names=True worked for me . Thanks

However, if I have to update only specific columns in table, for example a data frame which only include primary key(SessionID) , disconnectat( int64), clientintiateddisconnect{bool) columns.

the available modes [ upsert_duplicate_key, upsert_replace_into ] did not worked for only updating the records, It causes updated the records  and inserting the records with null values for columns not mentioned in data frame , the mode upsert_distinct even did nothing for this scenario.

There should be a separate mode for update_only which should only perform updates.
Along with this mode there should be update_keys parameter of list type which should be mandatory for this mode.

**Comment by LeonLuttenberger** [comment]
Hey,

I was able to update only the columns I had in the DataFrame with the following code:

```python
def test_update_table_with_calculated_field(mysql_table: str, mysql_con: "Connection[Cursor]") -> None:
    create_table_sql = (
        f"CREATE TABLE test.{mysql_table} ("
        "    c0 VARCHAR(100) PRIMARY KEY"
        "  , c1 VARCHAR(100)"
        "  , c2 INT"
        "  , c3 INT GENERATED ALWAYS AS (c2 + 1) STORED"
        ");"
    )
    with mysql_con.cursor() as cursor:
        cursor.execute(create_table_sql)
        mysql_con.commit()

    df = pd.DataFrame({"c0": ["a", "b"], "c1": ["foo", "bar"], "c2": [1, 2]})
    schema = "test"

    wr.mysql.to_sql(df=df, con=mysql_con, schema=schema, table=mysql_table, mode="append", use_column_names=True)

    df2 = pd.DataFrame({"c0": ["c", "b"], "c2": [5, 10]})
    wr.mysql.to_sql(
        df=df2, con=mysql_con, schema=schema, table=mysql_table, mode="upsert_duplicate_key", use_column_names=True
    )

    df_output = wr.mysql.read_sql_table(table=mysql_table, con=mysql_con, schema=schema)
    df_expected = pd.DataFrame({"c0": ["a", "b", "c"], "c1": ["foo", "bar", None], "c2": [1, 10, 5]})

    df_expected["c3"] = df_expected["c2"] + 1
    df_expected["c0"] = df_expected["c0"].astype("string")
    df_expected["c1"] = df_expected["c1"].astype("string")
    df_expected["c2"] = df_expected["c2"].astype("Int64")
    df_expected["c3"] = df_expected["c3"].astype("Int64")

    assert df_expected.equals(df_output)
```

In the example above, the frame `df2` does not contain column `c1`. However, despite this, the existing values of `c1` are not overridden with `None`.

Let me know if I'm missing something.

Best regards,
Leon

**Comment by sohailanjum99** [comment]
Your implementation worked for me,

**Thank** you so much for explaining the details, Really **appreciate** it.
