### ISSUE TITLE
Add support for Glue Table (Schema) Comparison

### ISSUE THREAD

**Issue by W7T2A** [aws/aws-sdk-pandas#2179]
**Is your feature request related to a problem? Please describe.**
As a user of aws-sdk-pandas I would like to be able to use the api so that I can query a schema comparison between multiple versions of a glue table. The output should be a pandas dataframe containing all changes of the schema versions as default when no other format is specified.

**Describe the solution you'd like**
Extending the current Glue Catalog API to get more detailed information about the glue tables e.g. version(s) of the table and do a comparison of two versions of a glue table.

It would be nice if there is a programmatic way of getting the same user experience doing a schema comparison inside aws consolue ui in a more programmatic way.

Also according to this blog post https://aws.amazon.com/blogs/big-data/identify-source-schema-changes-using-aws-glue/ this feature would make life more easier cause you can use this as a kind of native ootb experience inside of an glue job or glue notebook.

**Comment by LeonLuttenberger** [comment]
Hey,

Thanks for the suggestion. I will discuss this with the rest of the team and decide what the next steps should be.

Best regards,
Leon
