### ISSUE TITLE
Python 3.10 Layer support

### ISSUE THREAD

**Issue by HAK-CODE** [aws/aws-sdk-pandas#2209]
Add support for python 3.10 layer support.

**Comment by malachi-constant** [comment]
Thanks @HAK-CODE we are working on this actively.

**Comment by LeonLuttenberger** [comment]
Hey,

We have published the layers with support for Python 3.10. You can find a list of the ARNs [here](https://aws-sdk-pandas.readthedocs.io/en/latest/layers.html) for each region/architecture here.

They're not showing up as managed layers in the AWS Lambda console yet, but hopefully they will by the end of the week. In the meantime, you can just type in the Layer ARNs directly.

Best regards,
Leon
