### ISSUE TITLE
Add additional information related to boto3_session being an unsupported arg for distributed EngineEnum.RAY mode

### ISSUE THREAD

**Issue by brevityinmotion** [aws/aws-sdk-pandas#2213]
Hello,

It is a common use case to pass boto3 sessions into data queries, in my particular situation, it was the Athena read_sql function. It seems like the default functionality is configured as Ray if it is available which breaks any workflows utilizing the session argument. The error message is at:
https://github.com/aws/aws-sdk-pandas/blob/7939b0ea15a1094f5653812050bbfba85e46380f/awswrangler/_utils.py#L198 which does not provide user clarity on how to overcome and resolve the issue. I could not find any documentation to resolve this outside of reading the code.

Can we consider the following:
1. Add more information to the error message to the user on how to overcome the lack of support. For example, adding "Run wr.engine.set('python') to switch the engine from distributed mode to an engine type that supports the boto3_session argument."
2. Additionally, could it be investigated to fall-back automatically to the python engine when the boto3_session argument is passed and potentially issue a warning message on how they can explicitly configure the engine to 'python' to clear the warning in the future?
3. Add a section of documentation for configuring the various engine modes.

Thank you!

**Comment by kukushking** [comment]
Hi @brevityinmotion, thanks for opening this! Yes I agree error message / docs could be improved - we will add info into the docs. 

Regarding point 2 - I'm afraid falling back to python engine would be too dangerous considering ray engine is used to process large amounts of data which may not be possible using python engine. Explicit failure in this scenario was a conscious design decision, you can read more about it in [ADR](https://aws-sdk-pandas.readthedocs.io/en/latest/adr/0002-handling-unsupported-arguments-in-distributed-mode.html)

**Comment by LeoUfimtsev** [comment]
@kukushking is there any way to prevent AWS Wrangler from automatically activating Ray worker?

I install AWS Gluon, which includes Ray. But AWS Wrangler automatically activates ray worked without my consent to do so and fails due to custom boto3 session.

The only work around I could find so far is to switch engine over to python after worker started, which is not ideal.

```
import awswrangler as wr
wr.engine.set("python")    
wr.memory_format.set("pandas") 
```

**Comment by CrashLaker** [comment]
hi all,

facing the same error.
I'm willing to use ray engine but with another session/credentials.

is there any current workaround in place?

ty,c.

**Comment by kukushking** [comment]
Hi  folks
@CrashLaker At the moment it's not possible to use ray engine and pass a custom session/credentials. 
@LeoUfimtsev Yes that is correct, in 3.2 you will be able to switch the engine before ray starts up. The initialisation is delayed to the first distributed call.

**Comment by LeoUfimtsev** [comment]
Is there any way to pass initialization logic to the ray engine?
E.g. a function that is used to generate a session?

my use case is to run this on a Linux box that retrieves data from one aws account, does some etl and then uploads it to another. I use custom boto sessions for that.
