### ISSUE TITLE
Support EMR Serverless

### ISSUE THREAD

**Issue by aarana95** [aws/aws-sdk-pandas#2242]
**Is your feature request related to a problem? Please describe.**
I am thinking of switching from using boto3 to using awswrangler to manage EMR, but we have clusters with EMR Serverless and as far as I can see awswrangler does not support it.

**Describe the solution you'd like**
EMR Serverless support.

**Describe alternatives you've considered**

**Additional context**

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by kukushking** [comment]
Thanks @aarana95 for opening this, we will add EMR Serverless to our roadmap!

**Comment by kukushking** [comment]
Merged. Will be available in the next release.
