### ISSUE TITLE
AWSSDKPandas-Python39, layer version:6, python3.9 columns_comments error

### ISSUE THREAD

**Issue by daniloaluiz** [aws/aws-sdk-pandas#2253]
### Describe the bug

When trying to use the arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:6 layer that currently defaults to the lambda function, I came across the following error in Cloud Watch:
[ERROR] TypeError: got an unexpected keyword argument 'columns_comments'
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 38, in lambda_handler
wr.s3.to_parquet(
File "/opt/python/awswrangler/_config.py", line 679, in wrapper
args: Dict[str, Any] = signature.bind_partial(*args_raw, **kwargs).arguments
File "/var/lang/lib/python3.9/inspect.py", line 3052, in bind_partial
return self._bind(args, kwargs, partial=True)
File "/var/lang/lib/python3.9/inspect.py", line 3034, in _bind
raiseTypeError(

For some reason columns_comments was not contemplated in version 6, and the way I managed to solve the problem, after checking my parameters countless times, was to move to version 5 and then it worked normally

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### OS

x86_64

### Python version

python3.9

### AWS SDK for pandas version

AWSSDKPandas-Python39

**Comment by LeonLuttenberger** [comment]
Hey Danilo,

One of the changes we made as part of our `3.0.0` release was to group some of the Glue parameters together. The [to_parquet](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.s3.to_parquet.html#awswrangler.s3.to_parquet) function now accepts a `glue_table_settings` parameter -- a typed dictionary where one of the members is `column_comments`.

As such, you can still use `column_comments` with the following code:
```python
wr.s3.to_parquet(
    ...
    glue_table_settings=wr.typing.GlueTableSettings(
        column_comments={...}
    )
)
```
or
```python
wr.s3.to_parquet(
    ...
    glue_table_settings={
        "column_comments": {...}
    }
)
```

Best regards,
Leon

**Comment by daniloaluiz** [comment]
Thanks @LeonLuttenberger I'm going to use it that way
