### ISSUE TITLE
Cannot set TimeUnit to MICROSECONDS

### ISSUE THREAD

**Issue by gegnew** [aws/aws-sdk-pandas#2261]
### Describe the bug

Hello again, apologies for being annoying, but the response to the previous bug doesn't really answer the question. I'll do my best to explain/understand:

> `If time_col column is supplied, it must be of type timestamp. TimeUnit is set to MILLISECONDS by default.`

Okay, there's two pieces here: "time_col must be of type timestamp" and "TimeUnit is MILLISECONDS by default". My dataframe has a column `timestamp`, which is a `pandas.Timestamp` like `Timestamp('2023-05-08 19:34:22.711911201')`, so that's good. Plenty of precision there. And TimeUnit is set to MILLISECONDS by default, but how to change it? There's no mention of this in the docs.

> So by specifying a time column, the TimeUnit is set to Milliseconds. 

Alright, so am I stuck with milliseconds?

> This is because we do not handle datetime conversion in the method

Except you do, in `_format_timestamp`, where you `str(round(timestamp.timestamp() * 1_000))`, and this is exactly the issue.

> and expect the user to pass a timestamp type column which is set to Milliseconds.

So we are forced to use milliseconds? Despite Timestream's nanosecond precision, we're forced to use millisecond precision if we use `awswrangler`?

### How to Reproduce

https://github.com/aws/aws-sdk-pandas/issues/2260

### OS

Linux

### Python version

3.10

### AWS SDK for pandas version

3.0.0

**Comment by gegnew** [comment]
Thanks for the response, I really do appreciate it.

Is there any reason to not make `MICROSECONDS` the default? 

Or, since the code already converts timestamp `int`s or `datetimes` to milliseconds and sets `MILLISECONDS`, it seems pretty manageable to handle milliseconds. The datetime object's precision is, of course, a great reason to not support nanoseconds, but that doesn't seem to be a good reason to limit the precision even further.

**Comment by jaidisido** [comment]
`MILLISECONDS` is the [default](https://docs.aws.amazon.com/timestream/latest/developerguide/API_Record.html#timestream-Type-Record-TimeUnit) in Timestream so we are following that. I have opened #2263 which enables passing `time_unit`. We still have the NANOSECONDS issue however so will need to discuss that with the team
