### ISSUE TITLE
Support querying Hudi datasets with Amazon Athena

### ISSUE THREAD

**Issue by jaidisido** [aws/aws-sdk-pandas#2269]
Add APIs in the awswrangler Athena module to support querying Hudi datasets. It would be similar to the work achieved with Athena Iceberg
https://docs.aws.amazon.com/athena/latest/ug/querying-hudi.html

**Comment by kukushking** [comment]
@apopata-aws Can you explain your use case in more detail, please? It is already possible to read Hudi data using `wr.athena.read_sql_query`. In terms of write support Hudi datasets are typically written using Spark which wrangler does intend to support. We have also discussed creating hudi tables with the team internally but it would not be useful on it's own.
