### ISSUE TITLE
timestream 'list_tables' method typo in 'NextToken'

### ISSUE THREAD

**Issue by SukruHan** [aws/aws-sdk-pandas#2274]
### Describe the bug

Hi,

The code in the package;

![image](https://github.com/aws/aws-sdk-pandas/assets/49291771/26fc89b1-a9a3-4874-9fc3-023a6f65cd30)

'nextToken' string should be searched as 'NextToken' in response in while loop. (In the json response there is no key such as 'nextToken', but there is a key such as 'NextToken')
Otherwise it does not return more than 20 table names. 

So code should be like following;
![image](https://github.com/aws/aws-sdk-pandas/assets/49291771/5fd3eb83-d5db-4237-baf6-bedc752e2d81)

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
Just try to use 'list_tables' method in a timestream database where there are more than 20 tables in a database. You will be able to see that method won't be able to list more than 20 table since 'NextToken' string is written as 'nextToken'.

Python 3.10, awswrangler 3.0.0

### OS

Windows

### Python version

3.10

### AWS SDK for pandas version

3.0.0

**Comment by jaidisido** [comment]
Thank you for raising this @SukruHan, it's merged
