### ISSUE TITLE
Importing awswrangler spins up a ray cluster

### ISSUE THREAD

**Issue by henridwyer** [aws/aws-sdk-pandas#2279]
### Describe the bug

When I import awswrangler, a ray cluster gets created. I just want to import awswrangler.

### How to Reproduce

`import awswrangler`

Then see logs indicating a ray cluster is created, and see several new python processes.

### Expected behavior

It would be better if I could import awswrangler without paying the huge cost in RAM, cpu and time. If a ray cluster is needed, it should be spun up at that time and not immediately

### OS

Mac

### Python version

3.9

### AWS SDK for pandas version

3.0.0

**Comment by jaidisido** [comment]
@henridwyer, I believe there is some confusion here. 

First, a Ray runtime is only initialised if you have installed Ray as an optional dependency (i.e. `pip install awswrangler[modin,ray]`). By default it should not be there. We assume that if a user has decided to install Ray then they intend to use it, so we do the heavy lifting of initialising the runtime for them. This is a common approach used by other libraries such as Modin for example.

Assuming you did intend to have Ray installed, by default a local Ray runtime is initialised, meaning your local computer is used (local RAM and CPUs), not a cluster of workers in the cloud, so I am not sure what you mean by "paying the huge cost in RAM". You are only charged if you decide to create cluster in the cloud (e.g. [EC2](https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/035%20-%20Distributing%20Calls%20on%20Ray%20Remote%20Cluster.html) or [Glue for Ray](https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/035%20-%20Distributing%20Calls%20on%20Ray%20Remote%20Cluster.html)).

**Comment by SukruHan** [comment]
@henridwyer In the link: https://aws-sdk-pandas.readthedocs.io/en/stable/install.html you can see the detailed explanation about ray and modin installation. In the default modin and ray is not enabled. 

![image](https://github.com/aws/aws-sdk-pandas/assets/49291771/6bfb9d93-7d43-475f-ba9c-6297ede1e3e6)

**Comment by adgaultier** [comment]
I have ray installed (not as a awswrangler dependency).
I can get random ray gcs error after 60 sec 
` gcs_rpc_client.h:533: Failed to connect to GCS within 60 seconds. GCS may have been killed. It's either GCS is terminated by `ray stop` or is killed unexpectedly. If it is killed unexpectedly, see the log file gcs_server.out. https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure. The program will terminate.`
which causes my program to crash
I think it's not the best approach to infer that  user needs to spin up a ray cluster when importing awswrangler? 
Or can it be deactivated via an env var?

**Comment by jaidisido** [comment]
A user can always initialise the cluster before importing awswrangler by running their own `ray.init` command. We don't encourage that behaviour however because specific [arguments](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/distributed/ray/_core.py#L177) must be supplied to ray.init for it to work properly with Modin and awswrangler, which is why we do it on their behalf the same way Modin does. The idea is to abstract most of the interface so that users don't have to understand the intricacies of ray to run their awswrangler code at scale. Advanced users have the choice of overriding this if they wish by configuring the ray runtime before importing the package.

Side note, I would be careful with the lingo here. No **cluster** is spun up by default, only the local host is used as a Ray runtime. The user would have to create their own Ray cluster (of EC2s for example) and register with it.

**Comment by henridwyer** [comment]
@jaidisido  I'm arguing that users should really be given the control about whether awswrangler should spin up a ray cluster, or at the very least it should only happen when awswrangler needs it.

Is it not a valid use case to have ray installed but use awswrangler to do some things that don't need ray - such as run queries in athena?

**Comment by jaidisido** [comment]
If Ray/Modin are installed, even running Athena queries will use Ray to read the results in parallel from S3. Specifically, all APIs listed [here](https://aws-sdk-pandas.readthedocs.io/en/stable/scale.html#supported-apis) will use Ray under the hood, which as you can see include the most important APIs in awswrangler. So no, there is no valid use case for both installing Ray and not using it. The whole point of installing Ray with awswrangler is to run the existing APIs at scale. If a user does not want to use Ray with awswrangler, they should simply not install it in the same environment, which is the default behaviour.

As a side note, even if we were to revert this behaviour on our end, the simple fact that Modin is doing the same (i.e. initialise Ray if it's installed) will mean that it will be done anyways. So we prefer to at least be in control of that process on our end.

**Comment by henridwyer** [comment]
Modin is actually a great example: you can in fact import it without it creating anything with ray (until necessary!).
```
import modin.pandas as pd
# Nothing happened yet
pd.read_csv("s3://my/data.csv")
# Now ray is started
```

The way modin it works is quite reasonable: while by default it will spin up ray (as described in my example), you have the option of not doing it as so:
```
import modin.config
modin.config.Engine.put('Python')
import modin.pandas as pd
pd.read_csv("s3://my/data.csv")
# No ray ever started
```

To be clear, I think ray support is awesome, and I'm excited to leverage it for some usecases.

However, it's really not ideal that just importing this package have such a huge side effect - at the very least the moment when ray is started should be moved to when it's actually necessary. Furthermore, giving users some control over whether to use it or not is reasonable

**Comment by jaidisido** [comment]
If the ask is simply to not use the existing APIs with Ray, then we offer a similar level of control to the example you mentioned with Modin. By running the below:
```
wr.engine.set("python")
wr.memory_format("pandas")
```
awswrangler APIs won't leverage Ray and revert to the default, non-distributed implementation.

Delaying the Ray initialisation to the first API call can be considered. But I still don't see the valid use case for not using/initialising Ray by default when it's installed.

**Comment by jaidisido** [comment]
The suggestion of delaying Ray initialisation to the first distributed API call was merged in #2285. The PR also includes [clarifications](https://aws-sdk-pandas.readthedocs.io/en/latest/scale.html) on how to switch between engines. The changes will be available in the next release.

**Comment by henridwyer** [comment]
Awesome! Thanks for the quick implementation

**Comment by LeoUfimtsev** [comment]
Thank you fix/implementation.

As a note, I use  AWS Gluon, which pulls in Ray as a dependency. So I ran into the problem that all of a sudden AWS Wrangler was spinning up Ray clusters just because I had it as an import in one of my files even if my workflow didn't actually use aws wrangler functionality. Also, using Ray broke our use case which passed in a custom RedShift connection & boto3 session.

I think going down the distributed route makes sense, although I think the user should be given a bit more control functions on when a Ray cluster is initialized. Just having it installed doesn't mean you want to fire up a Ray cluster every time.

AWS Wrangler is being used for Science use cases here, not just pure DE workflows :).

**Comment by Asseel-Naji** [comment]
I strongly second the opinion that it has to be initialized manually.
My case was me just using poetry add awswrangler[all] which pull that dependency as well. And while I agree that this might not be the best thing to do from my end I never expected this much unintended behaviour.

**Comment by bouachalazhar** [comment]
> If the ask is simply to not use the existing APIs with Ray, then we offer a similar level of control to the example you mentioned with Modin. By running the below:
> 
> ```
> wr.engine.set("python")
> wr.memory_format.set("pandas")
> ```
> 
> awswrangler APIs won't leverage Ray or Modin and revert to the default, non-distributed implementation with native python and pandas instead.
> 
> Delaying the Ray initialisation to the first API call can be considered. But I still don't see the valid use case for not using/initialising Ray by default when it's installed.

Firstly, I installed awswrangler without ray but I already ray installed yet before just for finetune hyperparameters model. Now when I just call 

```
nb_folder = wr.s3.list_directories(path)
nb_files = wr.s3.list_objects(path)
```
Ray instance is created but they give me the same number `wr.s3.list_directories()` works like `wr.s3.list_objects()`. It's really insane

**Comment by esiebert** [comment]
Is it possible to reopen this issue? It was closed with insufficient explanation on why this unexpected behaviour is even remotely beneficial to users. 

Just as the behaviour, the workaround and its effects are unclear and would require code comments and linking this issue.
