### ISSUE TITLE
Lambda Managed Layer - China regions support

### ISSUE THREAD

**Issue by guanlinz** [aws/aws-sdk-pandas#2289]
As for now, only the AWS Commercial regions are supported, the China and GovCloud aren't supported yet.

Is there any plan to launch in China regions?

**Comment by jaidisido** [comment]
Thanks for opening this @guanlinz, definitely something for us to consider in the next release

**Comment by kukushking** [comment]
Hi @guanlinz the layers are  nowavailable in `cn-north-1` and `cn-northwest-1`. Full arn list available [here](https://aws-sdk-pandas.readthedocs.io/en/latest/layers.html).
