### ISSUE TITLE
read_parquet() categories argument gone

### ISSUE THREAD

**Issue by matthewyakubiw** [aws/aws-sdk-pandas#2295]
Hey,

Just wondering why read_parquet no longer has a `categories` argument. I can't find any mention if it in change notes either. Thanks!

**Comment by jaidisido** [comment]
Hi @matthewyakubiw, starting version 3.0 of awswrangler all pyarrow arguments (e.g. safe, categories...) can be supplied directly via the `pyarrow_additional_kwargs` argument. The decision was made to avoid overloading our APIs and to group together similar arguments:
```
wr.s3.read_parquet(..., pyarrow_additional_kwargs={"categories"...}
```
