### ISSUE TITLE
Does opensearch support using Ray/Modin to ingest and query?

### ISSUE THREAD

**Issue by xiaochuan-du** [aws/aws-sdk-pandas#2323]
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
Does opensearch support use Ray/Modin to ingest and query?

**Comment by kukushking** [comment]
Hi @xiaochuan-du no unfortunately at the moment opensearch module does not support distribution using ray/modin.

**Comment by xiaochuan-du** [comment]
thank you @kukushking
