### ISSUE TITLE
"keep_files" parameter in the "to_iceberg" function

### ISSUE THREAD

**Issue by avantgardeam** [aws/aws-sdk-pandas#2331]
Hello! Wouldn't it be more logical if the "keep_files" parameter in the "to_iceberg" function defaulted to False instead of True, considering it's related to a temporary table?

**Comment by kukushking** [comment]
Hi @avantgardeam thanks for opening this! I think the rationale was just that it's safe choice that avoids data loss in case user did not expect it. The API is marked as experimental so we can change the default behaviour if there is a convincing case.
