### ISSUE TITLE
Support for MERGE INTO operations in Iceberg

### ISSUE THREAD

**Issue by avantgardeam** [aws/aws-sdk-pandas#2332]
Hello! Are there any plans to introduce support for MERGE INTO operations in Iceberg, in addition to just INSERT INTO?

**Comment by adrianrego** [comment]
Could this issue be reconsidered?  `wr.athena.to_iceberg` looks like a nice place to leverage `MERGE INTO`.  Without out it, ETL jobs could create duplicate records.
