### ISSUE TITLE
Lower "packaging" version requirement to Glue 4.0 pre-installed version 21.3

### ISSUE THREAD

**Issue by FredStober** [aws/aws-sdk-pandas#2339]
**Is your idea related to a problem? Please describe.**

AWS Glue 4.0 has packaging 21.3 pre-installed.
awswrangler 3.2.0 added a packaging requirement that is incompatible with solves that constrains python packages to those that are pre-installed on Glue 4.0.
It would be useful to lower the packaging version limit to 21.3 if possible to reduce Glue 4.0 installation times.

**Describe the solution you'd like**

Use packaging = "^21.3" instead of packaging = "^23.1" in the pyproject.toml file.

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by FredStober** [comment]
Thanks for the quick fix!

**Comment by LeonLuttenberger** [comment]
The fix was deployed in version `3.2.1` of the library.
