### ISSUE TITLE
Attribute error being flagged when importing awswrangler

### ISSUE THREAD

**Issue by christinegu1** [aws/aws-sdk-pandas#2349]
I've recently been getting an attribute error when importing awswrangler 2.12.1. I've had no issues until now so I'm a bit confused why it's happening. Any suggestions on why this might be happening?

I am currently using:
- Python 3.8.6
- awswrangler 2.12.1
- progressbar2 3.55.0

Please see flag below:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-e85f5e0affbd> in <module>
----> 1 import awswrangler

/opt/conda/lib/python3.8/site-packages/awswrangler/__init__.py in <module>
      8 import logging as _logging
      9 
---> 10 from awswrangler import (  # noqa
     11     athena,
     12     catalog,

/opt/conda/lib/python3.8/site-packages/awswrangler/opensearch/__init__.py in <module>
      3 from awswrangler.opensearch._read import search, search_by_sql
      4 from awswrangler.opensearch._utils import connect
----> 5 from awswrangler.opensearch._write import create_index, delete_index, index_csv, index_df, index_documents, index_json
      6 
      7 __all__ = [

/opt/conda/lib/python3.8/site-packages/awswrangler/opensearch/_write.py in <module>
      9 import boto3
     10 import pandas as pd
---> 11 import progressbar
     12 from jsonpath_ng import parse
     13 from jsonpath_ng.exceptions import JsonPathParserError

/opt/conda/lib/python3.8/site-packages/progressbar/__init__.py in <module>
      1 from datetime import date
      2 
----> 3 from .utils import (
      4     len_color,
      5     streams

/opt/conda/lib/python3.8/site-packages/progressbar/utils.py in <module>
      7 import logging
      8 import datetime
----> 9 from python_utils.time import timedelta_to_seconds, epoch, format_time
     10 from python_utils.converters import scale_1024
     11 from python_utils.terminal import get_terminal_size

/opt/conda/lib/python3.8/site-packages/python_utils/__init__.py in <module>
----> 1 from . import (
      2     aio,
      3     compat,
      4     converters,
      5     decorators,

/opt/conda/lib/python3.8/site-packages/python_utils/decorators.py in <module>
      6 T = types.TypeVar('T')
      7 TC = types.TypeVar('TC', bound=types.Container[types.Any])
----> 8 P = types.ParamSpec('P')
      9 
     10 

AttributeError: module 'python_utils.types' has no attribute 'ParamSpec'

**Comment by kukushking** [comment]
Hi @christinegu1 looks like that particular version of `progressbar2` has an issue. In particular, this issue is in `python_utils` that is a dependency of `progressbar2`. I suggest to try installing a different version of those libraries.

**Comment by christinegu1** [comment]
Hi @kukushking. I will try installing a different version of these libraries first. If the issue persists, I'll post the pip freeze, but I will respond back with what happens. Thanks for your response.

**Comment by christinegu1** [comment]
@kukushking Wanted to give you an update: I created a ticket with python_utils and they resolved the issue. The problem was the result of an outdated version of 'typing-extensions' being downloaded with python_utils v3.6.0. They released a patch to update typing-extensions. Now awswrangler 2.12.1 is working as expected. I will close this ticket now.
