### ISSUE TITLE
`s3.to_parquet` fails sometimes when converting string array columns to TensorArray in Ray Jobs

### ISSUE THREAD

**Issue by jvmunhoz** [aws/aws-sdk-pandas#2358]
### Describe the bug

I have an ETL whose output is a DataFrame that has quite a few array<string> columns. When saving it in parquet to s3 using `s3.to_parquet` i get the following error:

`ValueError: Tried to cast column favorite_hashtags to the TensorArray tensor extension type but the conversion failed. To disable automatic casting to this tensor extension, set ctx = DatasetContext.get_current(); ctx.enable_tensor_extension_casting = False.`

This column specifically is a list of hashtags (which are represented by an unique ID) that the user has favorited. But users can have no favorited hashtags, so the values in this column are either `NaN` or a list of strings, kinda like this `[cl7gbe4vi151501my5qln7nc3, ckzd83biv262230jlmnaq3hxca]`

I tried following the fix in the error message, but it didn't work. So I guess it's something that should be set in awswrangler?

```python
from ray.data.context import DataContext

ctx = DataContext.get_current()
ctx.enable_tensor_extension_casting = False
```

When using s3fs to save the parquet `df.to_parquet()` all goes as expected. 

Otherwise, the solution is just converting the list into a string and saving it as such in s3.

I guess providing a `tensor_extension_casting` parameter to `s3.to_parquet` would do it? if True it would keep the usual behaviour, if False, it would do no tensor extension casting at all. 

### How to Reproduce

The weird thing is that the error is not consistent at all. Just today, I've had the same ETL fail with this error and in the very first retry it worked, so I can't exactly provide a reproducible example.

### OS

Linux

### Python version

3.9.14

### AWS SDK for pandas version

3.2.0

**Comment by jvmunhoz** [comment]
But that's exactly what this code snippet I provided does, isn't it?

```python
from ray.data.context import DatasetContext

ctx = DatasetContext.get_current()
ctx.enable_tensor_extension_casting = False
```

**Comment by jaidisido** [comment]
No your code is creating an instance of the context but that is not the one used downstream in the code, instead a different instance is used.

By setting the env variable it would apply to all instances no matter where they are initialized

**Comment by jvmunhoz** [comment]
Ah, I see.

I've done some more testing, but the error is currently not happening anymore. If I let it run without any kind of DatasetContext adjustment or string conversion, it works just fine. I'll let it run over the week like this to see if I can trigger the error again and then test your suggestion.

**Comment by jvmunhoz** [comment]
Got the error to trigger again (still inconsistent btw)

But when you suggested setting environment variable you meant something like `os.environ["DEFAULT_ENABLE_TENSOR_EXTENSION_CASTING"] = "False"` ? Or putting that in the Glue job parameters.

Tried both to no avail.

**Comment by jaidisido** [comment]
After looking into it more carefully it seems that ray does not enable setting that flag via an environment variable. I have created https://github.com/ray-project/ray/pull/37074 to enable it. Hopefully it will be merged soon

**Comment by jvmunhoz** [comment]
Ah, that makes more sense. I wasn't seeing a way to change that value through an environment variable.

 Thanks for the quick fix. Hope it works. I'll be keeping tabs on this issue until it's merged and I can test.
