### ISSUE TITLE
Provide Lambda Layers in opt-in regions

### ISSUE THREAD

**Issue by madhavvishnubhatta** [aws/aws-sdk-pandas#2360]
**Is your idea related to a problem? Please describe.**
The Managed Lambda layers for AWS SDK for Pandas are available only in default regions but not in opt-in regions like UAE(me-central-1) or Hyderabad (ap-south-2). In those opt-in regions we are forced to use custom layers.

**Describe the solution you'd like**
Please provide managed layers in opt-in regions too.

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
We have been deploying the layers across regions starting with most popular ones. The opt-in regions you mentioned (along others) can be considered in the next release
