### ISSUE TITLE
AWS Lambda Managed Layer with Modin and Ray 

### ISSUE THREAD

**Issue by kangks** [aws/aws-sdk-pandas#2370]
As of version 3.2.0 for Python 3.10, the Managed Layer does not have modin and Ray support (https://aws-sdk-pandas.readthedocs.io/en/stable/layers.html).

Example of the outputs using `arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python310:3`

Lambda function:
```
import logging
import awswrangler as wr
import pandas as pd
# import modin.pandas as pd
from datetime import datetime
import pkg_resources

logger = logging.getLogger()
logger.setLevel(logging.INFO)

def lambda_handler(event, context):
    logger.info(pd.__version__)
    logger.info(wr.engine.get())
    logger.info(wr.memory_format.get())

    installed_packages = pkg_resources.working_set
    installed_packages_list = sorted(["%s==%s" % (i.key, i.version)
       for i in installed_packages])
    logger.info(installed_packages_list)

    return {}
```

Output: 

```
[INFO]	2023-06-30T05:22:50.451Z	78c9a486-e32d-4e56-8912-b7f7e6063475	2.0.2
[INFO]	2023-06-30T05:22:50.469Z	78c9a486-e32d-4e56-8912-b7f7e6063475	EngineEnum.PYTHON
[INFO]	2023-06-30T05:22:50.469Z	78c9a486-e32d-4e56-8912-b7f7e6063475	MemoryFormatEnum.PANDAS
[INFO]	2023-06-30T05:22:50.469Z	78c9a486-e32d-4e56-8912-b7f7e6063475	['aenum==3.1.12', 'aiohttp==3.8.4', 'aiosignal==1.3.1', 'asn1crypto==1.5.1', 'async-timeout==4.0.2', 'attrs==23.1.0', 'awslambdaric==2.0.4', 'awswrangler==3.2.0', 'beautifulsoup4==4.12.2', 'boto3==1.26.90', 'botocore==1.29.90', 'certifi==2023.5.7', 'charset-normalizer==3.1.0', 'decorator==5.1.1', 'et-xmlfile==1.1.0', 'frozenlist==1.3.3', 'gremlinpython==3.6.4', 'idna==3.4', 'isodate==0.6.1', 'jmespath==1.0.1', 'jsonpath-ng==1.5.3', 'lxml==4.9.2', 'multidict==6.0.4', 'nest-asyncio==1.5.6', 'numpy==1.24.3', 'openpyxl==3.1.2', 'opensearch-py==2.2.0', 'packaging==23.1', 'pandas==2.0.2', 'pg8000==1.29.6', 'pip==23.0.1', 'ply==3.11', 'pyarrow==10.0.0', 'pymysql==1.0.3', 'python-dateutil==2.8.2', 'pytz==2023.3', 'redshift-connector==2.0.911', 'requests-aws4auth==1.2.3', 'requests==2.31.0', 's3transfer==0.6.1', 'scramp==1.4.4', 'setuptools==67.8.0', 'simplejson==3.17.2', 'six==1.16.0', 'soupsieve==2.4.1', 'typing-extensions==4.6.3', 'tzdata==2023.3', 'urllib3==1.26.16', 'yarl==1.9.2']
```

Can we have managed layers that comes with modin and ray support?

**Comment by jaidisido** [comment]
Hi @kangks, our Lambda managed layers never had Ray or Modin baked in. AWS Lambda layers are limited to 250Mb unzipped and 50Mb zipped in size. Our current layer is already at 230Mb unzipped and 48Mb zipped. Ray alone is 100Mb+. So there is simply no space for it.

Beyond the size issue however, I am not sure what would be a good use case for using Ray on Lambda. The framework is dedicated to distributed computing which is not a good pattern for Lambda functions. Better options on AWS include AWS Glue jobs (including [AWS Glue for Ray](https://aws.amazon.com/blogs/big-data/advanced-patterns-with-aws-sdk-for-pandas-on-aws-glue-for-ray/)).

If for some reason you must install Ray on a Lambda environment, then one option is to build your own container [image](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html) that would include it alongside other dependencies.
