### ISSUE TITLE
`wr.dynamodb.read_items` ignores `max_items_evaluated` kwarg

### ISSUE THREAD

**Issue by a-slice-of-py** [aws/aws-sdk-pandas#2371]
### Describe the bug

`wr.dynamodb.read_items` ignores `max_items_evaluated` kwarg, **resulting in a possibly-expensive full scan operation if it is the only kwarg provided to the method** (beside to `table_name`, of course)

This bug also highlight the lack of a dedicated unit test in `tests/unit/test_dynamodb.py`

Some notes hopefully useful for debugging:

- this bug already occurs in version 2.20.0, but I am pretty confident that this has been introduced after https://github.com/aws/aws-sdk-pandas/pull/1877 (released with 2.19.0), therefore my guess is that it's related to extension of the `read_items` feature to threads/chunks/indices rather than to version 3.x changes
- the kwarg is correctly passed through from `read_items` to low level boto3 scan operation (e.g. passing `max_items_evaluated=-1` a `ParamValidationError` would be raised), but it is somehow ignored/skipped
- the kwarg corresponds to `Limit` kwarg of [boto3 client scan operation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb/client/scan.html)

### How to Reproduce

This unit test should do the job, and meanwhile is a good example of the current buggy behaviour

```python
@pytest.mark.parametrize(
    "params",
    [
        {
            "KeySchema": [{"AttributeName": "id", "KeyType": "HASH"}],
            "AttributeDefinitions": [{"AttributeName": "id", "AttributeType": "N"}],
        }
    ],
)
@pytest.mark.parametrize("use_threads", [False, True])
def test_read_items_limited(params: Dict[str, Any], dynamodb_table: str, use_threads: bool) -> None:
    df = pd.DataFrame(
        {
            "id": [1, 2, 3, 4],
            "word": ["this", "is", "a", "test"],
            "char_count": [4, 2, 1, 4],
        }
    )
    wr.dynamodb.put_df(df=df, table_name=dynamodb_table, use_threads=use_threads)

    df2 = wr.dynamodb.read_items(table_name=dynamodb_table, max_items_evaluated=1)
    assert df2.shape == (1, len(df.columns))
```

### Expected behavior

The method should abide to the given `max_items_evaluated` value, stopping the search once the given amount of items has been reached and returning up to `max_items_evaluated` items.

### OS

Windows

### Python version

3.10

### AWS SDK for pandas version

3.2.1 (but bug already occurs in 2.20.0)

**Comment by jaidisido** [comment]
Good catch @a-slice-of-py, thanks for raising this.

Based on the note in this [section](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.Pagination) of the DynamoDB docs, it seems that a `LastEvaluatedKey` is returned even when the specified Limit is returned:
```
Using aws dynamodb scan --table-name Prices --limit 1 returns a LastEvaluatedKey.
```
There must be a good reason for this behaviour but in this case it means that we cannot rely on `LastEvaluatedKey` as a signal that we have reached the end of the pagination.

I have put together a fix in #2372. Not entirely happy with it but we can discuss it there.
