### ISSUE TITLE
`wr.s3.to_deltalake` throwing TypeError about storage_options

### ISSUE THREAD

**Issue by leodido** [aws/aws-sdk-pandas#2378]
### Describe the bug

Calling `we.s3.to_deltalake()` throws the following error:

```
self._table = RawDeltaTable(
                  ^^^^^^^^^^^^^^
TypeError: argument 'storage_options': 'NoneType' object cannot be converted to 'PyString'
```

### How to Reproduce

```py
wr.s3.to_deltalake(
            df=data,
            path="s3://bucket/delta",
            index=False,
            partition_cols=["a", "b"],
            overwrite_schema=True,
            s3_additional_kwargs={
                "AWS_ACCESS_KEY_ID": "...",
                "AWS_SECRET_ACCESS_KEY": "...",
                "AWS_REGION": "eu-west-1",
            },
            s3_allow_unsafe_rename=True,
        )
```

### Expected behavior

I'd expect `awswrangler` to connect to S3 and write the delta table.

### OS

Mac

### Python version

3.11.4

### AWS SDK for pandas version

3.2.1

**Comment by jaidisido** [comment]
The `s3_additional_kwargs` argument is for passing S3 specific arguments like `ServerSideEncryption`, not your AWS credentials. The boto3 session is [used](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/s3/_write_deltalake.py#L25) to extract the credentials and the region. So as long as that is correctly configured and passed, it should be enough:
```
boto3_session = boto3.Session(region_name="eu-west-1")
wr.s3.to_deltalake(path=path, df=df, boto3_session=boto3_session, s3_additional_kwargs={"ServerSideEncryption": "AES256"})
```

**Comment by leodido** [comment]
Did it ...

```py
     boto3_session = boto3.Session(region_name="eu-west-1") # Yes, the region is correct
      wrangler.s3.to_deltalake(
          df=data,
          path="s3://mybucket/delta", # Yes, the bucket exists
          index=False,
          partition_cols=["a", "b"], 
          overwrite_schema=True,
          boto3_session=boto3_session,
          s3_allow_unsafe_rename=True,
      )
```

But I keep getting the same error:

```
TypeError: argument 'storage_options': 'NoneType' object cannot be converted to 'PyString'
```

I enabled logging (INFO level) with:

```py
logging.basicConfig(level=logging.INFO, format="[%(name)s][%(funcName)s] %(message)s")
logging.getLogger("awswrangler").setLevel(logging.INFO)
```

And I see this in logs just before the error above...

```
[botocore.credentials][load] Found credentials in environment variables.
on 0: {'AWS_ACCESS_KEY_ID': 'REDACT', 'AWS_SECRET_ACCESS_KEY': 'REDACT', 'AWS_SESSION_TOKEN': None, 'PROFILE_NAME': 'default', 'AWS_REGION': 'eu-west-1', 'AWS_S3_ALLOW_UNSAFE_RENAME': 'TRUE'}
```

Any further suggestion on how to fix this?

**Comment by jaidisido** [comment]
Hmm strange, I am unable to replicate this error on my local:
```
boto3_session = boto3.Session(region_name="us-east-1")
df = pd.DataFrame({"c0": [1, 2, 3], "c1": [True, False, True], "par0": ["foo", "foo", "bar"], "par1": [1, 2, 2]})
wr.s3.to_deltalake(
    path=path,
    df=df,
    index=False,
    boto3_session=boto3_session,
    partition_cols=["par0", "par1"],
    overwrite_schema=True,
    s3_allow_unsafe_rename=True,
)
df2 = wr.s3.read_deltalake(path=path, columns=["c0"], partitions=[("par0", "=", "foo"), ("par1", "=", "1")])
assert df2.shape == (1, 1)
```
works fine.

Could you share your pip freeze? I imagine you are on deltalake 0.9.0?

Also please try to make the call directly using the deltalake library, which is pretty much what we are [doing](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/s3/_write_deltalake.py#L103). At which point it might be worth opening an issue in [delta-rs](https://github.com/delta-io/delta-rs) directly.

**Comment by leandro-ferreira-farm** [comment]
I recive the same error here:

wr.s3.to_deltalake(
                            df=df_delta,
                            path=s3_path,
                            mode="overwrite",
                            partition_cols = partition_cols,
                            index=False,
                            overwrite_schema=True,
                            s3_allow_unsafe_rename=True,
                        )
                        
                        
 argument 'storage_options': 'NoneType' object cannot be converted to 'PyString'

**Comment by leandro-ferreira-farm** [comment]
Please, reeopen this ticket. This issue continues to happen even in version 3.3.0

**Comment by leandro-ferreira-farm** [comment]
I saw that the error happens when we use a boto.session. I don't know if it's a deltalake-rs issue or an awswrangler issue

**Comment by leandro-ferreira-farm** [comment]
I'm using poetry as a dependencies manager, and my pyproject.tom is:

[tool.poetry.dependencies]
python = "3.10.11"
awswrangler = "3.3.0"
boto3 = "1.27.1"
pyarrow = "12.0.1"
duckdb = "0.8.1"
pandas = "2.0.3"
deltalake = "0.10.0"
jsonschema = "4.18.0"
requests = "2.31.0"
pyyaml = "6.0.1"
ipykernel = "6.24.0"
pyspark = "3.4.0"
delta-spark = "2.4.0"
sagemaker = "2.72"
findspark = "2.0.1"
msal = "1.22.0"
great-expectations = "0.17.7"
hvac = "1.1.1"

**Comment by luis-fnogueira** [comment]
I gently ask to reopen this issue, I am facing the very same problem. I'm using version 3.4.1.

**Comment by ZulqarnainB** [comment]
I am facing this issue with wr.s3.read_deltalake

**Comment by neverlink** [comment]
This issue can occur when no region is associated with the profile in `~/.aws/config`
Running `aws configure` and providing a default region fixes this.

[to_deltalake()](https://github.com/aws/aws-sdk-pandas/blob/de5d1610d6d4ea3be44a01ab3f09b64e291a4ab7/awswrangler/s3/_write_deltalake.py#L24 ) pulls a `None` value from the `boto3_session` which then can't be cast to a `PyString` as the exception shows.

**Comment by stuart-powell** [comment]
I had this problem too. It looks to me like the 'AWS_SESSION_TOKEN' being None is clashing with the constructor expecting a dictionary of strings. (Perhaps the underlying C++ code does not handle None for string??)

I tried this workaround: 
       # replace None with empty string
        if 'AWS_SESSION_TOKEN' in storage_options and storage_options['AWS_SESSION_TOKEN'] is None:
            storage_options['AWS_SESSION_TOKEN'] = ''

It certainly stopped the type error, though I haven't fully written the table yet.

**Comment by vavaan** [comment]
I've had same error in AWS environment while locally everything was working fine. Got it fixed by adding before calling `to_deltalake`:
```
boto3.setup_default_session(region_name='us-east-1')
```

**Comment by pingu1m** [comment]
Just got this issue too.

I had 
`session = boto3.Session()` and I solved the issue by doing:
`session = boto3.Session(region_name="us-west-2")`
