### ISSUE TITLE
[Support Us]: LogicalCube

### ISSUE THREAD

**Issue by zolabud** [aws/aws-sdk-pandas#2383]
Thank you for letting us use your organization's name on the repository read.me page and letting other customers know that you support the project!  If you would like us to also display your organization's logo. please raise a pull request to provide an image file for the logo.

Please add any files to *docs/source/_static/*

Organization Name: LogicalCube (https://www.logicalcube.com)
Your Name: Bryan Kelly
Your Position: Manager
I have included a logo: n

*By raising a Support Us issue (and related pull request), you are granting AWS permission to use your company’s name (and logo) for the limited purpose described here and you are confirming that you have authority to grant such permission.*

**Comment by jaidisido** [comment]
Added in https://github.com/aws/aws-sdk-pandas/commit/6eb8462202803e0233c4ddb2cd899f0da993f0b9 thanks for the support!
