### ISSUE TITLE
Exclude unused Dependencies in Lambda Layer

### ISSUE THREAD

**Issue by hendrikschafer** [aws/aws-sdk-pandas#2389]
Hi Team, since introducing the optional dependencies for some packages eg pyarrow etc. , when using the lambda layer, is it possible to exclude them from the unzipped lambda size check? Or will they always be included?

**Comment by jaidisido** [comment]
Most dependencies are included in the lambda layer. Removing dependencies that are now optional would be a breaking change for users who upgrade to a new version of the layer. We also wouldn't know which dependencies to remove as each user considers some of them optional but not others
