### ISSUE TITLE
Loading timeseries data to Redshift using AWS Wrangler results in loss of timezone information

### ISSUE THREAD

**Issue by Mahima-ai** [aws/aws-sdk-pandas#2413]
I am working on a use case which involves loading time series data with timezone information in Redshift. There are 50K datapoints.
There are two ways to do this:

1. Using  [wr.redshift.to_sql() method](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.redshift.to_sql.html)
2. Using [wr.redshift.copy() method](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.redshift.copy.html)

Using the `wr.redshift.to_sql()` method I am able to retain the timezone information in the Redshift. In the documentation for larger DataFrames (1K+ rows) they recommend to use `wr.redshift.copy()`. When I use the `wr.redshift.copy()` method I am not able to retain the timezone information. Please help me to resolve this. Below are the approaches I worked on and their results:

**Environment:**
OS: Linux
Python : 3.8.3
awswrangler : 2.16.1
redshift_connector : 2.0.913
pandas : 1.4.1

**Code to reproduce:**
Creating a time series Dataframe
```
from datetime import timedelta
import awswrangler.redshift as rs
import redshift_connector
import pandas as pd
import os

a = pd.Timestamp('2020-03-14T15:32:52.192548651', tz="UTC")
time_index = []
timestamp_tz = []
for counter in range(1,10):
    time_index.append('time_'+str(counter))
    timestamp_tz.append(a+timedelta(days=counter))
dataframe = pd.DataFrame(data = {'time_index': time_index, 'timestamp_info':timestamp_tz})
dataframe.info()

```
Creating the Redshift Connection
```
rs_conn = redshift_connector.connect(host=host, database=database, user=user, password=password)
rs_conn.autocommit = True
```
Loading the DataFrame to Redshift using  `wr.redshift.copy()` method

Approach 1:
```
rs.copy(
  df=dataframe,
  path='S3_path',
  con=rs_conn,
  table='timestamp_test',
  schema='schema_test',  
  )
```
Result : Stores data in the Redshift without timezone. The datatype is timestamp instead of timestamptz.

Approach 2:
```
rs.copy(
  df=dataframe,
  path='S3_path',
  con=rs_conn,
  table='timestamp_test',
  schema='schema_test',  
  dtype = {'timestamp_info':'TIMESTAMPTZ'}
  )
```
UnsupportedType: Unsupported Athena type: timestamptz

Approach 3: Replaced 'TIMESTAMPTZ' with 'timestamp with time zone' but it also gave output as UnsupportedType.

Approach 4:
```
rs.copy(
  df=dataframe,
  path='S3_path',
  con=rs_conn,
  table='timestamp_test',
  schema='schema_test',  
  sql_copy_extra_params=["TIMEFORMAT AS 'auto'"]
  )
```
ProgrammingError: {'S': 'ERROR', 'C': '0A000', 'M': 'TIMEFORMAT argument is not supported for PARQUET based COPY', 'F': '../src/pg/src/backend/commands/commands_copy.c', 'L': '2933', 'R': 'report_keyword_error'}

Any help in this regard is appreciated.

**Comment by jaidisido** [comment]
Hi @Mahima-ai, could you double check that your table actually has the `timezone_info` set to the `TIMESTAMPTZ` data type?

The code below returns a data frame with the timezone, but note how the column has the right type at table creation:
```
from datetime import timedelta
import awswrangler as wr
import pandas as pd

schema = "public"
table = "test_timezone_2413"
iam_role = "arn:aws:iam::..."
path = f"s3://bucket/{table}/"

con = wr.redshift.connect(connection="aws-sdk-pandas-redshift")
con.autocommit = True

with con.cursor() as cursor:
    cursor.execute(
        f"""
        CREATE TABLE {schema}.{table} (
            time_index VARCHAR(100),
            timestamp_info TIMESTAMPTZ
        );
        """
    )

df = pd.DataFrame({
    "time_index": [f"time_{i}" for i in range(1, 10)],
    "timestamp_info": [pd.Timestamp('2020-03-14T15:32:52.192548651', tz="UTC") + timedelta(days=i) for i in range(1, 10)],
})
print(df)
print(df.dtypes)

wr.redshift.copy(
    df=df,
    path=path,
    con=con,
    table=table,
    schema=schema,
)

df_redshift = wr.redshift.read_sql_table(con=con, table=table, schema=schema)

print(df_redshift)
print(df_redshift.dtypes)
```
Output:
```
  time_index                      timestamp_info
0     time_1 2020-03-15 15:32:52.192548651+00:00
1     time_2 2020-03-16 15:32:52.192548651+00:00
2     time_3 2020-03-17 15:32:52.192548651+00:00
3     time_4 2020-03-18 15:32:52.192548651+00:00
4     time_5 2020-03-19 15:32:52.192548651+00:00
5     time_6 2020-03-20 15:32:52.192548651+00:00
6     time_7 2020-03-21 15:32:52.192548651+00:00
7     time_8 2020-03-22 15:32:52.192548651+00:00
8     time_9 2020-03-23 15:32:52.192548651+00:00
time_index                     object
timestamp_info    datetime64[ns, UTC]

  time_index                   timestamp_info
0     time_1 2020-03-15 15:32:52.192548+00:00
1     time_3 2020-03-17 15:32:52.192548+00:00
2     time_5 2020-03-19 15:32:52.192548+00:00
3     time_7 2020-03-21 15:32:52.192548+00:00
4     time_9 2020-03-23 15:32:52.192548+00:00
5     time_2 2020-03-16 15:32:52.192548+00:00
6     time_4 2020-03-18 15:32:52.192548+00:00
7     time_6 2020-03-20 15:32:52.192548+00:00
8     time_8 2020-03-22 15:32:52.192548+00:00
time_index             string[python]
timestamp_info    datetime64[ns, UTC]
```

**Comment by Mahima-ai** [comment]
> Hi @Mahima-ai, could you double check that your table actually has the `timezone_info` set to the `TIMESTAMPTZ` data type?
> 
> The code below returns a data frame with the timezone, but note how the column has the right type at table creation:
> 
> ```
> from datetime import timedelta
> import awswrangler as wr
> import pandas as pd
> 
> schema = "public"
> table = "test_timezone_2413"
> iam_role = "arn:aws:iam::..."
> path = f"s3://bucket/{table}/"
> 
> con = wr.redshift.connect(connection="aws-sdk-pandas-redshift")
> con.autocommit = True
> 
> with con.cursor() as cursor:
>     cursor.execute(
>         f"""
>         CREATE TABLE {schema}.{table} (
>             time_index VARCHAR(100),
>             timestamp_info TIMESTAMPTZ
>         );
>         """
>     )
> 
> df = pd.DataFrame({
>     "time_index": [f"time_{i}" for i in range(1, 10)],
>     "timestamp_info": [pd.Timestamp('2020-03-14T15:32:52.192548651', tz="UTC") + timedelta(days=i) for i in range(1, 10)],
> })
> print(df)
> print(df.dtypes)
> 
> wr.redshift.copy(
>     df=df,
>     path=path,
>     con=con,
>     table=table,
>     schema=schema,
> )
> 
> df_redshift = wr.redshift.read_sql_table(con=con, table=table, schema=schema)
> 
> print(df_redshift)
> print(df_redshift.dtypes)
> ```
> 
> Output:
> 
> ```
>   time_index                      timestamp_info
> 0     time_1 2020-03-15 15:32:52.192548651+00:00
> 1     time_2 2020-03-16 15:32:52.192548651+00:00
> 2     time_3 2020-03-17 15:32:52.192548651+00:00
> 3     time_4 2020-03-18 15:32:52.192548651+00:00
> 4     time_5 2020-03-19 15:32:52.192548651+00:00
> 5     time_6 2020-03-20 15:32:52.192548651+00:00
> 6     time_7 2020-03-21 15:32:52.192548651+00:00
> 7     time_8 2020-03-22 15:32:52.192548651+00:00
> 8     time_9 2020-03-23 15:32:52.192548651+00:00
> time_index                     object
> timestamp_info    datetime64[ns, UTC]
> 
>   time_index                   timestamp_info
> 0     time_1 2020-03-15 15:32:52.192548+00:00
> 1     time_3 2020-03-17 15:32:52.192548+00:00
> 2     time_5 2020-03-19 15:32:52.192548+00:00
> 3     time_7 2020-03-21 15:32:52.192548+00:00
> 4     time_9 2020-03-23 15:32:52.192548+00:00
> 5     time_2 2020-03-16 15:32:52.192548+00:00
> 6     time_4 2020-03-18 15:32:52.192548+00:00
> 7     time_6 2020-03-20 15:32:52.192548+00:00
> 8     time_8 2020-03-22 15:32:52.192548+00:00
> time_index             string[python]
> timestamp_info    datetime64[ns, UTC]
> ```

Hi @jaidisido,

Thank you for your response. The example given by you is working but it fails in the following two scenarios:
1. When we use the parameter `mode='overwrite'` in the `wr.redshift.copy()`. My use case uses the overwrite mode. 
2. We query the table using `wr.redshift.unload()` instead of `wr.redshift.read_sql_table()`. `wr.redshift.unload()` is the recommended method for 1K+ rows.

Thanks!
