### ISSUE TITLE
Reducing the memory footprint of wr.s3.to_parquet

### ISSUE THREAD

**Issue by mccauleyp** [aws/aws-sdk-pandas#2421]
Hello, 

Love this library and in particular all of the Glue catalog manipulations that are built in to the S3 methods. We recently encountered an issue that relates to the memory footprint of `wr.s3.to_parquet`. We have a line that looks like this: 

```
wr.s3.to_parquet(
    df.assign(**partitions),
    dataset=True,
    database=glue_database,
    table=glue_table,
    path=s3_path,
    partition_cols=list(partitions.keys()),
)
```

So the DataFrame that we're writing doesn't actually contain the partition columns from the `partitions` dict. We add those in using `.assign`, and then `to_parquet` strips them back out to write the file to S3 with the appropriate S3 key format for our table. 

Our problem is that the DataFrame we're writing is around 3 GB but balloons to over 20 GB after the `.assign`, which then exceeds the limits of AWS Lambda. I can think of two ways to solve this: 

1) Don't use the `dataset=True` option and decompose all that magic into separate steps, meaning create the table if it doesn't exist, construct the S3 key, write the parquet file, and then add the parquet partition. This would avoid the memory issue but we lose all that leverage that the `dataset=True` option brings. 

2) Break the DataFrame into smaller chunks so that the `.assign` doesn't lead to such a large object. 

We're probably going to go with option 2 because it's easier to implement, but I think it's a bit unfortunate that the memory consumption is so much larger than it really needs to be. Are there any other options we haven't considered that would avoid the large memory footprint while still allowing us to use the `dataset=True` option? Or might there be some edit to `to_parquet` to support something like that? 

Cheers!

**Comment by LeonLuttenberger** [comment]
Hey,

Which version of the library and layer are you using? And what are the dimensions of the DataFrame before adding the partition columns (i.e. number of rows and columns)? I find it strange that the frame size balloons so much, so I'd like to play around with frames with similar dimensions.

I agree option 2 is easier to implement. I can't think of a third option right now unfortunately. As I play around with a similar-sized DataFrame I'll see if there are any other options though, or changes that we could make to the function.

Best regards,
Leon

**Comment by mccauleyp** [comment]
> Hey,
> 
> Which version of the library and layer are you using? And what are the dimensions of the DataFrame before adding the partition columns (i.e. number of rows and columns)? I find it strange that the frame size balloons so much, so I'd like to play around with frames with similar dimensions.
> 
> I agree option 2 is easier to implement. I can't think of a third option right now unfortunately. As I play around with a similar-sized DataFrame I'll see if there are any other options though, or changes that we could make to the function.
> 
> Best regards, Leon

Thanks for the reply @LeonLuttenberger! We're using version `3.2.1` in a Dockerized Lambda. The original shape (columns, rows) is around `(7E7, 4)`. Those first four columns all integers and then there are 4 more partition string columns added with the `.assign` statement. Two of those columns are UUID's (e.g. `str(uud.uuid4())`), and I think the frame size gets so huge primarily because those long UUID strings are being repeated in memory 70 million times.
