### ISSUE TITLE
Ray instance long startup time on Glue Ray script

### ISSUE THREAD

**Issue by jorge-bruno** [aws/aws-sdk-pandas#2425]
I have a simple python script that runs on an aws glue ray script. The code is something like this:
```python
import awswrangler as wr

print(f"Execution Engine: {wr.engine.get()}")
print(f"Memory Format: {wr.memory_format.get()}")

path = '<input_file_path>'
table_location = '<table_location>'
dtypes = {...}

df = wr.s3.read_parquet(
    path=path,
    dataset=True,
    path_suffix='.parquet'
)

#perform some transformations

wr.athena.to_iceberg(
    df=df,
    database='<database>',
    table='<table_name>',
    temp_path=temp_path,
    index=False,
    table_location=table_location,
    partition_cols=partition_cols,
    keep_files=False,
    dtype=dtypes
)
```
The job parameters are as follows:
![image](https://github.com/aws/aws-sdk-pandas/assets/84637128/204cef5e-816d-4a7c-8e39-f31fac64d1ec)

The input files are approx. 4gb on memory, the job ran for almost 12 min and ~10 of them where for initializing the ray instance
![image](https://github.com/aws/aws-sdk-pandas/assets/84637128/3ef52bf2-14ee-4b4e-89ae-f9846d9e76e5)

Is this duration normal? Is it correct that it initializes a instance for every execution? https://aws-sdk-pandas.readthedocs.io/en/stable/scale.html#getting-started

**Comment by jaidisido** [comment]
I believe cluster initialisation was instantaneous. The issue here is that AWS Glue for Ray jobs only seem to output some of the logs at the end (and not during), including some duplicates. For instance, this exact log output:
```
INFO worker.py:1616 -- Connected to Ray cluster. View the dashboard at...
```
appears at 22:41 and then again at 22:52.

As a side note, notice the `UserWarning... defaulting to pandas implementation`. My hunch is that this is where most of the time is lost for this job. It's caused by having to [resolve](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/_data_types.py#L485) pyarrow data types from the data frame, which leads to converting the modin df to pandas, a slow operation for large data frames. If possible, I would suggest creating the Glue table in advance to avoid this.

**Comment by jorge-bruno** [comment]
I made some modifications to the code, now it looks something like this
```
import awswrangler as wr
import modin.pandas as pd
import ray


@ray.remote
def read_from_s3(path, dataset, path_suffix):
    return wr.s3.read_parquet(
        path=path,
        dataset=dataset,
        path_suffix=path_suffix
    )

@ray.remote
def write_to_athena(df, database, table, temp_path, index, table_location, partition_cols, keep_files, dtype):
    wr.athena.to_iceberg(
        df=df,
        database=database,
        table=table,
        temp_path=temp_path,
        index=index,
        table_location=table_location,
        partition_cols=partition_cols,
        keep_files=keep_files,
        dtype=dtype
    )

print(f"Execution Engine: {wr.engine.get()}")
print(f"Memory Format: {wr.memory_format.get()}")
wr.catalog.delete_table_if_exists(database=database, table=table)

dtypes = {...}

# Use Ray to read from S3
df_future = read_from_s3.remote(
    path=path,
    dataset=True,
    path_suffix='.parquet'
)

# Fetch the result from the Ray task
df = ray.get(df_future)

# Use Ray to write to Athena
write_to_athena.remote(
    df=df,
    database=database,
    table=table,
    temp_path=temp_path,
    index=False,
    table_location=table_location,
    partition_cols=partition_cols,
    keep_files=False,
    dtype=dtypes
)
```
I executed it multiple times, it finished in less than 2 minutes and its succeding, but it's not writing any file, log seems to show everythings ok

**Comment by jaidisido** [comment]
No, you shouldn't wrap the methods in ray.remote decorators, their are already distributed and implement it under the hood, it makes no sense to do it this way

**Comment by jorge-bruno** [comment]
Ok thx! I tried removing the dtype argument on the to_iceberg function and it succesfully created the table in 2 min, thanks!
