### ISSUE TITLE
read_parquet -> apply -> to_parquet

### ISSUE THREAD

**Issue by twonil-jordan-stout** [aws/aws-sdk-pandas#2431]
```python
df = wr.s3.read_parquet(f's3://{bucket}/{key}')
df = df.apply(update_row, client=client, axis=1)
wr.s3.to_parquet(
    df=df,
    path=out_path,
    index=False
)
```

I'm trying to process batches of files using parquet + lambda.

Things work until I go to upload back into Redshift.  `to_parquet` seems to be converting int32 columns to int64.

The table field types should be identical between mappings.  How can I ensure the output matches the input?

**Comment by kukushking** [comment]
Hi @twonil-jordan-stout, how are you uploading to redshift? It is not in your code sample. What exactly happens then - does the upload fail with an error? If so, what is the error? Is `df.apply` in the code sample relevant to the issue?

**Comment by twonil-jordan-stout** [comment]
@kukushking Hey,

The out_path is an s3 source, so to_parquet is doing the upload.

df.apply in this updates two different columns based on criteria and returning the full row.

```python
def update_row(row):
    uri_query = row['uri_query']
    traffic_source = row['traffic_source']
    referer = row['referer']

    # fix utm_source if changed
    query_params = querystring_dict(uri_query)
    fixed_utm_source = get_utm_source(query_params['utm_source'], uri_query)
    if fixed_utm_source != row['utm_source']:
        row['utm_source'] = fixed_utm_source

    # fix traffic source if changed
    fixed_traffic_source = get_traffic_source(query_params['utm_source'], uri_query, referer, client)
    if fixed_traffic_source != traffic_source:
        row['traffic_source'] = fixed_traffic_source

    return row
```

I can run this same pipeline using pandas directly and manually uploading to S3 and everything works.

**Comment by kukushking** [comment]
Thanks @twonil-jordan-stout I see so there is no Redshift involved, it's only S3. When you say it doesn't work - what is the error? Can you share the full stack trace of the error?

**Comment by twonil-jordan-stout** [comment]
@kukushking 

`file [...] has an incompatible Parquet schema for column [...]/.yr Column type INT. Parqu`

`yr` in source file is int32 and the output file changes it to `int64`

When using dask, I can pass in the original dataframe and it retains types.  Also, again, plain pandas doesn't change types.

```python
# this doesn't change types using pandas
import pandas as dd

df = dd.read_parquet('0015_part_00.parquet')
df.to_parquet('0015_part_00_hmm.parquet', index=False)
```



```python
# this does change types
import awswrangler as wr

df = wr.s3.read_parquet(f's3://{bucket}/{key}')
wr.s3.to_parquet(
      df=df,
      path=f's3://{bucket}/out/{key}',
      index=False
)
```

**Comment by twonil-jordan-stout** [comment]
@kukushking Just confirmed that it happens when using `apply` but doesn't happen when using dask.  Dask retains the column types
