### ISSUE TITLE
Combine Cached Data with New Data using max_cache_seconds

### ISSUE THREAD

**Issue by flowtrader2016** [aws/aws-sdk-pandas#2432]
**Is your feature request related to a problem? Please describe.**
Yes, when using the `max_cache_seconds` feature in `read_sql_query`, it only returns the cached results from S3. While this is efficient, it doesn't provide me with any new data that has been added since the last cached result.

**Describe the solution you'd like**
I'd like an enhancement to the `max_cache_seconds` functionality where:
1. If a matching cached result is found, it's returned.
2. The system then fetches any data added or updated since the last cached result.
3. Both the cached and new data are combined and returned to the user.

**Describe alternatives you've considered**
One alternative would be to manually manage the data retrieval process: first fetching the cached data and then running a separate query to get the new data. However, this approach is cumbersome.

**Additional context**
This enhancement would be particularly beneficial for datasets that have frequent updates. It ensures users always have access to the latest data without the need to re-fetch the entire dataset, optimizing both performance and data freshness.

**Comment by kukushking** [comment]
Hi @flowtrader2016 you should use `max_cache_seconds` to tune caching to the approximate frequency of data updates. Also unfortunately it would not be possible to tell the records that were added/updated without reading the full result set.
