### ISSUE TITLE
pyarrow.lib.ArrowInvalid: Schema at index 0 was different reading data via s3.read_parquet using the paramters chunked and columns

### ISSUE THREAD

**Issue by KaroPy** [aws/aws-sdk-pandas#2433]
### Describe the bug

Hello community, 

I'm currently attempting to load Parquet files using awswrangler version 3.3.0 and the s3.read_parquet function, with the parameters chunked=True and specifying the specific columns I wish to load. While the initial reading of the data seems to work correctly, I encounter an error when attempting to concatenate the loaded chunks together. Interestingly, when I omit the columns parameter, the concatenation process functions without any issues.

To illustrate this problem and make it easier for the community to assist, I've provided a reproducible example using a public dataset. The second part results in the following error message: 
```
Traceback (most recent call last):
  File "/home/karoline/Innkeepr/Git/prefect-flows-etl/error_reading_parquet.py", line 17, in <module>
    for df in df_selective:
  File "/home/karoline/.local/share/virtualenvs/prefect-flows-etl-94aQ17Of/lib/python3.10/site-packages/awswrangler/s3/_read_parquet.py", line 243, in _read_parquet_chunked
    table=pa.Table.from_batches(chunks, schema=pq_file.schema.to_arrow_schema()),
  File "pyarrow/table.pxi", line 3979, in pyarrow.lib.Table.from_batches
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Schema at index 0 was different: 
quadkey: string
tile: string
avg_d_kbps: int64
avg_u_kbps: int64
avg_lat_ms: int64
avg_lat_down_ms: int32
avg_lat_up_ms: int32
tests: int64
devices: int64
vs
avg_d_kbps: int64
avg_u_kbps: int64
avg_lat_ms: int64
```

### How to Reproduce

```
import awswrangler as wr
import pandas as pd
print(f"awswrangler version: {wr.__version__}")

path = "s3://ookla-open-data/parquet/performance/type=fixed/year=2023/quarter=1/2023-01-01_performance_fixed_tiles.parquet"

# read parquet file in chunks
df_chunked = wr.s3.read_parquet(path,chunked=True)
df_concat = pd.DataFrame()
for df in df_chunked:
    df_concat = pd.concat([df_concat, df])
print(f"read all data = {df_concat.shape}")

# read parquet file with specific columns resulting in an error
df_selective = wr.s3.read_parquet(path,chunked=True,columns=["avg_d_kbps","avg_u_kbps","avg_lat_ms"])
df_combine = pd.DataFrame()
for df in df_selective:
    df_combine = pd.concat([df_combine, df])
print(f"read data using certain columns  = {df_combine.shape}")

```

### Expected behavior

In Version 3.1 I can concatenate the chunks without any errors using the parameter columns. 

### OS

Linux

### Python version

Python 3.10.12

### AWS SDK for pandas version

2.0.3

**Comment by kukushking** [comment]
Hi @KaroPy what is the version of pyarrow in both cases? You can check the version via:
```
import pyarrow as pa

print(f"pyarrow version: {pa.__version__}")
```

**Comment by KaroPy** [comment]
Hey @kukushking , the pyarrow version is 12.0.1

**Comment by MorganLu** [comment]
Have the same issue with awswrangler-3.4.0 + pyarrow-13.0.0.
But it works properly with awswrangler-3.2.1 + pyarrow-13.0.0.
Is it possible that the root cause was because the PR here adding schema checks?
https://github.com/aws/aws-sdk-pandas/pull/2400/files

**Comment by mmilosav** [comment]
Same issue with awswrangler-3.4.1 + pyarrow-12.0.1.

**Comment by irowberryFS** [comment]
Also getting the same issue with awswrangler-3.4.2 and pyarrow-14.0.1

**Comment by rchromik** [comment]
I have same issue with awswrangler-3.4.2 and pyarrow-14.0.2
