### ISSUE TITLE
A public json to identify the right layer ARN

### ISSUE THREAD

**Issue by madhavvishnubhatta** [aws/aws-sdk-pandas#2434]
**Is your feature request related to a problem? Please describe.**
At the moment, there is no good way to identify what the lambda layer ARN is for a given region, python version and package version. The layer ARNs need to be hardcoded, and it becomes tricky if we have to deploy lambda functions that use this package to multiple regions.

**Describe the solution you'd like**
A public json that maps every combination of region, python version and package version to a specific layer ARN.

**Describe alternatives you've considered**
While the json solves the problem for this package, publishing the ARNs as [public parameters ](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-public-parameters.html)on SSM parameter store might be a better way as that would apply to all AWS vended/curated layers (not just this one). But that might be a longer term approach, while this json could help with the short term.

**Additional context**
Based on this [Slack discussion](https://aws-sdk-pandas.slack.com/archives/C028ZDMB12L/p1687766147253529).

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by malachi-constant** [comment]
Public parameters are now in place and can be found in both the SSM console under `Public Parameters` | `aws-sdk-pandas` 
<img width="1671" alt="Screenshot 2023-10-09 at 8 16 04 AM" src="https://github.com/aws/aws-sdk-pandas/assets/6465221/71db885c-6882-46ab-a58c-b42ad7f7a049">

Or via the CLI
```
aws ssm get-parameters-by-path --path /aws/service/aws-sdk-pandas --recursive
```

Will add to our docs shortly.

**Comment by madhavvishnubhatta** [comment]
Looks like these parameters are available only in us-east-1 but not in other regions. Is that the case? If so, is that intentional?

**Comment by malachi-constant** [comment]
@madhavvishnubhatta Thanks for raising this. We agree that global parameters should be stored in the region where the layer exists. We will reopen and update this ticket with progress.

**Comment by malachi-constant** [comment]
SSM parameters are now up to date `<=3.4.2` in all regions (including opt-in). Note: Parameters reside in the same region as their layer now.
