### ISSUE TITLE
RedshiftDataApi: Support temporary credentials auth via IAM

### ISSUE THREAD

**Issue by theister** [aws/aws-sdk-pandas#2435]
**Is your idea related to a problem? Please describe.**

I love the convenience of using `wr.data_api.redshift.read_sql_query()` to fetch data from a redshift cluster using temporary credentials, without having to worry about VPCs and network accessibility.

Currently, the authentication methods accepted in the `wr.data_api.redshift.RedshiftDataApi` class are restricted to either an explicit db user name or a link to the secrets manager, and [fails if neither is passed](https://github.com/aws/aws-sdk-pandas/blob/906b4d2/awswrangler/data_api/redshift.py#L96) by the user.

The underlying redshift-data -> executeStatement api call however [falls back to IAM](https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html
) if neither is given, which i'd like to make use of in the wrangler calls as well. A direct mapping to IAM users allows us to easier implement role based access control, as database users would be directly related to the roles already set up for the specific teams.

**Describe the solution you'd like**

If neither a `db_user` nor `secret_arn` are given, the `RedshiftDataApi` class does not throw an error, but pass on neither, which causes the `executeStatement` api call to use `getTemporaryCredentialsWithIAM` instead of `getTemporaryCredentials`.

Alternatively, a `use_iam` flag (or similar) could be implemented if that's preferable.

Would you be willing to accept/merge a PR that changes this behaviour?

**Comment by kukushking** [comment]
Hi @theister yes contributions are very welcome! As far as I can tell, we do not need an extra flag, it should be possible to fall back to IAM if neither secret nor user is passed keeping the backward-compatibility.

**Comment by anand086** [comment]
I am using 3.4.0 version and the RedshiftDataApi connection still fails with " ERROR - Either `secret_arn` or `db_user` must be set for authentication" if neither db_user nor secret_arn parameter is added.  Is there a way for data_api.redshift.connect to fallback to IAM?

```
>>> import awswrangler as wr
>>> wr.__version__
'3.4.0'
>>>

redshift_data_api_client = wr.data_api.redshift.connect(
        cluster_id=cluster_identifier,
        database=db_name,
        retries=2,
        boto3_session=boto_session
    )
    
  
```
