### ISSUE TITLE
Incompatibility Issue with Timestamp Precision when Using to_deltalake() 

### ISSUE THREAD

**Issue by DimitarSirakov** [aws/aws-sdk-pandas#2437]
Problem Description:
The issue I'm encountering is related to the casting of timestamp columns in a DataFrame when utilizing the `to_deltalake`() function. Presently, when I pass a dtype containing timestamp columns, the columns are casted to nanoseconds (ns) precision. However, Deltalake exclusively supports microsecond (us) precision for timestamps. As a result of this discrepancy in precision, the `deltalake.write_deltalake` operation throws an error with the message: "Schema error: Invalid data type for Delta Lake: Timestamp(Nanosecond, None)."

Desired Solution:
I propose that necessary modifications be implemented in the `athena2pyarrow` function of the AWS SDK for Pandas. Specifically, when handling timestamp columns in this function, it should be adjusted to use microseconds (us) precision instead of nanoseconds (ns). This adjustment will ensure that the timestamp columns align with Deltalake's precision requirements, fostering consistency in precision. By incorporating this alteration, we can guarantee that Deltalake can effectively parse the timestamp column, thus preventing any compatibility issues stemming from precision disparities.

**Comment by kukushking** [comment]
Hi @DimitarSirakov I've double checked and it is possible to write datetime objects in microseconds (`us`):
```
from datetime import datetime
import pandas as pd
import awswrangler as wr

df = pd.DataFrame({"c0": [1, 2, 3], "c1": ["foo", None, "bar"], "c2": [3.0, 4.0, 5.0], "c3": [True, False, None]})
df["c4"] = pd.to_datetime(datetime.now().timestamp())
# Cast to microseconds
df["c4"] = df["c4"].astype("datetime64[us]")
# Validate dtype
df.dtypes

Out[4]: 
c0             int64
c1            object
c2           float64
c3            object
c4    datetime64[us]
dtype: object

wr.s3.to_deltalake(path=<REDACTED>, df=df)
```
If I inspect the output parquet file, the timestamp in the file is in microseconds (`us`).
```
> parquet-tools inspect <REDACTED>
...
############ Column(c4) ############
name: c4
path: c4
max_definition_level: 1
max_repetition_level: 0
physical_type: INT64
logical_type: Timestamp(isAdjustedToUTC=false, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false)
converted_type (legacy): NONE
```

Can you provide a reproducible example of the issue, please?
