### ISSUE TITLE
wr.athena.to_iceberg does same account table look up first even though data_source is specified

### ISSUE THREAD

**Issue by Xiangyu-C** [aws/aws-sdk-pandas#2441]
### Describe the bug

When calling:
`wr.athena.to_iceberg`
It first check if the table exists by calling (see line #3 below)

```
try:
        # Create Iceberg table if it doesn't exist
        if not catalog.does_table_exist(database=database, table=table, boto3_session=boto3_session):
            _create_iceberg_table(
                df=df,
                database=database,
                table=table,
                path=table_location,  # type: ignore[arg-type]
                wg_config=wg_config,
                partition_cols=partition_cols,
                additional_table_properties=additional_table_properties,
                index=index,
                data_source=data_source,
                workgroup=workgroup,
                encryption=encryption,
                kms_key=kms_key,
                boto3_session=boto3_session,
                dtype=dtype,
            )
```
In the 
`wr.catalog.does_table_exist()` call, there is nothing that can specify data_source or catalog_id (even though in the API you could add catalog_id).
This caused my to_iceberg call to fail because I need to write to cross account. Can this be fixed to either allow catalog_id or data_source to be used?

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
Just try the to_iceberg call and try to write a table but don't give yourself permission to your same account glue catalog. You will get the following access denied error:

An error occurred (AccessDeniedException) when calling the GetTable operation

### OS

amazon linux

### Python version

3.9

### AWS SDK for pandas version

3.3.0

**Comment by Xiangyu-C** [comment]
In the same code, the subsequent s3.to_parquet and catalog.delete_table_if_exists both lack catalog_id or data_source.

**Comment by jaidisido** [comment]
I am confused, the [wr.athena.to_iceberg](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.to_iceberg.html#awswrangler.athena.to_iceberg) already exposes a `datasource` which is then used downstream in the implementation. Isn't that what you are asking about?

I also assume that you have configured your boto3 credentials for the cross account access as well?

**Comment by Xiangyu-C** [comment]
@jaidisido If you look at athena.py code, you can see even though data_source is used by to_iceberg but it is not used by any subsequent calls in that method (the code snippet in my first comment is what to_iceberg does first)

**Comment by jaidisido** [comment]
I see, thanks. #2446 should fix this. Please keep in mind that the boto3_session will still have to handle the cross account calls though as not all APIs in `to_iceberg` support catalog_id/data_source (e.g. Athena wait_query...)

**Comment by Xiangyu-C** [comment]
Thank you. Yeah I have configured cross account IAM policies so that part should be fine.
