### ISSUE TITLE
Using reserved words as Redshift table names results in error on upserting data when precombine_key is defined

### ISSUE THREAD

**Issue by kahfai99** [aws/aws-sdk-pandas#2442]
### Describe the bug

I currently have a table named "order" in my redshift database. When using redshift.copy() with mode="upsert" and precombine_key="datetime", the query will fail due to "order" being a reserved word in redshift.

Error message: 

KeyError: ('DELETE FROM "my_schema"."order" USING "temp_redshift_e7e5d5333a9a474b8a8b367b9d89c550" WHERE "order".id = "temp_redshift_e7e5d5333a9a474b8a8b367b9d89c550".id AND order.datetime<= temp_redshift_e7e5d5333a9a474b8a8b367b9d89c550.datetime', ())

redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'syntax error at or near "order"', 'P': '161', 'F': '/home/ec2-user/padb/src/pg/src/backend/parser/parser_scan.l', 'L': '732', 'R': 'yyerror'}

### How to Reproduce

import awswrangler as wr
import pandas as pd

S3_PATH = "s3://test-bucket/tmp/"

df = pd.DataFrame(
    {
        "id": [1,2,3],
        "value": ["foo1", "bar1", "cho1"],
        "datetime": pd.to_datetime(["2022-01-01", "2022-01-02", "2022-01-03"])
    }
)

con = wr.redshift.connect("my-connection")

wr.redshift.copy(
    df=df,
    path=S3_PATH,
    con=con,
    schema="my_schema",
    table="order",
    mode="upsert",
    primary_keys=["id"],
    precombine_key="datetime",
)

### OS

Linux

### Python version

Python 3.9.16

### AWS SDK for pandas version

awswrangler 2.20.1

**Comment by LeonLuttenberger** [comment]
Hey,

I tried running the code snippet you provided on the most recent version of the library - `3.3.0`. I was able to create the table named `order` with the `precombine_key`.

Can you try this with the `3.3.0` version of the library in your project?

Best regards,
Leon
