### ISSUE TITLE
Python 3.11.0 unable to import on arm64

### ISSUE THREAD

**Issue by FireAndIceFrog** [aws/aws-sdk-pandas#2443]
### Describe the bug

Importing pandas using the layer updated for python 3.11.0 now fails to import. 

It looks like there is a shared library now missing in the build. Please investigate

I am using the platform 'manylinux2014_aarch64' 

![image](https://github.com/aws/aws-sdk-pandas/assets/60675668/c6c7d3f6-ed45-4e1f-b320-aa7136b1bf0c)

`libxslt.so.1: cannot open shared object file: No such file or directory`

### How to Reproduce

Add the layer to terraform or sam config, sam result

```yaml
Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python311-Arm64:1
 ```
 
 Then later 
 
 ```python
import pandas as pd
```

### Expected behavior

The error doesnt exist and you can import

### OS

manylinux2014_aarch64 (aws arm)

### Python version

3.11.0

### AWS SDK for pandas version

1

**Comment by jaidisido** [comment]
The released AWS Lambda layers are meant to be used within Lambda functions. When I test the below snippet in an Arm64 Py3.11 Lambda with the layer, it passes without issues:
```
import pandas as pd
import awswrangler as wr

def lambda_handler(event, context):
    print(pd.__version__)
    print(wr.__version__)
    return {
        'statusCode': 200,
    }
```
<img width="544" alt="image" src="https://github.com/aws/aws-sdk-pandas/assets/16362107/893bb899-e13b-4f81-ba09-ab0f9fa59e94">
