### ISSUE TITLE
s3.to_parquet with 'zstd' compression fails.

### ISSUE THREAD

**Issue by J-Scriv-Oblak** [aws/aws-sdk-pandas#2445]
### Describe the bug

My imports:
```
import awswrangler as wr
import pandas
```

```
wr.s3.to_parquet(
    df=dataframe, 
    path="s3://{BUCKET_NAME}/{PREFIX}", 
    dataset=True, 
    partition_cols=PARTITION_COLUMNS,
    compression='zstd'
 ```
 
 When running the above line with the layer `arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:9`, the operation experiences an error that shows that the zstd codec isn't installed. 
 
 Error Message: `New Schema Parquet Error Support for codec 'zstd' not built`
 
 I've been trying to isolate the exact library but finding it difficult to do.  My best guess is that its a pyarrow issue but not too positive.

### How to Reproduce

To reproduce, use the `arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:9` lambda layer to create a pandas dataframe.  From there, write the dataframe to a parquet file with zstd compression to s3.

*Note* The functionality works as expected with other compression types (gzip, snappy)

### Expected behavior

There shouldn't be an error when compressing the file with zstd

### OS

Python Lambda Function

### Python version

3.9

### AWS SDK for pandas version

arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:9

**Comment by LeonLuttenberger** [comment]
Hey,

The binary files required for `zstd` to work don't come packaged in with the Lambda layer. The reason for this is because of the 250 MB size limit on the Lambda layer image. In order for the Lambda layer size to be under 250 MB, we had to [only include the most commonly used compression algorithms](https://github.com/aws/aws-sdk-pandas/blob/main/building/lambda/build-lambda-layer.sh#L44), which is why snappy and gzip are supported.

Best regards,
Leon

**Comment by J-Scriv-Oblak** [comment]
Hey @LeonLuttenberger ,

Is there a way we could bring in those binaries in another layer which would your layer could then use?

If not, its sounds like we wouldn't be able to use this layer for our purposes right? we need awswrangler to write the parquet file but compress it with zstd

**Comment by LeonLuttenberger** [comment]
Hey,

You could either create your own layer, where you could include the dependencies you need; or package your dependencies [directly into the Lambda function itself](https://docs.aws.amazon.com/lambda/latest/dg/python-package.html).

Best regards,
Leon
