### ISSUE TITLE
Error with typ='series' for read_json

### ISSUE THREAD

**Issue by ClaudiaSchulz** [aws/aws-sdk-pandas#2453]
### Describe the bug

When using `s3.read_json` with the additional pandas argument `typ='series'` I get the following error: `AttributeError: 'Series' object has no attribute 'select_dtypes'`.
Using pandas.read_json with the same json file and `typ='series'` works without problems.

### How to Reproduce

```
d = {'a': 'dd', 'b': 'yy'}
j = json.dumps(d)
pd.read_json(j, typ='series')
```
This works without problems.

Now save as a json file somewhere on s3
```
 s3 = boto3.resource('s3')
 s3object = s3.Object(bucket, key)
 s3object.put(Body=(bytes(json.dumps(d, indent=4).encode('UTF-8'))))
```

and try to load the json file
```
wr.s3.read_json(s3_path, typ='series')
```
Gives this error:
`AttributeError: 'Series' object has no attribute 'select_dtypes'`

### Expected behavior

No error, same as using pd.read_json()

### OS

Linux

### Python version

3.8

### AWS SDK for pandas version

3.3.0

**Comment by laurentdufloux** [comment]
Not an expert but I don't think `wr.s3.read_json` can return `Series`, its return type is explicitly `DataFrame`. Maybe this should be made more explicit in the documentation.

**Comment by kukushking** [comment]
Hi @ClaudiaSchulz unfortunately `typ="Series` isn't supported at the moment, as a data frame is expected. However, as a workaround, you can read the data via and convert to series after, if required:
```
wr.s3.read_json("...", orient="index")

Out[22]: 
    0
a  dd
b  yy
```

**Comment by ClaudiaSchulz** [comment]
Thanks for the workaround!
