### ISSUE TITLE
Is there a release schedule?

### ISSUE THREAD

**Issue by raaidarshad** [aws/aws-sdk-pandas#2456]
Hi maintainers! Thanks for all that you do. I recently made a PR to this project, and I'm curious if there is a public release schedule (and if that isn't the right term, I just mean when the next version bump and release beyond 3.3.0 would happen). I know I can refer to the main branch of this if needed, but yeah I'm just curious how and when that happens 🙂

**Comment by LeonLuttenberger** [comment]
Hey,

We don't normally have a release schedule, so it all depends on how many features we have ready.

However, it's been over a month since the last release, and there are a few features ready, we'll release a new version in the next few days.

Best regards,
Leon
