### ISSUE TITLE
Repairing table works in the AWS Console, but not when using athena.repair_table

### ISSUE THREAD

**Issue by CarlosDomingues** [aws/aws-sdk-pandas#2461]
### Describe the bug

I'm trying to repair a table using `athena.repair_table`, like so:

```
wr.athena.repair_table(
    database=db_name,
    table=table["name"],
    boto3_session=athena_session,
    workgroup=settings.aws_dev_athena_workgroup,
)
```

This code generates the following exception:

```Python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vscode/.local/lib/python3.11/site-packages/awswrangler/_config.py", line 733, in wrapper
    return function(**args)
           ^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/awswrangler/athena/_utils.py", line 530, in repair_table
    response: Dict[str, Any] = _executions.wait_query(
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/awswrangler/_config.py", line 733, in wrapper
    return function(**args)
           ^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/awswrangler/athena/_executions.py", line 238, in wait_query
    raise exceptions.QueryFailed(response["Status"].get("StateChangeReason"))
awswrangler.exceptions.QueryFailed: [ErrorCategory:USER_ERROR, ErrorCode:DDL_FAILED], Detail:FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask
```

I also tried running the query (`MSCK REPAIR TABLE <TABLE NAME>`) using `athena.read_sql_query`, but got the same error. 

Using boto3 yelds a similar error.

I'm able to run `SELECT` queries just fine.

Running this query on the AWS Console (Athena Query editor) works correctly.

### How to Reproduce

I'm trying to to repair a table in a development account, after copying parquet files from a production account. My idea was to create a prod -> dev sync script. 

### OS

Linux

### Python version

3.11

### AWS SDK for pandas version

3.3.0

**Comment by jaidisido** [comment]
The fact that it's failing with pure boto3 too makes me think that it's not related to our implementation. My guess based on the links below is that some IAM permission might be missing perhaps?
- https://stackoverflow.com/questions/50492748/boto3-and-aws-athena-permission
- https://repost.aws/knowledge-center/athena-aws-glue-msck-repair-table
- https://repost.aws/questions/QU37JMpgqPSjO-qJY7fuSjAQ/msck-repair-table-returns-failed-org-apache-hadoop-hive-ql-exec-ddltask-nu

**Comment by CarlosDomingues** [comment]
I was missing a permission!
