### ISSUE TITLE
OSError: When resolving region for bucket 'ursa-labs-taxi-data': AWS Error [code 99]: curlCode: 35, SSL connect error

### ISSUE THREAD

**Issue by dmarkowvw** [aws/aws-sdk-pandas#2467]
### Describe the bug

When trying to read data from the example bucket (and any other bucket) the error "OSError: When resolving region for bucket 'ursa-labs-taxi-data': AWS Error [code 99]: curlCode: 35, SSL connect error" is displayed although aws environment variables are set and configured as well as the proxy

### How to Reproduce

```
import awswranger as wr
df = wr.s3.read_parquet(path="s3://ursa-labs-taxi-data/2017/")
```

### Expected behavior

Read data from s3 into the dataframe

### OS

Red Hat Enterprise Linux release 8.8 (Ootpa)

### Python version

3.8.16

### AWS SDK for pandas version

3.4.0

### Additional context

Through the aws cli services are reachable

**Comment by LeonLuttenberger** [comment]
Hey,

Does your boto3 session have access to the region information? You can try to run these commands after setting the default AWS region using an environment variable:
```bash 
export AWS_DEFAULT_REGION=us-east-1
```

Let me know if this works, or if it gives you a different error.

Best regards,
Leon

**Comment by dmarkowvw** [comment]
Hi Leon

Thanks for your reply. Unfortunately this didn't resolve it. I get the same error message. I suspect that the curl version on RHEL 8 is too old.

Regards
Daniel
