### ISSUE TITLE
Allow glue_table_settings attribute on to_iceberg

### ISSUE THREAD

**Issue by frenchytheasian** [aws/aws-sdk-pandas#2469]
**Is your idea related to a problem? Please describe.**
Currently, I'm working with Iceberg tables in Athena. When I want to add comments to the table or columns, I have to make a separate boto3 call to glue. 

**Describe the solution you'd like**
wr.s3.to_parquet contains a glue_table_settings parameter which allows users to add a GlueTableSettings object to configure the glue catalog and update data in one function call. I was wondering if its possible or would make sense to do something similar for the to_iceberg function?

I would willing to open a PR and take a stab at this if it makes sense to add.

**Comment by jaidisido** [comment]
Hi, unlike `s3.to_parquet` which makes a Glue call to create a table in the catalog, the `athena.to_iceberg` API creates the table via an Athena [query](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/athena/_write_iceberg.py#L44). It means that it's limited by the parameters exposed [here](https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg-creating-tables.html). We expose the `additional_table_parameters` in the API but comments are not one of those listed. PRs are always welcome though

**Comment by frenchytheasian** [comment]
@jaidisido Ahh I see. Rather than creating a whole glue_table_settings parameter, I think a column_comments parameter might make more sense. I noticed that you can add column comments in the athena sql. I think this could be done by injecting the values of a column comments parameter into the Athena query. I can work on implementing this
