### ISSUE TITLE
Saving a Pandas DataFrame to Parquet with `s3.to_parquet`: `object` fields are cast to `INT32` when all null

### ISSUE THREAD

**Issue by isaaclangley** [aws/aws-sdk-pandas#2472]
### Describe the bug

I noticed some (potentially) unexpected behaviour with the `s3.to_parquet` method recently.

When the `s3.to_parquet` method is used to save a pandas DF with an all-null `object` column, the resulting parquet field has type `INT32`.

This feels unexpected, as `object` is typically used to store string values or mixed-type values in Pandas, and thus I would expect the `BYTE_ARRAY` or `UTF8` parquet type to be more appropriate. I know that this is a tricky one, as `object` columns can be mixed-type, and thus there can be no _exact_ parquet equivalent, but in practical terms the lack of a native Pandas string type means that `object` is largely used to store string values. 

This behaviour can be particularly surprising if `s3.to_parquet` is used in a process that writes an all-null `object` field having previously written non-null `object` string values. In this case, the parquet field will change from a binary  (`BYTE_ARRAY` or `UTF8`)  to `INT32`, despite the data type of the pandas DataFrame remaining unchanged.

### How to Reproduce

```
import pandas as pd
import awswrangler as wr
import pyarrow.parquet as pq


# Create a DF with an all-null object column
df = pd.DataFrame({"col1":[1,2,3]})
df["col2"] = pd.Series([None]*len(df), dtype=str)


# Save to S3 as parquet
wr.s3.to_parquet(
    df=df,
    path="<S3 PATH>",
    compression="gzip"
)

# Check schema of parquet file (note that `col2` is int32)
metadata = pq.read_metadata("<S3 PATH>")
metadata.schema
>>> required group field_id=-1 schema {
>>>     optional int64 field id=-1 col1;
>>>     optional int32 field id=-1 col2 (Null);
>>> }
```

### Expected behavior

`object` fields in Pandas should be saved as `BYTE_ARRAY` or `UTF8` in parquet via `s3.to_parquet`

### OS

Linux

### Python version

3.8.10

### AWS SDK for pandas version

2.9.0

**Comment by jaidisido** [comment]
That is a quirk of the pyarrow ParquetWriter that we use under the hood - here is an even simpler example:
```
import pyarrow as pa
import pyarrow.parquet as pq

table = pa.table({
    "col1": [i for i in range(100)],
    "col2": [None] * 100,
})
print(table.schema)

path = "example.parquet"
writer = pq.ParquetWriter(path, table.schema)
writer.write_table(table)
writer.close()

metadata = pq.read_metadata(path)
print(metadata.schema)
```
returns:
```
col1: int64
col2: null
<pyarrow._parquet.ParquetSchema object at 0x10c64cfc0>
required group field_id=-1 schema {
  optional int64 field_id=-1 col1;
  optional int32 field_id=-1 col2 (Null);
}
```

That being said when reading the data back with `wr.s3.read_parquet`, the column is resolved to `object`:
```
wr.s3.read_parquet(path, pyarrow_additional_kwargs={"types_mapper": None}).dtypes

col1     int64
col2    object
dtype: object
```
