### ISSUE TITLE
Possible memory leak in wr.s3.to_parquet

### ISSUE THREAD

**Issue by KardaChalak** [aws/aws-sdk-pandas#2476]
### Describe the bug

I'm reading 120 parquet files of about 1.2 MB with nested data and then writing it file by file. I have 2.5 GiB of ram. The memory drains slowly until the program gets killed at around the 70th file.

### How to Reproduce

```
import awswrangler as wr
import boto3

read_path = "s3://bucket_read_name/"
write_path = "s3://bucket_write_name/"

boto3_session = boto3.Session(
    aws_access_key_id="***",
    aws_secret_access_key="***",
)
df_iterator = wr.s3.read_parquet(
    read_path , chunked=True, boto3_session=boto3_session
)

for partition, df in enumerate(df_iterator):
    wr.s3.to_parquet(
        df,
        f"{write_path}.{partition}",
        index=False,
        boto3_session=boto3_session,
    )
```

Dependencies 
```
awswrangler==3.4.0
boto3==1.28.56
botocore==1.31.56
jmespath==1.0.1
numpy==1.26.0
packaging==23.1
pandas==2.1.1
pyarrow==13.0.0
python-dateutil==2.8.2
pytz==2023.3.post1
s3transfer==0.7.0
six==1.16.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.16
```

### Expected behavior

Being able to read and write all the files.

### Screenshots

<img width="1067" alt="image" src="https://github.com/aws/aws-sdk-pandas/assets/11937766/d66565be-f072-441a-92e5-ec7e94ed726c">

### OS

Ubuntu dev container on a mac. mcr.microsoft.com/devcontainers/base:ubuntu

### Python version

3.10.13

### AWS SDK for pandas version

3.4.0

**Comment by KardaChalak** [comment]
Solved by using .convert_dtypes()

```
import awswrangler as wr
import boto3

read_path = "s3://bucket_read_name/"
write_path = "s3://bucket_write_name/"

boto3_session = boto3.Session(
    aws_access_key_id="***",
    aws_secret_access_key="***",
)
df_iterator = wr.s3.read_parquet(
    read_path , chunked=True, boto3_session=boto3_session
)

for partition, df in enumerate(df_iterator):
    wr.s3.to_parquet(
        df.convert_dtypes(),
        f"{write_path}.{partition}",
        index=False,
        boto3_session=boto3_session,
```

**Comment by pisskidney** [comment]
@KardaChalak how did you even arrive at that solution?

I had the exact same problem as you described, but I would've never thought of using convert_dytpes just to solve a memory leak.

**Comment by KardaChalak** [comment]
@pisskidney 

Happy that it worked for you too!

After being frustrated for a while I decided to write a subset of the columns with specific types and iteratively add columns until the memory problem reappeared. The problem didn't reappear and I searched for a method to convert the dtypes generally.
