### ISSUE TITLE
read_sql_table does not return the entire table

### ISSUE THREAD

**Issue by ldoff-innovative** [aws/aws-sdk-pandas#2481]
### Describe the bug

When I run:

```
sales = wr.athena.read_sql_table(
        table="sales",
        database=glue_catalog_db,
        boto3_session=session,
    )
```

The results are 38,498 records. When I run SELECT * directly on Athena for the same database and table, there are 242,883 records. The Glue/Athena table has partitions.

I tested this by querying directly to Athena using the boto library and running a select * query. The results were 242,883 records. This was tested using the same python version and library versions.

So using awswrangler read_sql_table, I only get a subset of the database. When I run a query directly on Athena or using the boto library I get all the results. 

I'm using 3.4.0 of awswrangler. 

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
Have a table with more than 40,000 records. Run the command to pull all records. The results will be maxed at 38,498 records.

### Expected behavior

The expected behavior is to return all records from the database.

### OS

Mac, Lambda

### Python version

3.9.18

### AWS SDK for pandas version

1.28.58

**Comment by LeonLuttenberger** [comment]
Hey,

I have not been able to recreate the error with dummy data.

Can you try seeing if you error when passing either `ctas_approach=False` or `unload_approach=True`? Also, is there any place in the code where you're modifying the `wr.config` variables (such as `max_cache_seconds`)?

Cheers,
Leon

P.S. the way I created the dummy data was using this snippet:
```python
    num_rows = 45_000
    frame_in = pd.DataFrame({"id": list(range(num_rows)), "par": ["foo", "bar", "baz"] * (num_rows // 3)})

    wr.s3.to_parquet(
        df=frame_in,
        path=path,
        index=False,
        dataset=True,
        mode="overwrite",
        database=glue_database,
        table=glue_table,
        partition_cols=["par"],
    )

    frame_out = wr.athena.read_sql_table(
        table=glue_table,
        database=glue_database,
        ctas_approach=ctas_approach,
        unload_approach=unload_approach,
        s3_output=path2,
        keep_files=False,
    )
```
