### ISSUE TITLE
Write partitioned dataset and still keep partition columns in respective files possible?

### ISSUE THREAD

**Issue by Zyntogz** [aws/aws-sdk-pandas#2487]
Hello,

normally parquet-files are viewed as a dataset where parts of the parquet-file-location contain some data. However, we have a consumer that is unable to respect the partitioning string and enrich contained information to downloaded parquet file content. Hence, we is always downloading the "raw" parquet file and misses the columns used for partitioning.

Is there an option / argument to keep partition columns in written parquet file(s)? Athena can handle this scenario and it seems to have no further downsides except normally unnecessary data duplication and hence, higher parquet file size.

Many thanks :)

**Comment by kukushking** [comment]
Hi @Zyntogz there is no option atm unfortunately, but it is a worthwhile feature. It would also require an equivalent option when reading to avoid adding duplicate columns
