### ISSUE TITLE
AWSWrangler with optional Redshift Module on Glue jobs

### ISSUE THREAD

**Issue by hrpitta** [aws/aws-sdk-pandas#2488]
First of all thank you guys for the amazing Library!
Can you help me with the below question, couldn't find on the docs.
Please how to install the optional module for Redshift on Glue, I've tried the 
--additional-python-modules pyarrow==7,awswrangler[redshift] but it didn't work. I'm using the version 2.20 --additional-python-modules pyarrow==7,awswrangler==2.20, but I need some enhancements from the newer releases.
Thanks in advance for your help.
Best,
Hugo

**Comment by jaidisido** [comment]
You can install the `redshift_connector` to add the dependency:
```
--additional-python-module awswrangler==3.4.0,redshift-connector==2.0.915
```

**Comment by hrpitta** [comment]
Thank you so much @jaidisido, it worked like a charm!
