### ISSUE TITLE
 File "<stdin>", line 1, in <module> ModuleNotFoundError: No module named 'awswrangler'

### ISSUE THREAD

**Issue by taupirho** [aws/aws-sdk-pandas#2501]
### Describe the bug

I'm following this tutorial on awswrangler: (https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/036%20-%20Distributing%20Calls%20with%20Glue%20Interactive%20Sessions%20on%20Ray.html)

cell 1
====
!pip install "awswrangler[modin]"  
​
Defaulting to user installation because normal site-packages is not writeable
Collecting awswrangler[modin]
  Using cached awswrangler-3.4.1-py3-none-any.whl (396 kB)
Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/jupyter-user/.local/lib/python3.9/site-packages (from awswrangler[modin]) (1.28.2)
Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/jupyter-user/.local/lib/python3.9/site-packages (from awswrangler[modin]) (1.31.2)
Requirement already satisfied: numpy<2.0,>=1.18 in /home/jupyter-user/.local/lib/python3.9/site-packages (from awswrangler[modin]) (1.25.1)
Requirement already satisfied: packaging<24.0,>=21.1 in /home/jupyter-user/.local/lib/python3.9/site-packages (from awswrangler[modin]) (23.1)
Requirement already satisfied: pandas<3.0.0,>=1.2.0 in /home/jupyter-user/.local/lib/python3.9/site-packages (from awswrangler[modin]) (2.0.0)
Requirement already satisfied: pyarrow>=7.0.0 in /home/jupyter-user/.local/lib/python3.9/site-packages (from awswrangler[modin]) (13.0.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/jupyter-user/.local/lib/python3.9/site-packages (from awswrangler[modin]) (4.7.1)
Requirement already satisfied: modin<0.24.0,>=0.23.0 in /home/jupyter-user/.local/lib/python3.9/site-packages (from awswrangler[modin]) (0.23.1)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/jupyter-user/.local/lib/python3.9/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler[modin]) (1.0.1)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /home/jupyter-user/.local/lib/python3.9/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler[modin]) (0.6.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/jupyter-user/.local/lib/python3.9/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler[modin]) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/jupyter-user/.local/lib/python3.9/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler[modin]) (1.26.16)
Requirement already satisfied: fsspec>=2021.07.0 in /home/jupyter-user/.local/lib/python3.9/site-packages (from modin<0.24.0,>=0.23.0->awswrangler[modin]) (2023.10.0)
Requirement already satisfied: psutil>=5.8.0 in /home/jupyter-user/.local/lib/python3.9/site-packages (from modin<0.24.0,>=0.23.0->awswrangler[modin]) (5.9.5)
Requirement already satisfied: pytz>=2020.1 in /home/jupyter-user/.local/lib/python3.9/site-packages (from pandas<3.0.0,>=1.2.0->awswrangler[modin]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/jupyter-user/.local/lib/python3.9/site-packages (from pandas<3.0.0,>=1.2.0->awswrangler[modin]) (2023.3)
Requirement already satisfied: six>=1.5 in /home/jupyter-user/.local/lib/python3.9/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler[modin]) (1.16.0)
Installing collected packages: awswrangler
Successfully installed awswrangler-3.4.1

[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: pip install --upgrade pip

cell2
====
import awswrangler as wr

 File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'awswrangler'

### How to Reproduce

Just followed the tutorial at https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/036%20-%20Distributing%20Calls%20with%20Glue%20Interactive%20Sessions%20on%20Ray.html

Here is the output of me doing a  !python -m pip list 

Package                             Version
----------------------------------- ----------
aiofiles                            22.1.0
aiohttp                             3.8.6
aiohttp-cors                        0.7.0
aiosignal                           1.3.1
aiosqlite                           0.19.0
amazon-codewhisperer-jupyterlab-ext 1.0.3
anyio                               3.7.1
argon2-cffi                         21.3.0
argon2-cffi-bindings                21.2.0
arrow                               1.2.3
asn1crypto                          1.5.1
asttokens                           2.2.1
async-timeout                       4.0.3
attrs                               23.1.0
autovizwidget                       0.20.5
aws-glue-sessions                   0.38.1
awscli                              1.29.2
awswrangler                         3.4.1
Babel                               2.12.1
backcall                            0.2.0
beautifulsoup4                      4.12.2
bleach                              6.0.0
blessed                             1.20.0
boto3                               1.28.2
botocore                            1.31.2
cachetools                          5.3.2
certifi                             2023.5.7
cffi                                1.15.1
charset-normalizer                  3.2.0
click                               8.1.4
colorama                            0.4.4
colorful                            0.5.5
comm                                0.1.3
debugpy                             1.6.7
decorator                           5.1.1
defusedxml                          0.7.1
distlib                             0.3.7
docutils                            0.16
exceptiongroup                      1.1.2
executing                           1.2.0
fastjsonschema                      2.17.1
filelock                            3.12.4
fqdn                                1.5.1
frozenlist                          1.4.0
fsspec                              2023.10.0
google-api-core                     2.12.0
google-auth                         2.23.3
googleapis-common-protos            1.61.0
gpustat                             1.1.1
grpcio                              1.59.0
hdijupyterutils                     0.20.5
idna                                3.4
importlib-metadata                  6.8.0
ipykernel                           6.24.0
ipython                             8.14.0
ipython-genutils                    0.2.0
ipywidgets                          8.0.7
isoduration                         20.11.0
jedi                                0.18.2
Jinja2                              3.1.2
jmespath                            1.0.1
json5                               0.9.14
jsonpointer                         2.4
jsonschema                          4.18.2
jsonschema-specifications           2023.6.1
jupyter                             1.0.0
jupyter_client                      8.3.0
jupyter-console                     6.6.3
jupyter_core                        5.3.1
jupyter-events                      0.6.3
jupyter-lsp                         2.2.0
jupyter_server                      2.7.0
jupyter_server_fileid               0.9.0
jupyter_server_terminals            0.4.4
jupyter_server_ydoc                 0.8.0
jupyter-ydoc                        0.2.4
jupyterlab                          3.6.4
jupyterlab-lsp                      4.0.0
jupyterlab-pygments                 0.2.2
jupyterlab_server                   2.23.0
jupyterlab-widgets                  3.0.8
lxml                                4.9.3
markdown-it-py                      3.0.0
MarkupSafe                          2.1.3
matplotlib-inline                   0.1.6
mdurl                               0.1.2
mistune                             3.0.1
modin                               0.23.1
msgpack                             1.0.7
multidict                           6.0.4
nbclassic                           1.0.0
nbclient                            0.8.0
nbconvert                           7.6.0
nbformat                            5.9.1
nest-asyncio                        1.5.6
nose                                1.3.7
notebook                            6.5.4
notebook_shim                       0.2.3
numpy                               1.25.1
nvidia-ml-py                        12.535.108
opencensus                          0.11.3
opencensus-context                  0.1.3
overrides                           7.3.1
packaging                           23.1
pandas                              2.0.0
pandocfilters                       1.5.0
parso                               0.8.3
pexpect                             4.8.0
pickleshare                         0.7.5
pip                                 23.1.2
platformdirs                        3.8.1
plotly                              5.15.0
prometheus-client                   0.17.1
prompt-toolkit                      3.0.39
protobuf                            4.24.4
psutil                              5.9.5
ptyprocess                          0.7.0
pure-eval                           0.2.2
py-spy                              0.3.14
pyarrow                             13.0.0
pyasn1                              0.5.0
pyasn1-modules                      0.3.0
pycparser                           2.21
pydantic                            1.10.13
Pygments                            2.15.1
pykerberos                          1.2.4
python-dateutil                     2.8.2
python-json-logger                  2.0.7
pytz                                2023.3
PyYAML                              5.4.1
pyzmq                               25.1.0
qtconsole                           5.4.3
QtPy                                2.3.1
ray                                 2.6.3
redshift-connector                  2.0.915
referencing                         0.29.1
requests                            2.31.0
rfc3339-validator                   0.1.4
rfc3986-validator                   0.1.1
rich                                13.4.2
rpds-py                             0.8.10
rsa                                 4.7.2
s3transfer                          0.6.1
scramp                              1.4.4
Send2Trash                          1.8.2
setuptools                          58.1.0
six                                 1.16.0
smart-open                          6.4.0
sniffio                             1.3.0
soupsieve                           2.4.1
stack-data                          0.6.2
tenacity                            8.2.2
terminado                           0.17.1
tinycss2                            1.2.1
tomli                               2.0.1
tornado                             6.3.2
traitlets                           5.9.0
typing_extensions                   4.7.1
tzdata                              2023.3
uri-template                        1.3.0
urllib3                             1.26.16
virtualenv                          20.21.0
wcwidth                             0.2.6
webcolors                           1.13
webencodings                        0.5.1
websocket-client                    1.6.1
widgetsnbextension                  4.0.8
y-py                                0.5.9
yarl                                1.9.2
ypy-websocket                       0.8.2
zipp                                3.16.1

[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: pip install --upgrade pip

### Expected behavior

I expected to be able to import the awswrangler library

### Screenshots

![Screenshot 2023-10-26 091713](https://github.com/aws/aws-sdk-pandas/assets/21940629/0c8ab2f3-73eb-41c7-bfb9-4236c039d98e)

### OS

Windows 11

### Python version

3.9.9

### AWS SDK for pandas version

3.4.1

### Additional context

Running on Windows 11 Home version 22H2

**Comment by taupirho** [comment]
I also tried using the additional_python_modules ['awswrangler'] magic, then import awswrangler produced this output

uthenticating with environment variables and user-defined glue_role_arn: arn:aws:iam::696353118745:role/awsglueservicerole
Trying to create a Glue session for the kernel.
Worker Type: Z.2X
Number of Workers: 5
Session ID: fa980785-a2c9-4b43-b704-bbaf2c485e4a
Job Type: glueray
Applying the following default arguments:
--glue_kernel_version 0.38.1
--enable-glue-datacatalog true
--auto-scaling-ray-min-workers 1
--additional-python-modules 'awswrangler'
Waiting for session fa980785-a2c9-4b43-b704-bbaf2c485e4a to get into ready status...
Session fa980785-a2c9-4b43-b704-bbaf2c485e4a has been created.
  File "<stdin>", line 19, in <module>
  File "<stdin>", line 12, in <module>
  File "/opt/amazon/workload-runtime/Ray2.4/python3.9/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/amazon/workload-runtime/Ray2.4/python3.9/lib/python3.9/site-packages/ray/_private/worker.py", line 2523, in get
    raise value
ray.exceptions.RuntimeEnvSetupError: Failed to set up runtime environment.
Traceback (most recent call last):
  File "/opt/amazon/workload-runtime/Ray2.4/python3.9/lib/python3.9/site-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 357, in _create_runtime_env_with_retry
    runtime_env_context = await asyncio.wait_for(
  File "/opt/amazon/workload-runtime/Ray2.4/python3.9/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/opt/amazon/workload-runtime/Ray2.4/python3.9/lib/python3.9/site-packages/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 312, in _setup_runtime_env
    await create_for_plugin_if_needed(
  File "/opt/amazon/workload-runtime/Ray2.4/python3.9/lib/python3.9/site-packages/ray/_private/runtime_env/plugin.py", line 252, in create_for_plugin_if_needed
    size_bytes = await plugin.create(uri, runtime_env, context, logger=logger)
  File "/opt/amazon/workload-runtime/Ray2.4/python3.9/lib/python3.9/site-packages/ray/_private/runtime_env/pip.py", line 473, in create
    return await task
  File "/opt/amazon/workload-runtime/Ray2.4/python3.9/lib/python3.9/site-packages/ray/_private/runtime_env/pip.py", line 455, in _create_for_hash
    await PipProcessor(
  File "/opt/amazon/workload-runtime/Ray2.4/python3.9/lib/python3.9/site-packages/ray/_private/runtime_env/pip.py", line 361, in _run
    await self._install_pip_packages(
  File "/opt/amazon/workload-runtime/Ray2.4/python3.9/lib/python3.9/site-packages/ray/_private/runtime_env/pip.py", line 337, in _install_pip_packages
    await check_output_cmd(pip_install_cmd, logger=logger, cwd=cwd, env=pip_env)
  File "/opt/amazon/workload-runtime/Ray2.4/python3.9/lib/python3.9/site-packages/ray/_private/runtime_env/utils.py", line 101, in check_output_cmd
    raise SubprocessCalledProcessError(
ray._private.runtime_env.utils.SubprocessCalledProcessError: Run cmd[9] failed with the following details.
Command '['/tmp/ray/session_2023-10-27_07-49-57_590470_1678/runtime_resources/pip/3df5f0bf1a8ea11d08aea8f90e4c748f7e1ae468/virtualenv/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', '--no-cache-dir', '-r', '/tmp/ray/session_2023-10-27_07-49-57_590470_1678/runtime_resources/pip/3df5f0bf1a8ea11d08aea8f90e4c748f7e1ae468/requirements.txt']' returned non-zero exit status 1.
Last 50 lines of stdout:
    ERROR: Invalid requirement: "'awswrangler'" (from line 1 of /tmp/ray/session_2023-10-27_07-49-57_590470_1678/runtime_resources/pip/3df5f0bf1a8ea11d08aea8f90e4c748f7e1ae468/requirements.txt)


2023-10-27 07:50:03,187	INFO worker.py:1432 -- Connecting to existing Ray cluster at address: 2600:1f10:4f79:8b20:31f8:648:54b9:cfc5:6379...
2023-10-27 07:50:03,196	INFO worker.py:1616 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:8265

**Comment by jaidisido** [comment]
Thanks for raising this @taupirho. It looks like the installation of additional modules in AWS Glue interactive sessions has somehow [changed](https://docs.aws.amazon.com/glue/latest/dg/is-using-ray-configuration.html) and requires using `%additional_python_modules.` I have updated the [tutorial](https://github.com/aws/aws-sdk-pandas/blob/main/tutorials/036%20-%20Distributing%20Calls%20with%20Glue%20Interactive%20Sessions%20on%20Ray.ipynb) to reflect that.
