### ISSUE TITLE
Enable current spark on athena to support different table formats

### ISSUE THREAD

**Issue by rajagurunath** [aws/aws-sdk-pandas#2503]
Hi Team, 

We are piloting Spark on Athena feature (which is recently merged in this PR https://github.com/aws/aws-sdk-pandas/pull/2314 ) 

**Problem:** 
Currently, we are able to use a spark on Athena for plain parquet tables. But not able to use the table formats, though Spark on Athena supports all [three table formats](https://docs.aws.amazon.com/athena/latest/ug/notebooks-spark-table-formats.html) (Delta, Hudi, Iceberg). 
 - In OSS spark, we add config related to Table formats and a spark session will created with this table format-related catalog and extensions. but spark on Athena we are not able to create the new spark session, the session was prepared by spark on Athena service itself.  so we need to pass the relevant properties to the service itself.

**Proposed Solution**
Actually, Spark on Athena accepts this table format related **SparkProperties**, please check the boto documentation [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena/client/start_session.html#start-session)

currently `awswrangler` taking only **AdditionalConfigs** from the user : https://github.com/aws/aws-sdk-pandas/blob/64868b652598ebabd749a24bf6928ab67e92cb7b/awswrangler/athena/_spark.py#L129-L141

This solution proposes to add a new argument called spark_properties to the `create_spark_session` function and pass the properties to 'engine_configuration`. 

so that the user can pass relevant table properties and use the required table formats:

``` 

for Delta:
{
    "spark.sql.catalog.spark_catalog": "org.apache.spark.sql.delta.catalog.DeltaCatalog",
    "spark.sql.extensions": "io.delta.sql.DeltaSparkSessionExtension"
}

for Hudi

{
    "spark.sql.catalog.spark_catalog": "org.apache.spark.sql.hudi.catalog.HoodieCatalog",
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
    "spark.sql.extensions": "org.apache.spark.sql.hudi.HoodieSparkSessionExtension"
} 
```
if these Solutions seem good, **I am more than happy to contribute to this enhancement!** Thanks!

**Comment by kukushking** [comment]
Hi @rajagurunath thanks for opening this. Yes the solution makes sense, we are more than happy to accept a contribution!

**Comment by rajagurunath** [comment]
Thanks @kukushking Created a PR https://github.com/aws/aws-sdk-pandas/pull/2508 please review and let me know your thoughts !

**Comment by kukushking** [comment]
Closing as the PR is merged. Thanks @rajagurunath for contribution!
