### ISSUE TITLE
Connection pool is full, discarding connection; xxxx; Connection pool size: 10

### ISSUE THREAD

**Issue by ryansunmoon** [aws/aws-sdk-pandas#2504]
Hi all,

I am trying to use wr.s3.read_parquet to read multiple files into dataframe at once, but it reported the following issues. 

Connection pool is full, discarding connection; xxxx; Connection pool size: 10

In conducting research, it seems that wr.s3.read_parquet has a parameter call "boto3_session" where I am supposed to pass in the boto3 session object.

However, when I look at the boto3 documentation, it seems that I cannot specify the max pool connection at session object. Instead, i have to create a client/resource object form a session object and specify the max pool connection there. As you can see from the documentation below: I am not able to specify the max pool size for the boto3 session object.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html
Question: how do I specify the number of max pool for wr.s3.read_parquet file?

(in addition, I also tried to change the parameter for use_threads, not working either)

Thanks!

**Comment by kukushking** [comment]
Hi @ryansunmoon you can provide `max_pool_connections ` and other boto config via [Global Configurations](https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/021%20-%20Global%20Configurations.html#wr.config).

**Comment by ryansunmoon** [comment]
@kukushking Thank you very much for the reply. It works!

**Comment by kukushking** [comment]
@ryansunmoon Happy to help! :)
