### ISSUE TITLE
Allow Parallel overload for redshift.unload_to_files method

### ISSUE THREAD

**Issue by DylDelport** [aws/aws-sdk-pandas#2505]
**Is your feature request related to a problem? Please describe.**
Currently, this is hardcoded and produces multiple files in the S3 destination. Users may want the option to only generate one file.

**Describe the solution you'd like**
Similar to the other overloads, covert this to a parameter.

**Describe alternatives you've considered**
The alternative is to not use this method and run the UNLOAD statement as an SQL statment.

**Additional context**
![image](https://github.com/aws/aws-sdk-pandas/assets/31354787/895983c4-c328-4f59-a2ff-214b9afecca4)

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by kukushking** [comment]
Hi @DylDelport thanks for opening this - added in #2507. 

Note `parallel=False` does not guarantee a single file will be produced as they will be split into chunks of max 6.2 GB. More in [User guide](https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html).

**Comment by DylDelport** [comment]
Thanks @kukushking
