### ISSUE TITLE
Exponential backoff 

### ISSUE THREAD

**Issue by awspiv** [aws/aws-sdk-pandas#2509]
**Is your idea related to a problem? Please describe.**
When using awswrangler with millions of calls to databases, I am constantly receive throttling errors.  I have had to write an exponential backoff decorator in python and create wrappers for all of the wrangler functions I am using.  

**Describe the solution you'd like**
Since throttling is quite a common issue, I suggest adding it internal to awswrangler.  (I can provide my code if needed)

**Comment by kukushking** [comment]
HI @awspiv there is a [retry with exponential backoff utility](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/_utils.py#L806) and corresponding [decorator](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/_utils.py#L771). I suggest to perhaps try change retry config?

**Comment by awspiv** [comment]
Ah! Ok cool, let me try and I will close the issue on confirmation.
