### ISSUE TITLE
New pyarrow v14 raises FutureWarning: promote has been superseded by mode='default'

### ISSUE THREAD

**Issue by tamas7** [aws/aws-sdk-pandas#2510]
### Describe the bug

The new release of pyarrow v14 (Nov 1) looks like it introduced a breaking change.
Using `awswrangler.s3.select_query()` fails with the following error message:

FutureWarning: promote has been superseded by mode='default'

As a temporary workaround, pinning `pyarrow==13.0.0` fixes the issue.
Tested with both awswrangle 3.4.0 and 3.4.1 with the same results.

### How to Reproduce

```python
awswrangler.s3.select_query(
        sql=query,
        path=f"s3://bucket/file.csv",
        input_serialization="CSV",
        input_serialization_params={"FileHeaderInfo": "Use"},
)
```
 

### OS

Linux (AWS Lambda)

### Python version

3.9

### AWS SDK for pandas version

3.4.0

**Comment by jaidisido** [comment]
Is there an actual error being raised besides the warning? I tested the example below with pyarrow 14:
```
df = wr.s3.select_query(
    sql="SELECT * FROM s3object",
    path="s3://humor-detection-pds/Humorous.csv",
    input_serialization="CSV",
    input_serialization_params={
        "FileHeaderInfo": "Use",
        "RecordDelimiter": "\r\n",
    },
    scan_range_chunk_size=1024*1024*32,  # override range of bytes to query, by default 1Mb
    use_threads=True,
)
df.head()
```python
It shows the warning but I still get the results without issues.

Looking at the pyarrow [code](https://github.com/Fokko/arrow/blob/a216d48122e34e4419a6f29f973bd27e030bc19b/python/pyarrow/table.pxi#L5089), it seems they tried to make the change backward compatible

**Comment by tamas7** [comment]
Hi thanks for the quick reply! Upon closer inspection the issue only seems to happen when the code is run through pytest. Executing it directly does raise the warning, but it doesn't seem to cause interruption. Perhaps a better fix then would be to use `filterwarnings` (directly in the tests or in the pytest.ini file) instead of the dependency downgrade for pyarrow.

Although it might look like the issue is "coming from" awswrangler, not sure if this requires a change, so I'm happy if the issue is closed.

**Comment by jorisvandenbossche** [comment]
FWIW, the warning comes from this code in awswrangler:

https://github.com/aws/aws-sdk-pandas/blob/24e6e81270f426072e54ab5336d5a022c8537a19/awswrangler/_utils.py#L892-L894

This is using `promote=True`, and this has been superseded by a new keyword `promote_options` (I see that the warning message uses the wrong keyword name though, will fix that!)

PyArrow indeed kept backwards compatibility, so on the short term the behaviour should stay the same. But if you want that users of awswrangler don't see this (for them useless, as they can't do anything about it) warning, it's the above code in awswrangler that needs to be changed to use the new keyword (or the new or the old depending on the pyarrow version, if you want to keep supporting multiple versions of pyarrow).

**Comment by troyswanson** [comment]
I'm experiencing this warning as well. Seems like it is something that should be patched on the AWS Wrangler side.

**Comment by simplew2011** [comment]
pyarrow==12.0.0 is ok.

**Comment by Thijss** [comment]
@jaidisido 

Seems like an easy fix: https://github.com/aws/aws-sdk-pandas/issues/2510#issuecomment-1809828527

Could we re-open this to implement the change?

**Comment by jaidisido** [comment]
pyarrow is completely [uncapped](https://github.com/aws/aws-sdk-pandas/blob/main/pyproject.toml#L35) from our side. Implementing a change to the new keyword only would mean that we must restrict the dependency to the latest version which we haven't been able to do because some of our other dependencies (e.g. ray) still require earlier versions of pyarrow

**Comment by bgupta** [comment]
Note for those running into this. You can add this to your code in your import block:

`import warnings
# Suppress specific FutureWarning from awswrangler module
warnings.filterwarnings("ignore", message="promote has been superseded by promote_options='default'.", category=FutureWarning, module="awswrangler")
import awswrangler as wr`

Note: this filter could be baked right into the wrangler itself.
