### ISSUE TITLE
Add ResultReuseConfiguration parameter to Athena query 

### ISSUE THREAD

**Issue by sivankumar86** [aws/aws-sdk-pandas#2511]
**Is your idea related to a problem? Please describe.**
   I would like to enable cache feature in Athena however, there is no option to pass "ResultReuseConfiguration"

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena/client/start_query_execution.html

**Comment by LeonLuttenberger** [comment]
Hey,

We have our own implementation of reusing Athena queries, which you can find an example of [here](https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/019%20-%20Athena%20Cache.html#Second-execution-with-CACHE-(400x-faster)). The reason we have our own implementation is that it precedes the `ResultReuseConfiguration` option, which boto3 introduced with version `1.26.4`.

However, now that boto3 has its own implementation, we will look into refactoring our implementation to make use of `ResultReuseConfiguration` behind the scenes.

Thanks for bringing this to our attention!

Cheers,
Leon

**Comment by DavidKatz-il** [comment]
@LeonLuttenberger 
Any update on this?
