### ISSUE TITLE
Ensure compatibility with Lambda 3.10 runtime (botocore, urllib issue)

### ISSUE THREAD

**Issue by FredStober** [aws/aws-sdk-pandas#2512]
### Describe the bug

The awswrangler lambda layer Version 3.4.1 pulls in urllib==2.0.7.
However urllib>=2 is not compatible with botocore==1.29.90 that is pre-installed in the AWS Lambda Runtime.
This leads to the error message: "ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'"

**You need to either require botocore>1.29.123 OR urllib<2.**
Reference: https://github.com/boto/botocore/pull/2924

### How to Reproduce

Add the awswrangler lambda layer to a Lambda Function with the 3.10 runtime.

### Expected behavior

The lambda function can be loaded

### OS

Linux

### Python version

3.10

### AWS SDK for pandas version

3.4.1

**Comment by kukushking** [comment]
Hi @FredStober thanks for opening this! Older OpenSSL in AL2 might not allow us to upgrade but Iet me give it a try. Otherwise will pin urllib3<2. Please use 3.4.0 layers in the meantime.
