### ISSUE TITLE
to_parquet doesn't support partition_cols of index col

### ISSUE THREAD

**Issue by zzy1232** [aws/aws-sdk-pandas#2520]
### Describe the bug

Trying to write pandas data frame (multi indexed df) into parquet dataset by using s3.to_parquet and partition it using one of the index cols. It seems working properly with just pandas locally, but awswrangler is erroring out saying "[col] not found in axis"

### How to Reproduce

```
df = pd.DataFrame(np.random.rand(6, 3), columns=['a', 'b', 'c'],  
    index=pd.MultiIndex.from_product([pd.date_range('2023-11-15'), periods=3, freq='B', name='date'),
        [1, 2]], names=['date', 'id']))

wr.s3.to_parquet(df, path='xxxxxxxxxx', dataset=True, partition_cols=['date'], index=True)
```

### Expected behavior

Treat the index column the same as data frame column when used by partition.

### OS

Linux

### Python version

3.10

### AWS SDK for pandas version

3.4.1

**Comment by kukushking** [comment]
Hi @zzy1232 partitioning by index cols is not supported at the moment.

**Comment by zzy1232** [comment]
Thanks @kukushking. Is there any plan for the enhancement?
