### ISSUE TITLE
s3._write._validate_args causes OOM on Ray

### ISSUE THREAD

**Issue by bobthemighty** [aws/aws-sdk-pandas#2532]
### Describe the bug

I'm running a small-ish ETL job on Ray, pivoting and munging some data.
The job fails with an OOM during `awswrangler.s3.to_parquet`

Logs and some sample code are in this gist https://gist.github.com/bobthemighty/1973221989981fee121a03a4b18f6f4e

The traceback suggests that the problem occurs because in _validate_args, we check `df.empty`, which allocates an enormous numpy array on one node, and blows up.

I'm happy to do some work to fix this, but I'm not sure where and how to solve the problem. Is my understanding here correct?

### How to Reproduce

Write a large dataset with `to_parquet`.

### OS

Ray on aws glue.

### Python version

3.9

### AWS SDK for pandas version

awswrangler-3.4.2-py3-none-any.whl

**Comment by jaidisido** [comment]
It's difficult for us to reproduce this given the number of transformations involved. However, as discussed in Slack, my hunch is that one of the transformations (between the read and partitioned writes) is causing the OOM. One way to test this theory if you can is to just read the data and write it back immediately (i.e. skip the transformations)?
