### ISSUE TITLE
Support to register nested data types (avro/json/parquet in particular) in Wrangler

### ISSUE THREAD

**Issue by nithskj** [aws/aws-sdk-pandas#2534]
JPMC(CCB)  Data Lake side, Customer  are looking to expand their support to register nested data types (avro/json/parquet in particular). To do this, we need to support table creation using json/avro schema files.
Ideally, we would hope the Glue create_table() API would expand support for this. However, a faster alternative would be to expand AWS Datawrangler SDK methods like these -> https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.catalog.create_json_table.html#awswrangler.catalog.create_json_table
 to also support AVRO and support creation of Glue tables via schema files, We don’t necessarily want to go down the Glue SchemaRegistry route.
Reaching out what the process \step to incorporate above feature request for below wrangler SDK. 
https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.catalog.create_json_table.html#awswrangler.catalog.create_json_table

**Comment by jaidisido** [comment]
Is the ask to create a `wr.catalog.create_avro_table`? If so, it should be as simple as adding AVRO definitions to these two files:
- https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/catalog/_definitions.py
- https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/catalog/_create.py
Feel free to have a go at it in a PR if you wish
