### ISSUE TITLE
empty parquets are not accessible while using `chunked=INTEGER` in `s3.read_parquet`

### ISSUE THREAD

**Issue by milena-andreuzo** [aws/aws-sdk-pandas#2542]
Hello! I am using `awswrangler` to read a dataset from a specific parquet folder on s3, so `s3.read_parquet` is very useful. 

Currently, I need to read the dataset in chunks while having control of how many lines every chunk has, and for that reason I use the argument `chunked` with an integer instead of a bool. However, I've found a problem when the parquet file has no rows, only columns (note that it is not an empty file, is a dataset with no records, but with columns). My current line to read the files is:

```
reader = s3.read_parquet('s3://folder/key/', chunked=500000, dtype_backend="pyarrow")
```

On such case that the parquet file has only columns, I cannot reach any of its informations. I need to be able to go through with empty files, and ideally I would go with the code below.

```
reader = s3.read_parquet('s3://folder/key/', chunked=500000, dtype_backend="pyarrow")
for df in reader:
    if df.empty:
        return empty result
    else:
        process rows
```

The `df.empty` part however returns nothing, and everything on the code block is ignored. I've tried some other commands and the results are always empty.

```
>>> for df in reader:
...     print(df)
... 
>>> for df in reader:
...     print(dir(df))
... 
>>> for df in reader:
...     print(df.empty)
... 
>>> for df in reader:
...     print(df.shape)
... 
>>> 
```

I tried reading it with the dataset option and had the same result.
```
reader = s3.read_parquet('s3://folder/key/', chunked=500000, dataset=True, dtype_backend="pyarrow")
```

While reading with `chunked=True`, I can check that the object has attributes and methods, but trying to access them gives me nothing.
```
>>> reader = s3.read_parquet('s3://folder/key/', chunked=True, dtype_backend="pyarrow")
>>> for df in reader:
...     print(dir(df))
... 
[...columns..., ...attributes..., 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_gbq', 'to_hdf', 'to_html', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']
>>> for df in reader:
...     print(df.empty)
... 
```

Above I left only a part of the output to show as an example, since I can't show the data.

Now, the only way I got that `df` is actually an empty pandas dataframe is using a combination of `chunked=True` and `dataset=True`:

```
>>> reader = s3.read_parquet('s3://folder/key/', chunked=True, dataset=True, dtype_backend='pyarrow')
>>> for df in reader:
...     print(df.empty)
... 
True
```
But again, with `chunked=True` I cannot control how many rows each iteration has.

My conditions are: 
* Reading the entire input parquet folder directly from S3 is much more useful than iterating over files;
* I need to control the number of lines read for each chunk in case the dataframe is not empty;
* I need to check whether the dataframe is empty or not;

And my questions are:
* Is there a way to get everything I need with `awswrangler.s3`?

**Comment by jaidisido** [comment]
The logic for reading a dataset in chunks is [here](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/s3/_read_parquet.py#L221).

As you can see, it loops over the objects and:
1. If chunked=True, it returns one data frame per path. So there is a 1:1 mapping between the object and the data frame
2. If chunked=Integer, it **combines the files** in order to honour the requested number of rows. In other words, the mapping between an object and the data frame does not exist anymore because it's combining the files to return the correct chunks. As a result, S3 objects with no data are just [ignored](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/s3/_read_parquet.py#L256). 

So I am not sure what you are trying to achieve in your code:
```
for df in reader:
    if df.empty:  # this df does not map to the underlying file
        return empty result
```
because the returned chunked data frames do not map to the objects anyways

**Comment by milena-andreuzo** [comment]
Not sure if I got it right.. I'm not considering the `df` object maps to the `file`,  I'm considering **it is the empty dataframe** because the parquet file that is read on **reader** can be empty. See:

* I read a folder of parquet files: sometimes this folder has many parquets with data on it, sometimes it has only one file with the dataset containing no records. But still, I read the folder in chunks so when I have a large dataset I control how many lines I get in every iteration.
* My sequence is: 1. I am reading a parquet folder in chunks ; 2. there is only one parquet file on it with a table containing the columns but no records (meaning the dataset is empty, there are columns but no rows, the parquet is not a zero byte file); 3. when going through the iterator object it returns an empty object with no properties.
* What I wanted from the third step: the iterator to return an empty dataframe: has the columns the parquet presents, has all the properties a dataframe has (such as .empty), but has no rows.

**Comment by jaidisido** [comment]
Consider this example:
```python
import awswrangler as wr
import pandas as pd

path = "s3://bucket/prefix/"

df = pd.DataFrame({"col1": [1, 2, 3], "col2": [4, 5, 6]})
df.to_parquet(f"{path}not_empty/file.pq")

df = pd.DataFrame(columns=["col1", "col2"])
df.to_parquet(f"{path}empty/file.pq")

reader = wr.s3.read_parquet(path, dataset=True, chunked=2, dtype_backend="pyarrow")
for df in reader:
    print(df)

   col1  col2
0     1     4
1     2     5
   col1  col2
2     3     6
```
The first S3 object has three rows but the second object is empty. Reading in chunks of 2 rows returns two data frames, but not that there isn't a third df for the empty file that you can inspect. This is done by design. 

Now, your edge case seems to be that you are reading from a single empty file. The reason why you can't inspect the df is because the iterator is simply empty
```python
reader = wr.s3.read_parquet(f"{path}empty/", dataset=True, chunked=2, dtype_backend="pyarrow")
if all(False for _ in reader):
    print("iterator is empty")
```
While the chunked API is not meant to be used in this scenario, the above would at least tell you if you are in that particular corner case. Please note that the above will consume the first element of the iterable.

**Comment by milena-andreuzo** [comment]
Just returning to you that the way you proposed works for detecting empty data, but it weirdly modifies the object when it isn't. 
Found a way using `itertools`:

```
tables = s3.read_parquet('s3://folder/key/', chunked=500000, dtype_backend="pyarrow")
try:
    first = next(tables)
    new_reader = itertools.iterchain([first], tables)
except StopIteration:
    new_reader = None
```

From [stackoverflow](https://stackoverflow.com/questions/661603/how-do-i-know-if-a-generator-is-empty-from-the-start)
