### ISSUE TITLE
Ray throwing ObjectRefStreamEndOfStreamError when using awswrangler.redshift.copy()

### ISSUE THREAD

**Issue by pmandadkes1207** [aws/aws-sdk-pandas#2549]
### Describe the bug

Hello,

I am getting the ObjectRefStreamEndOfStreamError when I am trying to upsert a dataframe using wrangler.redshift.copy command, mode='upsert'. The pandas used is modin.pandas. I created a ticket with Ray team https://github.com/ray-project/ray/issues/41209  and they told me the following : 

"We made a change to a developer API in Ray 2.7, and AWS hasn't updated the SDK accordingly. In particular, https://github.com/ray-project/ray/pull/37986 removed the block parameter from the BlockWritePathProvider interface."

### How to Reproduce

Create a dataframe with 10 rows and call wrangler.redshift.copy with mode='upsert'

### Expected behavior

The dataframe should be upserted with out any errors

### OS

Windows Server 2016 10.0.14393

### Python version

3.11.6

### AWS SDK for pandas version

awswrangler==3.4.1

**Comment by jaidisido** [comment]
You mention using Ray 2.8 but we currently [cap](https://github.com/aws/aws-sdk-pandas/blob/main/pyproject.toml#L64) Ray to 2.6 and below. Can you please downgrade to that version and test again?

**Comment by jaidisido** [comment]
Great, we will look to uncap and adapt the codebase to new versions of Ray in future releases
