### ISSUE TITLE
Unsupported Redshift type: binary

### ISSUE THREAD

**Issue by misteliy** [aws/aws-sdk-pandas#2550]
### Describe the bug

When using 

```
                wr.redshift.copy_from_files(
                    path=path,
                    con=con,
                    table=file_name.replace(".parquet", ""),
                    schema="staging",
                    parquet_infer_sampling = 1,
                    varchar_lengths_default = 65535
                )
```

I'm getting following error:

![image](https://github.com/aws/aws-sdk-pandas/assets/893310/354fe153-4251-4094-824f-df862102c004)

most likely the data type should be mapped to varchar

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### OS

Linux

### Python version

3.10.12

### AWS SDK for pandas version

3.4.2

**Comment by kukushking** [comment]
Hi @misteliy thanks for opening this. There is VARBYTE data type that is missing from [type mappings](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/_data_types.py#L411). I will cut a PR to fix this.
