### ISSUE TITLE
flatten_nested_df: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.

### ISSUE THREAD

**Issue by DataBoyTX** [aws/aws-sdk-pandas#2554]
**Is your idea related to a problem? Please describe.**
when I call `wr.neptune.flatten_nested_df()` I get the following warning printed for each record: 

```
/root/.local/lib/python3.10/site-packages/awswrangler/neptune/_neptune.py:624: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  s = (df.applymap(type) == list).all()
```

sample code: 
```
query = f"MATCH (n:person) RETURN n.name"
df0 = wr.neptune.execute_opencypher(client, query)
if len(df0) == 0: 
    print("no nodes") 
else:
    df1 = wr.neptune.flatten_nested_df(df0)
    display(df1)
```

**Describe the solution you'd like**
update the applymap to map to avoid the warning

**Comment by jaidisido** [comment]
The pandas `map` API on a data frame was only introduced in pandas 2.1 https://github.com/pandas-dev/pandas/issues/52353
So replacing it would cause backward compatibility. Perhaps we can consider suppressing the warning
