### ISSUE TITLE
Update official lambda layers with newer pandas version

### ISSUE THREAD

**Issue by dschmitz89** [aws/aws-sdk-pandas#2555]
**Is your feature request related to a problem? Please describe.**

The current "official" lambda layers from [here](https://aws-sdk-pandas.readthedocs.io/en/2.15.0/layers.html) ship with pandas 1.3. This is quite outdated as there is already a new major version of pandas available. Pandas 2 comes with great performance enhancements which are currently not usable with awswrangler without messing around with homegrown lambda layers.

**Describe the solution you'd like**
An official awswrangler lambda layer built on Pandas 2.1. Based on the [pyproject.toml file](https://github.com/aws/aws-sdk-pandas/blob/326ea8dfd6a2cc83c1f6f735d9dce3c0d03c6ced/pyproject.toml#L33), Pandas 2 is in principle supported.

**Describe alternatives you've considered**
If a lambda layer was already built by someone, I would be happy to use it.

**Comment by jaidisido** [comment]
The link you shared is pointing to version 2.15. The latest version of the library is [3.4](https://aws-sdk-pandas.readthedocs.io/en/stable/layers.html) which does package pandas 2.x in the layers

**Comment by dschmitz89** [comment]
Thank you and sorry for not finding it myself, somehow the older version showed up before the current one in a google search.
