### ISSUE TITLE
Support for python 3.12

### ISSUE THREAD

**Issue by HAK-CODE** [aws/aws-sdk-pandas#2557]
Add support for `python 3.12` which is being launched [here](https://aws.amazon.com/blogs/compute/python-3-12-runtime-now-available-in-aws-lambda/)

**Comment by kukushking** [comment]
Hi @HAK-CODE thanks for opening the issue - we'll plan it for the next release

**Comment by kukushking** [comment]
Closing - will be available in 3.5.0.
