### ISSUE TITLE
awswrangler way slower than boto3 to query a Timestream table

### ISSUE THREAD

**Issue by cscetbon** [aws/aws-sdk-pandas#2561]
I wonder if this is a bug or not but using awswrangler is way slower as you can see

```
In [108]: %time wr.timestream.query("""SELECT measure_name, measure_value::double, time    FROM "sampleDB"."sampleTable"    WHERE measure_name = 'memory_utilization' AND az = 'us-east
     ...: -2c' AND time > ago(1h) AND index = '1138' LIMIT 10""")
CPU times: user 38.8 ms, sys: 41.9 ms, total: 80.7 ms
Wall time: 2.41 s
```
versus
```
In [109]: %time client.query(QueryString="""SELECT measure_name, measure_value::double, time    FROM "sampleDB"."sampleTable"    WHERE measure_name = 'memory_utilization' AND az = 'us-eas
     ...: t-2c' AND time > ago(1h) AND index = '1138' LIMIT 10""")
CPU times: user 2.01 ms, sys: 808 µs, total: 2.82 ms
Wall time: 439 ms
```

**Comment by jaidisido** [comment]
I am afraid that is not an apple to apple comparison. `wr.timestream.query` returns a pandas data frame while `client.query` a Python list. Additional [steps](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/timestream/_read.py#L101) are involved after reading the list to convert it to a data frame such as processing the schema

**Comment by cscetbon** [comment]
oh, I was surprise for less than 10 elements in my case.. So I guess I should use boto3 when speed matters like user queries as opposed to background queries where I can leverage data frames.
