### ISSUE TITLE
Sanitization of named parameters in athena.read_sql_query

### ISSUE THREAD

**Issue by frenchytheasian** [aws/aws-sdk-pandas#2575]
If I am reading the code for `wr.athena.read_sql_query` correctly, it looks like sanitization is not performed on named queries which are resolved client side. I think this would be a nice enhancement to the function, but am open to reason or arguments on leaving it out. If this is something that would be valuable in wrangler, I can work on a PR for this.

**Comment by jaidisido** [comment]
Hi @frenchytheasian, could you please share a reference to the code where you believe Athena named queries are used within `wr.athena.read_sql_query`? AFAIK the user must supply the `sql` string at all times which is then [sanitised](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/athena/_read.py#L1047).

**Comment by frenchytheasian** [comment]
@jaidisido Sorry I misspoke in my original message. I don't believe sanitization is supported for named **parameters** (not named queries). The docs say that the formatter is applied client side [here](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/athena/_utils.py#L364). It does not look any string values are sanitized for malicious characters.

**Comment by jaidisido** [comment]
The [_process_sql_parameters](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/_sql_formatter.py#L171) method is doing some validation around typing but not malicious characters. Additional sanitisation is always welcome so please feel free to contribute, thanks!
