### ISSUE TITLE
AWS Clean Rooms - New Feature - Analysis Templates.

### ISSUE THREAD

**Issue by rmalecky** [aws/aws-sdk-pandas#2580]
**Is your idea related to a problem? Please describe.**
AWS Clean Rooms recently added support from templates in addition to free form queries. It would be helpful to update AWS SDK for Pandas to support this option.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cleanrooms/client/start_protected_query.html

Start Protected query requires either a SQL String or an Analysis Template ARN and optional parameters.

**Describe the solution you'd like**

Current Behavior:
```
import awswrangler as wr
df = wr.cleanrooms.read_sql_query(
     sql='SELECT DISTINCT...',
     membership_id='membership-id',
     output_bucket='output-bucket',
     output_prefix='output-prefix',
 )
```

New behavior
```
import awswrangler as wr
df = wr.cleanrooms.read_sql_query(
     analysis_template_arn= 'arn:aws:cleanrooms:us-west-2:123456789012:membership/e97cbd6b-3584-4adc-ae27-8b1d7cf9f386/analysistemplate/bd516f00-c169-43b7-921c-e242d316f605',
    parameters= {
         my_key='my_value'
     },
     membership_id='membership-id',
     output_bucket='output-bucket',
     output_prefix='output-prefix',
 )
```

**Comment by kukushking** [comment]
Thanks @rmalecky, great feature - I'll cut a PR to add it.
