### ISSUE TITLE
No matching distribution found for awswrangler

### ISSUE THREAD

**Issue by AbhishekRai-5** [aws/aws-sdk-pandas#2586]
I am facing the error " No matching distribution found for awswrangler " . awswrangler is an dependency in my project but I am not able to download it even though it is available in the pypi . The awswrangler version I am trying to use is " 2.17.0 ". 
![image](https://github.com/aws/aws-sdk-pandas/assets/89443807/ffec2ed1-e030-4314-84a7-e8655905e916)

The above image is the screenshot of the error I am facing. 

Please help me this issue.

**Comment by jaidisido** [comment]
You are using python 3.11. Py3.11 support was only introduced in later versions of the library and is not available for 2.17.0. You can either upgrade to a newer version or downgrade the python version
