### ISSUE TITLE
Support layers with python 3.12

### ISSUE THREAD

**Issue by aarana95** [aws/aws-sdk-pandas#2592]
**Is your idea related to a problem? Please describe.**
Three weeks ago, the Python 3.12 branch was merged (https://github.com/aws/aws-sdk-pandas/pull/2559), but there are no available layers for Python 3.12 yet, even though the usual time between support and layer availability is one week. Does anyone know the schedule for this?

**Comment by LeonLuttenberger** [comment]
Hey,

We are planning on releasing version `3.5.0` of the library this week. The lambda layers will also become available then, through the ARNs listed [here](https://aws-sdk-pandas.readthedocs.io/en/stable/layers.html).

Best regards,
Leon
