### ISSUE TITLE
Postgres Reserved Keyword Error

### ISSUE THREAD

**Issue by sotiriskar** [aws/aws-sdk-pandas#2617]
In my AWS RDS(Postgres) Database I have a table with a column named **"end".** In older versions, I was able to upload to this column without having any problems by using this part of the code in Python:

```python
import awswrangler as wr

wr.postgresql.to_sql(
    df=df,
    table=table,
    schema=schema,
    con=conn,
    mode="append",
    use_column_names=True,
)
```

After recently updating to the latest version of the library I get an error, more specifically:

```
Error loading data to PostgreSQL: {'S': 'ERROR', 'V': 'ERROR', 'C': '42601', 'M': 'syntax error at or near "end"', 'P': '97', 'F': 'scan.l', 'L': '1236', 'R': 'scanner_yyerror'}
```

I believe I'm encountering this error due to a reserved word. Is there a way to prevent this issue? 

Additionally, I'm curious about why this error has surfaced now when it wasn't a problem in the past. Thank you!

**Comment by kukushking** [comment]
Hi @sotiriskar , what is the version of the library you are using?

**Comment by sotiriskar** [comment]
I'm currently encountering the error with version `awswrangler-3.5.1`, whereas I didn't experience the issue when using version `awswrangler-3.4.2` previously.
