### ISSUE TITLE
iam policies required for to_iceberg api

### ISSUE THREAD

**Issue by subtype1** [aws/aws-sdk-pandas#2644]
My lambda function execution role has all the necessary permissions to s3, glue and athena.

However, to_iceberg call is failing with access denied issues for s3 bucket.

what are the necessary permissions to get to_iceberg call working

**Comment by jaidisido** [comment]
As a general rule we do not provide IAM policies as we don't know the level of security required for your use case nor the specific resources involved. What is the specific Access Denied exception that is raised?

**Comment by subtype1** [comment]
The exact exception I get is 

"Access to the specified s3 resource is denied, please check your iam/s3 bucket policies and any relevant kms permission".

Problem is - the lambda execution role has all the necessary permissions and the error message is so very general and hence difficult to debug on where exactly the issue is

**Comment by subtype1** [comment]
Also - just a general layout of the permissions will do or any pointers on how to debug this further will help as well

**Comment by kukushking** [comment]
@subtype1 Check LakeFormation permissions if it is enabled. It's common to miss `lakefromation:GetDataAccess`.
