### ISSUE TITLE
Writing to Athena Iceberg Table: Extra System Generated Directory in s3

### ISSUE THREAD

**Issue by sanaghazi1** [aws/aws-sdk-pandas#2656]
I am using the following function to write my pandas dataframe to Athena:

```
import awswrangler as wr

wr.athena.to_iceberg(df=df,
                     database=db_name,
                     table=table_name,
                     table_location="s3://my_bucket/my_catalog_name/my_namespace.db/table_name/",
                     temp_path="s3://my_bucket/my_catalog_name/temp/",
                     partition_cols=['col1', 'col2'],
                     keep_files=False
                     )
```

The data looks to be appearing correctly when I query Athena. When I inspect the underlying s3 location, I see data showing up like such:

`
s3://my_bucket/my_catalog_name/my_namespace.db/table_name/data/--Docg/col1=col1_val1/col2=col2_val1/
s3://my_bucket/my_catalog_name/my_namespace.db/table_name/data/--oCVA/col1=col1_val1/col2=col2_val2/
s3://my_bucket/my_catalog_name/my_namespace.db/table_name/data/-0uRtg/col1=col1_val2/col2=col2_val1/
`

So I am seeing these extra auto-generated sub-directories such as **"--Docg", "--oCVA", "-0uRtg"**. Why is this happening and how do I prevent this?

**Comment by jaidisido** [comment]
The `table_location` parameter is used as a path to the [create Iceberg table](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/athena/_write_iceberg.py#L62) SQL statement in Athena. It seems that those directories are created by the Athena engine when new data is added/updated, so it's managed by the underlying service not this library

**Comment by Mroq93** [comment]
When I am using pyspark to save into iceberg, the strange prefixes before partitions are not created.
I am facing this when I use `wr.athena.to_iceberg`
