### ISSUE TITLE
aws-wrangler creating new versions for iceberg table and creating metadata for each new version

### ISSUE THREAD

**Issue by B161851** [aws/aws-sdk-pandas#2661]
As I am trying to write data to the existing iceberg table using the AWS-wrangler without changing any schema, where it is generating the new versions for each record that we are inserting in the iceberg table and the old versions metadata was stored in our S3 bucket in huge amount. As we are writing records frequently to that table, versions increasing every time and metadata storage also crossed over 170 TB.
Is there any fix for this version increase issue? Can't this AWS wrangler library write to iceberg table without changing version every time, even if the schema was same?
The below is the code snippet that I am using, you can reproduce the issue using below code. 

```
wr.athena.to_iceberg(
            df=df,
            database='test_database',
            table='my_table2',
            table_location='s3://bucket-testing1/my_table2/',
            temp_path=f's3://bucket-testing1/temp_path/',
            keep_files=True
        )
```

**Comment by B161851** [comment]
@jaidisido

**Comment by jaidisido** [comment]
I assume you are referring to the metadata under the `temp_path`? Is there any reason why you are setting the `keep_files=True` flag? Switching it to `False` would delete files under the temporary path. Beyond that my understanding is that the metadata is created by the Athena service and AFAIK we don't control that. @kukushking can you think of anything else here?

**Comment by B161851** [comment]
@jaidisido  we tried with keep_files=False as well but we are facing the same issue, and the temp_path is not for metadata, in that library they are using temp_path to create the temporary table and inserting records from that temporary table to iceberg table and then they deleting the temp table and temp_path.

**Comment by kukushking** [comment]
Hi @B161851 @jaidisido Iceberg writes data in snapshots and keeps the metadata to support time travel. Consider optimizing the table via `OPTIMIZE` or `VACUUM` queries. More in the [User Guide](https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg-data-optimization.html).
