### ISSUE TITLE
Error while reading ctas query in awswrangler.athena.read_sql_query with ctas_approach set to TRUE

### ISSUE THREAD

**Issue by nikhil27472** [aws/aws-sdk-pandas#2676]
Hi, 

While i'm running the below code it is giving an Error.

`import pandas as pd`
`import awswrangler as wr`
`query = f"""`
`create table database_name.table_name as`
`select * from source_database_name.source_table_name`
`"""`
`wr.athena.read_sql_query(`
`	sql=query,`
`	database = 'database',`
`	workgroup = 'workgroup',`
`	ctas_approach = True,`
`	s3_output = 'database_path'`
`)`

The Error was `InvalidRequestException: An Error occurred when calling the StartQueryExecution operation: mismatch input create`

Please help in resolving the above Error.

**Comment by jaidisido** [comment]
You don't need to wrap your query in a CTAS statement, the API takes care of that already. So you just need to pass `select * from source_database_name.source_table_name`

**Comment by nikhil27472** [comment]
While just provide select statement, its just returning the data as a DataFrame. But our requirement is to directly create table from that select query.

The above query works perfectly fine when `ctas_approach=False`, but with this statement its taking too much time to compute.

Please suggest if i'm using it correctly. 
Do we have any other function to make this working.

**Comment by jaidisido** [comment]
> While just provide select statement, its just returning the data as a DataFrame.

That is exactly the intent of the `wr.athena.read_sql_query` API, to return data in a pandas DataFrame, not to create a table.

There is already an API dedicated to creating an Athena SQL query:
https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.create_ctas_table.html#awswrangler.athena.create_ctas_table
