### ISSUE TITLE
get more than 50 items from `describe_log_streams`

### ISSUE THREAD

**Issue by AlJohri** [aws/aws-sdk-pandas#2684]
**Is your idea related to a problem? Please describe.**
I would like to get more than 50 items from the `awswrangler.cloudwatch.describe_log_streams` function. It seems like the underlying boto3 call supports pasisng in `nextToken` [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/logs/client/describe_log_streams.html#). Thus, I believe I should be able to get more than 50 items.

Currently you get this error:

>InvalidParameterException: An error occurred (InvalidParameterException) when calling the DescribeLogStreams operation: 1 validation error detected: Value '51' at 'limit' failed to satisfy constraint: Member must have value less than or equal to 50

**Describe the solution you'd like**
I would like to request an arbitrary number of items have awswrangler handle the pagination to get that number of results.

**Comment by jaidisido** [comment]
The `wr.cloudwatch.describe_log_streams` API already implements [next_token](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/cloudwatch.py#L332) and can return all items. 50 is the limit for each pagination call, not the overall limit. It's enforced by the underlying boto3 API (see Limit in the [link](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/logs/client/describe_log_streams.html#) you shared).

**Comment by jaidisido** [comment]
I see. We are limited by what the underlying boto3 calls exposes I am afraid. The [read_logs](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.cloudwatch.read_logs.html#awswrangler.cloudwatch.read_logs) API might give you more flexibility in the query perhaps.

**Comment by AlJohri** [comment]
I think the boto3 API exposes enough nobs to achieve this behavior. Instead of running `while "nextToken" in response`, we can client side stop paginating requests if some condition is met such as a client side limit or a client side `LastEventTime`

I can re-open this as a feature request for adding a client side filtering / stop pagination parameter in `wr.cloudwatch.describe_log_streams` for large log groups
