### ISSUE TITLE
Iceberg partitioning based on transformed DataFrame columns not supported?

### ISSUE THREAD

**Issue by petebachant** [aws/aws-sdk-pandas#2686]
### Describe the bug

I was hoping that something like `partition_cols=["user_id", "month(ts)"]` would work nicely in `athena.to_iceberg`, but I end up with a `KeyError` noting that `"month(ts)"` doesn't exist in the DataFrame. However, the table is created properly based on the output of `athena.show_create_table`.

### How to Reproduce

Use a partitioning function in one of the `partition_cols` passed into `to_iceberg`.

### Expected behavior

I expect to not get a `KeyError`.

### OS

Mac

### Python version

3.11

### AWS SDK for pandas version

3.6.0

**Comment by kukushking** [comment]
Hi @petebachant unfortunately only partition columns are supported at the moment (no functions). You can transform the data in your data frame prior to the insert.

**Comment by alvaro-ponce** [comment]
Hi @kukushking that's not what documentation says: 
![image](https://github.com/aws/aws-sdk-pandas/assets/71835604/f8921287-2cef-4840-8f0a-a128aa6f0e9c)

https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.to_iceberg.html#awswrangler.athena.to_iceberg

I was using append a couple of days ago successfully on version 3.4, now it fails on version 3.6, I tried to check the wrangler code but I do not totally understand why did not failed in 3.4.

**Comment by alvaro-ponce** [comment]
Ok, it was 3.3.0, I have checked and I can append multiple times with function in partition cols in 3.3.0 version

**Comment by LeonLuttenberger** [comment]
Hey, thanks for bringing this up. You are correct, this feature was broken in the PR you tagged. I'm looking into a way to fix this.

**Comment by alvaro-ponce** [comment]
Thanks for the quick response and work!

You are awesome!
