### ISSUE TITLE
Why do I have to install openpyxl when I am using calamine as a pandas read_excel engine?

### ISSUE THREAD

**Issue by jaanisfehling** [aws/aws-sdk-pandas#2695]
Example:
`wr.s3.read_excel(file, sheet_name=0, engine="calamine")`
Here I am using `calamine` as the engine to open an excel file. This is fully supported by pandas.
But, `awswranger` is throwing an error telling me that I have to install `openpyxl`, even tho I do not want to use it.
If I understand correctly, `awswrangler` is not using `openpyxl` but just delegating the call to `pd.read_excel`. If yes, why are you checking for this library? How can I know which engine is actually used?
If no, it would be better to let the user know that a different engine cannot be selected.

**Comment by jaidisido** [comment]
Thanks for raising this. I agree, not sure why `openpyxl` should be enforced

**Comment by jaanisfehling** [comment]
Thanks for the quick fix!
