### ISSUE TITLE
dtype_backend overrides categories

### ISSUE THREAD

**Issue by antbz** [aws/aws-sdk-pandas#2700]
### Describe the bug

I noticed that when using `wr.athena.read_sql_query`, the `categories` parameter was not having any effect on the returned pandas dataframe.

I did some investigation and realised that in the `pa.Table.to_pandas` [method](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.to_pandas), the categorical conversion happens before the `types_mapper` is taken into account, so in effect, the categorical columns are always being converted back to string.

Removing the `types_mapper` kwarg, the categorical types are processed correctly.

### How to Reproduce

```
import awswrangler as wr

data = wr.athena.read_sql_query(
    sql="SELECT id, options FROM my_table",
    database="my-database",
    categories=["options"],
)
print(data.dtypes)
```

The `categories` will be a string column.

### Expected behavior

The columns specified in `categories` should be `pd.Categorical` types

### OS

MacOS 14.3.1

### Python version

3.9.18

### AWS SDK for pandas version

3.6.0

### Additional context

PyArrow is version 15.0.0

**Comment by jaidisido** [comment]
The [wr.athena.read_sql_query](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.read_sql_query.html#awswrangler.athena.read_sql_query) API has a `pyarrow_additional_kwargs` argument which is forwarded to the `to_pandas` method. If nothing is supplied, some [sane defaults](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/_data_types.py#L583) are applied.

If you wish to override these defaults, to remove `types_mapper` for example, you can do something along the lines of:
```
data = wr.athena.read_sql_query(
    sql="SELECT id, options FROM my_table",
    database="my-database",
    categories=["options"],
    pyarrow_additional_kwargs={'types_mapper': None},
)
```

**Comment by antbz** [comment]
@jaidisido While that is a nice suggestion, it also does not work because of how `_fetch_parquet_result` works internally. When you specify `pyarrow_additional_kwargs`, the `categories` are never added to the kwargs actually passed onto pyarrow:

https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/athena/_read.py#L150-L153

For it to work correctly you need to pass categories as additional kwargs as well:

```
data = wr.athena.read_sql_query(
    sql="SELECT id, options FROM my_table",
    database="my-database",
    pyarrow_additional_kwargs={'types_mapper': None, 'categories': ['options']},
)
```

I'm not sure if the behaviour in `_fetch_parquet_result` is intentional or not, but as it stands, the `categories` parameter effectively does not do what it is supposed to. We should either document this better or find a way to make it compatible by default.

**Comment by jaidisido** [comment]
I can't think of a reason why it's setup that way so I believe it's just badly indented. #2701 should fix that
