### ISSUE TITLE
S3 GetObject opetation. ClientError: The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by yihengli** [aws/aws-sdk-pandas#2719]
This might be relevant to #904 

For the following snippet:

```python
import awswrangler as wr
import boto3
from io import StringIO
import pandas as pd

# directly parse s3 csv using boto 
# this is working fine
session = boto3.Session()
s3 = session.client("s3")
obj = s3.get_object(Bucket="some_bucket", Key="some_key_to_csv")
file_content = obj["Body"].read()
df = pd.read_csv(StringIO(file_content.decode("utf-8")))

# using the same session with wr will throw error
df = wr.s3.read_csv("s3://some_bucket/some_key_to_csv", boto3_session=session)
```

In the old post, using the same session should overcome this error, which is not the case anymore.

Package Version
```
python = 3.11
awswrangler = 3.7.1
boto3 = 1.34.60
botocore = 1.34.60
```

Other details:
- My machine only sets `AWS_CA_BUNDLE`, and I don't have `~/.aws/credentials` (therefore, no `AWS_ACCESS_KEY_ID` nor `AWS_SECRET_ACCESS_KEY`

**Comment by jaidisido** [comment]
I didn't manage to reproduce the error running the supplied code on my local setup. Your issue might somehow be related to a combination of your local creds setup and the way we build the [client](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/_utils.py#L470)

**Comment by yihengli** [comment]
I can reproduce similar SSL error using s3fs as well. It is weird that boto3 alone works fine under the same runtime. 

If this cannot be reproduced by simply removing all credentials but only using CA_BUNDLE, then I might close this issue
