### ISSUE TITLE
Why doesn't postgresql.to_sql support a TRUNCATE overwrite_method?

### ISSUE THREAD

**Issue by senorcinco** [aws/aws-sdk-pandas#2728]
I've mostly used the SDK for loading data into Redshift, so I was surprised to learn that postgresql.to_sql doesn't support a TRUNCATE overwrite_method.  I need to preserve table indexes, so dropping the table isn't possible.  I read that a PostgreSQL TRUNCATE isn't MVCC compliant.  Is that the reason why it isn't supported?

**Comment by kukushking** [comment]
Thanks @senorcinco no I think it's just an oversight. We'll add it to our backlog.
