### ISSUE TITLE
Use of np.array_split causes warning that can be avoided

### ISSUE THREAD

**Issue by nabelekt** [aws/aws-sdk-pandas#2730]
### Describe the bug

The `split_pandas_frame` function in `_utils.py`, called by `awswrangler.timestream.write`, calls `np.array_split` resulting in this warning:
```
/usr/local/lib/python3.11/dist-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
```
np.array_split should no longer be used with dataframes. Please see here: https://github.com/numpy/numpy/issues/24889#issuecomment-1895503977

### How to Reproduce

```
Call awswrangler.timestream.write()
```

### OS

Linux

### Python version

3.11.7

### AWS SDK for pandas version

3.7.1

**Comment by jaidisido** [comment]
Thanks, the [comment](https://github.com/numpy/numpy/issues/24889#issuecomment-1895503977) you linked is recommending to use iloc instead, but according to its [docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html) that is deprecated too...
