### ISSUE TITLE
PostgreSQL - Adding constraints on columns for .to_sql() function

### ISSUE THREAD

**Issue by andino-seatcode** [aws/aws-sdk-pandas#2737]
When using the function `.to_sql()` for PostgreSQL, which creates the table if it doesn't exist, I don't see a way to add any constraints for the columns (for example primary key or unique).

I see this as a problem, as in this case the use of the `upsert_conflict_columns` and `insert_conflict_columns` parameters give an error, since a conflict can only occur if a constraint is set.

Is there a way to handle this with the current implementation or would the only solution be to create the table manually beforehand/add the constraints manually after creation (which I would like to avoid)?

I understand that this is a special case, as the constraints would only be needed upon creation of the table and not on any further inserts.

**Comment by jaidisido** [comment]
Yes, the table creation feature is only meant as a helper for simple use cases. For anything more involved we recommend creating the table beforehand with appropriate constraints as it would be too unnecessarily complex for us to handle all potential combinations. You can see that we do the same in our own [unit tests](https://github.com/aws/aws-sdk-pandas/blob/fix/issue-2730-deprecated-split-array/tests/unit/test_postgresql.py#L243) for example
