### ISSUE TITLE
How to get the access key being used?

### ISSUE THREAD

**Issue by nabelekt** [aws/aws-sdk-pandas#2747]
I am trying to retrieve the access key being used for operations for logging purposes. I.e., the XXXXX value here:

```
root@ThinkPad-3:~/repos/cloud-data-processing/aws/database_handling# cat ~/.aws/credentials
[default]
aws_access_key_id = XXXXX
aws_secret_access_key = YYYYY
```
Here is some code I am testing with:
```
import awswrangler as wr

account_id = wr.sts.get_account_id()
arn = wr.sts.get_current_identity_arn()
name = wr.sts.get_current_identity_name()
secret = wr.secretsmanager.get_secret(arn=arn)

print(account_id)
print(arn)
print(name)
print(secret)
```
Is `wr.secretsmanager.get_secret()` supposed to return this? I haven't yet been able to figure out how to use that properly. `arn` is not ana rgument for `get_secret()`. `get_secret(name=name)` gives me:
```
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret.
```
Any help here would be appreciated. Possibly, `name = wr.sts.get_current_identity_name()` is enough.

**Comment by jaidisido** [comment]
`wr.secretsmanager.get_secret` is an API to retrieve a secret from the [AWS Secrets Manager service](https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html), not your local AWS credentials. There is no API to retrieve the local access and secret keys within this library. You can however obtain it from your boto3 session ([link 1](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.get_credentials)/[link 2](https://stackoverflow.com/a/36291428/8178963)). Please keep in mind that this is sensitive information that should not be exposed, particularly not in logs...

**Comment by nabelekt** [comment]
That answers my question, thank you!
