### ISSUE TITLE
`catalog.create_parquet_table` silently ignores `table_type='ICEBERG'`

### ISSUE THREAD

**Issue by plbremer** [aws/aws-sdk-pandas#2757]
### Describe the bug

I have a parquet file stored in S3. I want to make an iceberg table using that information.

I want to make an iceberg table directly in order to avoid downloading the parquet file and using `athena.to_iceberg`. 

### How to Reproduce

I attempt to use create_parquet_table like

```
catalog.create_parquet_table(
    database='awswrangler_test',
    table='awswrangler_test_iceberg_directly',
    path='s3://plbremer-bucket/foo/',
    columns_types=columns_types,
    partitions_types=partitions_types,
    compression='snappy',
    table_type='ICEBERG',
)
```

This code resolves, but I do not think that the resulting table is one of type `iceberg`.

For example, when I got to Athena to look at the generated table DDL, i get

`FAILED: IllegalArgumentException No enum constant org.apache.hadoop.hive.metastore.TableType.ICEBERG`

for the record, i tried playing with things like
`parameters={'table_type':'ICEBERG','format':'parquet'}`

### Expected behavior

Creation of an iceberg table and corresponding metadata in s3 like `to_iceberg` produces.

### OS

mac 13.5 (22G74)

### Python version

3.11.3

### AWS SDK for pandas version

3.7.2

### Additional context

Am I thinking about this the right way? Or should the behavior of `_create_table` be modified to more closely replicate `to_iceberg` if `table_type='ICEBERG'`?

Thanks

**Comment by jaidisido** [comment]
In the `athena.to_iceber` call, the Iceberg table is created with an [Athena DDL query](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/athena/_write_iceberg.py#L63) not a Glue all. This [rePost article](https://repost.aws/questions/QUirg97gMGSzS0Ax6eC7k5zA/create-iceberg-table-in-glue) points to the same solution.

**Comment by plbremer** [comment]
> In the `athena.to_iceberg` call, the Iceberg table is created with an [Athena DDL query](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/athena/_write_iceberg.py#L63) not a Glue call. This [rePost article](https://repost.aws/questions/QUirg97gMGSzS0Ax6eC7k5zA/create-iceberg-table-in-glue) points to the same solution.

Does the following makes sense then:

- One cannot use awswrangler.catalog.* to create iceberg tables for athena
- Instead, if one wants to use awswrangler to create iceberg tables without downloading the contents into a local dataframe, one can only hope to use awswrangler.athena.read_sql_query with a query that might have been templated based on properly parsed parquet metadata from something like awswrangler.s3.read_parquet_metadata

I assume that the syntactically proper CREATE TABLE query would also deposity the appropriate iceberg metadata in the s3 containing the parquet file...?

**Comment by jaidisido** [comment]
Below is a simplified version of the [code](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/athena/_write_iceberg.py#L63) I linked in my previous comment using the [start_query_execution](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.start_query_execution.html#awswrangler.athena.start_query_execution) API:
```python    
   sql = (
        f"CREATE TABLE IF NOT EXISTS `{table}` ({cols_str}) "
        f"LOCATION '{path}' "
        f"TBLPROPERTIES ('table_type'='ICEBERG', 'format'='parquet')"
    )

    wr.athena.start_query_execution(sql=sql, database=database, wait=True)
```

It simply follows what is described in the Iceberg Athena [docs](https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg-creating-tables.html). You might have to play a bit with the parameters to the API but that is the gist of it

**Comment by plbremer** [comment]
> Below is a simplified version of the [code](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/athena/_write_iceberg.py#L63) I linked in my previous comment using the [start_query_execution](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.start_query_execution.html#awswrangler.athena.start_query_execution) API:
> 
> ```python
>    sql = (
>         f"CREATE TABLE IF NOT EXISTS `{table}` ({cols_str}) "
>         f"LOCATION '{path}' "
>         f"TBLPROPERTIES ('table_type'='ICEBERG', 'format'='parquet')"
>     )
> 
>     wr.athena.start_query_execution(sql=sql, database=database, wait=True)
> ```
> 
> It simply follows what is described in the Iceberg Athena [docs](https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg-creating-tables.html). You might have to play a bit with the parameters to the API but that is the gist of it

Ok great, I agree with this, thanks
