### ISSUE TITLE
aws wrangler - s3.to_csv stripes 00:00:00 in timestamps

### ISSUE THREAD

**Issue by kennethng** [aws/aws-sdk-pandas#2769]
### Describe the bug

when exporting to csv in s3 using aws wrangler, when it's a datetime column and time is 00:00:00, for example `2024-04-04 00:00:00`, the csv will only have `2024-04-04`.
In the same column, if you have another row that is `2024-04-04 11:11:11` (non 00:00), then in the same column but different rows, some will be date, and some will be datetime

### How to Reproduce

1. create a dataframe with a column for date time
2. Have a few rows with different datetime, including at least 1 row with 00:00:00
3. Export to s3 using aws wrangler (import awswrangler as wr) with: wr.s3.to_csv
4. download and open the csv in your computer
5. notice that the row with 00:00:00 is only exporting the date

### Expected behavior

datetime that have 00:00:00 should still be exported into csv.

### OS

Lambda x86_64

### Python version

Python 3.10

### AWS SDK for pandas version

AWSSDKPandas-Python310	layer 13

**Comment by kennethng** [comment]
Hi - thank you for your help on this!
This is within a lambda function:

```python
        cur.execute("select * from test")
        offer_reports = cur.fetchall()
        data = pd.DataFrame(test)
        if not data.empty:
            wr.s3.to_csv(data, f's3://cdc-target/test.csv',index=False)
``` 

I tried using `df.to_csv()` but getting an write error within the lambda function when trying to use that function.

**Comment by jaidisido** [comment]
Your code feeds a `test` variable to `pd.DataFrame` but it is referenced nowhere else so hard to infer anything from it. In any case, here are two suggestions:
1. Ensure that the column is indeed of type `datetime64`
2. pandas [to_csv](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html) has a `date_format` argument that you can leverage to enforce how datetime objects are formatted (e.g. `'%d/%m/%Y %H:%M:%S'`)

**Comment by kennethng** [comment]
Hi @jaidisido - apologies, I was trying to remove any syntax from my code, my code actually is the following:

```python
        cur.execute("select * from reports")
        reports = cur.fetchall()
        data = pd.DataFrame(reports)
        if not data.empty:
             wr.s3.to_csv(data, f's3://cdc/reports.csv',index=False)
       
``` 

with this code, for some reason it is stripping out 00:00:00, if i add 1 second to it, then I have no issues exporting out datetime.

I tried using `to_csv` in the lambda function but running into permission issues and haven't been able to resolve the permission issues yet.
