### ISSUE TITLE
filters for awswrangler.s3.read_parquet

### ISSUE THREAD

**Issue by DRKolev-code** [aws/aws-sdk-pandas#2779]
A while back there was a thread requesting this feature. Any progress? It is quite unfortunate not being able to use `filters` directly as they are friendlier compared to `partition_filter`. (It is doubly confusing given the new name of awswrangler:)).

**Comment by kukushking** [comment]
Hi @DRKolev-code thanks for opening this. As discussed [here](https://github.com/aws/aws-sdk-pandas/issues/1032) this would incur major refactoring of the library to use the new [PyArrow Dataset](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Dataset.html) API. We'll add it to the backlog.
