### ISSUE TITLE
Support client-side parameter resolution in wr.athena.create_ctas_table

### ISSUE THREAD

**Issue by tk09291197** [aws/aws-sdk-pandas#2787]
**Is your idea related to a problem? Please describe.**

[athena.unload](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.unload.html#awswrangler-athena-unload)、[athena.read_sql_query](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.read_sql_query.html#awswrangler-athena-read-sql-query) and
[athena.start_query_execution](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.start_query_execution.html#awswrangler-athena-start-query-execution) supports [client-side parameter resolution](https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/006%20-%20Amazon%20Athena.html#Client-side-parameter-resolution).
It would be useful if [athena.create_ctas_table](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.create_ctas_table.html#awswrangler-athena-create-ctas-table) had similar parameter resolution.

**Describe the solution you'd like**
A clear and concise description of what you are expecting.

Add parameters `params` and `paramstyle` to `athena.create_ctas_table`.

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
An `execution_params` parameter is exposed in the create_ctas API. It can be used like below:
```
from awswrangler.athena._utils import _apply_formatter

sql, execution_params = _apply_formatter(sql, params, paramstyle)
wr.athena.create_ctas_table(sql=sql, execution_params=execution_params...)
```

We agree however that this is inconsistent with other APIs and will look to rectify it
