### ISSUE TITLE
Requests for Additional Argument `name_function` on `awswrangler.s3.to_parquet()`

### ISSUE THREAD

**Issue by JaeryunYim** [aws/aws-sdk-pandas#2800]
**Describe the solution you'd like**
I hope that `awswrangler.s3.to_parquet()` method has an argument similar to `name_function` of `dask.dataframe.to_parquet()` for the case of `dataset=True` and `partition_cols` is set. For me, the existing argument `filename_prefix` is not enough because each partitioned filename always contains some hash value which I don't want.
https://docs.dask.org/en/stable/generated/dask.dataframe.to_parquet.html

**Comment by kukushking** [comment]
Thanks for opening this @JaeryunYim. Added to the backlog.
