### ISSUE TITLE
The `to_property_graph` docstring in the Neptune module is not well written and does not describe the behavior of the function when the node already exists

### ISSUE THREAD

**Issue by ajcost** [aws/aws-sdk-pandas#2813]
**Is your idea related to a problem? Please describe.**
Currently the docstring for `to_property_graph` reads:
>Write records stored in a DataFrame into Amazon Neptune.
>
>If writing to a property graph then DataFrames for vertices and edges must be written separately. DataFrames for >vertices must have a ~label column with the label and a ~id column for the vertex id. If the ~id column does not exist, >the specified id does not exists, or is empty then a new vertex will be added. If no ~label column exists an exception >will be thrown. DataFrames for edges must have a ~id, ~label, ~to, and ~from column. If the ~id column does not >exist the specified id does not exists, or is empty then a new edge will be added. If no ~label, ~to, or ~from column >exists an exception will be thrown.

>If you would like to save data using single cardinality then you can postfix (single) to the column header and set >use_header_cardinality=True (default). e.g. A column named name(single) will save the name property as single >cardinality. You can disable this by setting by setting use_header_cardinality=False.

This does not indicate anything as to the nature of the function if a node or edge with the same `~id` already exists within the database. Secondly this is not read easily, there are a couple of grammatical mistakes.

**Describe the solution you'd like**
Better written explanation as to the nature of the function when the node does not exist, exists, and nuances as to the errors thrown under those various scenarios.

**Comment by jaidisido** [comment]
Thanks, fixed in https://github.com/aws/aws-sdk-pandas/commit/7de0336e336b492bab1727770360759b4cbe0980
