### ISSUE TITLE
Intermittent NETWORK_CONNECTION Error During s3.read_parquet_table Operation

### ISSUE THREAD

**Issue by DimitarSirakov** [aws/aws-sdk-pandas#2847]
### Describe the bug

Hi,

I'm encountering an intermittent issue when using the s3.read_parquet_table function in my ETL pipeline. The pipeline reads Parquet files from S3 every 5 minutes (modin, ray, awswrangler). Occasionally, I receive the following error:

AWS Error NETWORK_CONNECTION during HeadObject operation: curlCode: 28, Timeout was reached

### How to Reproduce

I am unable to reproduce this error consistently, and it seems to resolve itself after some time. 
import awswrangler as wr

df = wr.s3.read_parquet_table(table,database,partition_filter, filename_suffix)

### OS

Linux

### Python version

3.10.13

### AWS SDK for pandas version

3.7.2

**Comment by jaidisido** [comment]
There is a long standing issue opened in https://github.com/ray-project/ray/issues/43803 on the subject
