### ISSUE TITLE
When saving a df with a partition transform function and mode="overwrite_partitions" using the `to_iceberg` method, the KeyError occurs

### ISSUE THREAD

**Issue by kenny52g** [aws/aws-sdk-pandas#2854]
### Describe the bug

When saving a DataFrame with a partition transform function specified like 'day(ts)' using the `to_iceberg` method and calling it with mode="overwrite_partitions", a KeyError: "['day(ts)'] not in index" occurs.

### How to Reproduce

please call to_iceberg method like below
```python
wr.athena.to_iceberg(
        df=df,
        database='some_db',
        table='some_tbl',
        table_location=f's3://some_table_location/',
        partition_cols=["day(ts)", "some_other_col"],
        workgroup='some_work_group',
        temp_path=f's3://some_temporary_path/',
        keep_files=False,
        mode="overwrite_partitions",  # if this line does not specified, the error does not occur thanks to PR #2694 
    )
```

### Expected behavior

The table is successfully created through the partition transform function.

### Screenshots

<img width="903" alt="image" src="https://github.com/aws/aws-sdk-pandas/assets/138445713/50d58fcd-644c-493b-8958-316cee06b09e">
<img width="1299" alt="image" src="https://github.com/aws/aws-sdk-pandas/assets/138445713/bb835b92-9dac-4681-a258-74ffc5f9314d">

### OS

Mac

### Python version

3.11.9

### AWS SDK for pandas version

awswrangler==3.8.0

### Additional context

if mode does not specified(it will be 'append' mode), the error does not occur thanks to PR #2694

**Comment by kenny52g** [comment]
I think it is similar issue with https://github.com/aws/aws-sdk-pandas/issues/2845

**Comment by LeonLuttenberger** [comment]
Hey,

Unfortunately, because this implementation of `to_iceberg` relies on a mesh of Pandas and Athena queries, we can't currently support this option of using a partition transform function with `mode="overwrite_partititons"`. However, we are exploring other APIs for refactoring `to_iceberg`, such as PyIceberg or other AWS Glue APIs, which would allow us to support this in the future.

**Comment by kenny52g** [comment]
@LeonLuttenberger 
Thank you for the detailed explanation of the plan. 
I also appreciate the continuous support with using AWS Wrangler. 
And again, I am also looking forward to the to_iceberg function using the other API you mentioned. 
I will close this issue now 👍
