### ISSUE TITLE
Convert CloudWatch LogInsights query results to Dataframe

### ISSUE THREAD

**Issue by sethusrinivasan** [aws/aws-sdk-pandas#2860]
**Scenario:** I was trying to export CloudWatch Insights' query results to csv file using Pandas

**Ask:**
[cloudwatch.run_query()](https://aws-sdk-pandas.readthedocs.io/en/3.8.0/stubs/awswrangler.cloudwatch.run_query.html#awswrangler.cloudwatch.run_query) returns ```List[List[Dict[str, str]]]```. Instead, can this return a Pandas Dataframe so that it is easier to  export to csv / excel format?

**What I tried:**
```

import awswrangler as wr
from datetime import datetime, timedelta

import pandas as pd

result = wr.cloudwatch.run_query(
    log_group_names=["log1"],
    query=query1,
    start_time = datetime.today() - timedelta(hours=0, minutes=5),
    end_time = datetime.today(),
    limit = 1
)

df = pd.DataFrame.from_records(result,index=['1', '2'])
df.to_csv('out.csv')
```
This gets me output as
```
,0,1
1,"{'field': 'field1', 'value': '5'}","{'field': 'field2', 'value': '10'}"
```

I was looking for something like
```
field1, field2
5,10
```

Any other / easier ways to accomplish?

**Comment by jaidisido** [comment]
The [wr.cloudwatch.read_logs](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.cloudwatch.read_logs.html#awswrangler.cloudwatch.read_logs) API is designed to do just that
