### ISSUE TITLE
Incompatibility with Ray 2.31 dependency

### ISSUE THREAD

**Issue by frosk1** [aws/aws-sdk-pandas#2878]
### Describe the bug

ImportError: cannot import name 'DefaultParquetMetadataProvider' from 'ray.data.datasource.file_meta_provider'

module has been restructured in new ray version:
https://github.com/ray-project/ray/commit/e116c5a30f3a5310b23b8710445e4a2d5cdb22f6

### How to Reproduce

```
use pandas with modin on ray

import modin.pandas as pd
import ray
...
```

### Expected behavior

No ImportError

### OS

Linux Ubuntu

### Python version

3.9

### AWS SDK for pandas version

3.8.0

**Comment by jaidisido** [comment]
https://github.com/aws/aws-sdk-pandas/issues/2870 addresses this and will be available in the next release. In the meantime we recommend pinning Ray to <2.30
