### ISSUE TITLE
Unexpected OOM on wr.s3.to_parquet() (2.20.1 / Py3.7)

### ISSUE THREAD

**Issue by alecbw** [aws/aws-sdk-pandas#2909]
Hey Wrangler team,

Submitting this as a question and not a bug report because I can't readily provide exhaustive context to reproduce this.

I should note I am currently using `awswrangler==2.20.1` on Py 3.7. I understand the most likely answer to this question is "bump the deps", but it would be **very** painful to do so, so I'm hoping you have other suggestions.

I've been experiencing an ongoing problem where a cron process running on AWS Fargate will OOM 
(`Exit code: 137 OutOfMemoryError: Container killed due to memory usage`) on running `wr.s3.to_parquet()`, despite the underlying data being substantially below the memory allocated to the box.

Here's the workflow:
1. A series of Parquet files are read with `wr.s3.read_parquet()`. This step never fails, and can comfortably use `use_threads=True`
2. The data is deduplicated and some rows are removed. The number of columns is unaffected.
3. It fails on write, no matter the `use_threads`, `concurrent_partitioning`, or `max_rows_by_file` values.

The original underlying data is `3.8 GB`. After deduplication it's probably ~3.0 GB. The box has been allocated `4 vCPU | 30 GB Memory`.

This seems to me to be a bug, or perhaps a lack of garbage collection in the process of writing the multiple files. I'm not quite sure what I can do to avoid this OOM without fully ripping out Wrangler and writing to Parquet more directly. 

I will note for clarity that this exact codebase used to work when the data sizes were smaller. 

I've provided the write kwargs currently in use:
```
wr.s3.to_parquet(
    df=df,
    path="s3://" + bucket + "/" + path
    dataset=True,
    mode="overwrite_partitions",
    database="database",
    table="table",
    compression="snappy",
    partition_cols=["year", "month", "day"],
    max_rows_by_file=25_000,
    index=False,
    sanitize_columns=True, 
    schema_evolution=False, 
    use_threads=False,
    concurrent_partitioning=False
)
```

Thoughts?

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
I am afraid we have dropped py3.7 support more than a year ago, our advice would be as you mention to upgrade to an earlier version and check if the OOM issue persists
