### ISSUE TITLE
Layer Version 12 Is not Available in China

### ISSUE THREAD

**Issue by jinxiao** [aws/aws-sdk-pandas#2910]
### Describe the bug

When we use the arn in China region, we found it's unavailable. As we contact with AWS China support, there're some issues for version 12. Could you please fix the documentation for us? This issue happened with arn:aws-cn:lambda:cn-north-1:406640652441:layer:AWSSDKPandas-Python311:12

### How to Reproduce

```
1. Use AWS web console, when selecting AWSSDKPandas-Python311, we cannot see version 12. 
2. Forcely use 12, it reported cannot import
```

### Expected behavior

This should be working fine.

### OS

Linux

### Python version

3.11

### AWS SDK for pandas version

12

### Additional context

Wrong arn is arn:aws-cn:lambda:cn-north-1:406640652441:layer:AWSSDKPandas-Python311:12, it's should be arn:aws-cn:lambda:cn-north-1:406640652441:layer:AWSSDKPandas-Python311:11

**Comment by jaidisido** [comment]
As per the [docs](https://aws-sdk-pandas.readthedocs.io/en/stable/install.html#aws-lambda-layer):
```
There is a one week minimum delay between version release and layers being available in the AWS Lambda console.
```

It can take several days for the latest version to appear in the AWS layers console. However you can specify the latest version (12 in this case) like in the picture

<img width="849" alt="Layers CN" src="https://github.com/user-attachments/assets/08c98aa8-8db3-4f9a-ad93-b014f15d03f4">

**Comment by jinxiao** [comment]
> As per the [docs](https://aws-sdk-pandas.readthedocs.io/en/stable/install.html#aws-lambda-layer):
> 
> ```
> There is a one week minimum delay between version release and layers being available in the AWS Lambda console.
> ```
> 
> It can take several days for the latest version to appear in the AWS layers console. However you can specify the latest version (12 in this case) like in the picture
> 
> <img alt="Layers CN" width="849" src="https://private-user-images.githubusercontent.com/16362107/351629042-08c98aa8-8db3-4f9a-ad93-b014f15d03f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjA2MDMsIm5iZiI6MTcyMjI2MDMwMywicGF0aCI6Ii8xNjM2MjEwNy8zNTE2MjkwNDItMDhjOThhYTgtOGRiMy00ZjlhLWFkOTMtYjAxNGYxNWQwM2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEzMzgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNzU2ZmZhZWU2Zjg4NmMyODk3YTI2YmVlMGUwZGExNTE1ZTQzMWY2ZWEyNWM2NjJhOGM0MzVmNjIwMGY4NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A39Zuqdba5Sp3wcYDHAJX-zUOzCWa4jae42Bda6aIQA">

As we contact the AWS support, it's not currently available, since there are some issues. We also tried this method, and reported errors. This layer cannot be used in China region. 

Erros like:

```
{
  "errorMessage": "Unable to import module 'lambda_function': Unable to import required dependencies:\nnumpy: Error importing numpy: you should not try to import numpy from\n        its source directory; please exit the numpy source tree, and relaunch\n        your python interpreter from there.",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "4efeeb40-2afc-44b5-8e07-8ff3fb86543c",
  "stackTrace": []
}
```

This is already confirmed by AWS Support China.

![image](https://github.com/user-attachments/assets/6e1ab864-ce39-4400-837e-9ea9a079bfff)

**Comment by jaidisido** [comment]
Please try with this version:
```
arn:aws-cn:lambda:cn-north-1:406640652441:layer:AWSSDKPandas-Python311:13
```
We are investigating the issue and updating the docs
