### ISSUE TITLE
Add support for polars (perhaps via narwhals)

### ISSUE THREAD

**Issue by david-waterworth** [aws/aws-sdk-pandas#2920]
**Is your feature request related to a problem? Please describe.**
I've mostly migrated my python analytics workflow from pandas to `polars`. This means in order to use a lot of great libraries such as `aws-sdk-pandas` I need to convert between `polars` and `pandas`

**Describe the solution you'd like**
`aws-sdk-pandas` seems like a great candidate for migration to being dataframe agnostic, i.e. by internally using [narwhals](https://github.com/narwhals-dev/narwhals) as a dataframe agnostic api.

An alternative might be to refactor methods that accept `dataset=True` to instead take a string (i.e. dataset="pandas" or dataset="polars").

**Comment by jaidisido** [comment]
Thanks @david-waterworth, we have considered other data frame formats such as polars in the past but have found that there is very little uptake compared to pandas for us to justify the dev effort that would be required to include them. We will keep on eye this however and might reconsider in the future
