### ISSUE TITLE
Significant Performance Degradation with Python 3.9+ Upgrade in AWS Lambda

### ISSUE THREAD

**Issue by akash5991** [aws/aws-sdk-pandas#2924]
We've encountered a substantial performance slowdown after upgrading from Python 3.8 to newer Python versions (3.9 and 3.11) in our AWS Lambda function using the AWS SDK for pandas layer.

Environment:
- AWS Lambda
- Previous: Python 3.8 with AWSSDKPandas-Python38 v24
- Issue with: Python 3.11 with their AWSSDKPandas-Python311 v16

Code that previously executed in approximately 1 second now takes about 5 seconds to complete. 

Additional Information:
- Runtime Version: python:3.8.v52 log timings:
  START: 10:29:32.151Z
  Main processing begins: 10:29:32.152Z
  Main processing ends: 10:29:32.850Z
  END: 10:29:32.889Z
  Total main processing time: ~0.7 seconds

- Runtime Version: python:3.11.v37 log timings:
  START: 10:29:03.954Z
  Main processing begins: 10:29:03.971Z
  Main processing ends: 10:29:08.650Z
  END: 10:29:08.749Z
  Total main processing time: ~4.8 seconds

In Python 3.11, below warnings were thrown at 10:29:06.070Z
- /opt/python/awswrangler/_distributed.py:105: FutureWarning: promote has been superseded by mode='default'.
- return cls.dispatch_func(func)(*args, **kw)

No changes were made to the function code or Lambda configuration aside from the Python version upgrade.

Questions:
1. Are there known performance issues with the AWS SDK for pandas when used with Python 3.11 on Lambda?
2. Could the FutureWarning be related to the performance degradation?
3. Are there any recommended optimizations or configuration changes for Python 3.11 usage?
4. Is this level of performance degradation expected, or could it indicate a bug in the SDK?

**Comment by LeonLuttenberger** [comment]
Hey,

Which region are you running this code in? We need the region to determine which version of the library was being used, as layer versions aren't consistent across regions.

Also, can you share what code you were running? Or at least which functions you were using (e.g. `s3.to_parquet`, `redshift.read_sql_query`, etc.)?

Best regards,
Leon

**Comment by akash5991** [comment]
Hello @LeonLuttenberger ,

I had tested it on eu-west-1 (Ireland) and eu-west-2 (London) and and used `s3.read_parquet`.
For more context, the parquet files being used are between 3KB - 5KB and the lambda has a memory of 128 MB in both scenarios.

However, when the memory was increased to 256MB in Python 3.11, execution time is averages at ~0.6 seconds, similar to how it was in Python 3.8 with 128MB memory

Cheers

**Comment by jaidisido** [comment]
@akash5991 I am not surprised that the execution time dropped when you increased the memory, it looks like py3.11 just requires more memory to be allocated
