### ISSUE TITLE
Can I use exponential backoff when I use wr.athena.read_sql_query() ?

### ISSUE THREAD

**Issue by A-nkt** [aws/aws-sdk-pandas#2951]
I used ``wrangler.athena.read_sql_query()``.

when I use this method, I cathed below error message.

> “errorMessage”: “An error occurred (TooManyRequestsException) when calling the StartQueryExecution operation: You have exceeded the limit for the number of queries you can run concurrently. Please reduce the number of concurrent queries submitted by this account. Contact customer support to request a concurrent query limit increase.”

this error caused of a lot of request.
So, I would like to using exponential backoff.
for example,

```python
import boto3
from botocore.config import Config
 
config = Config(retries = { 'max_attempts': 10, 'mode': 'standard' } )
 
client = boto3.client('athena', config=config)
```

so, my question is

1. when I using exponential backoff, this problem can resolve?
2. If this problem can resolve when using exponential backoff, How I can write?

**Comment by jaidisido** [comment]
The Athena start_query_execution call is already wrapped up in an [exponential backoff logic](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/athena/_utils.py#L127).

You can however fine tune it by modifying the botocore configuration as you suggest. This is explained in this [tutorial](https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/021%20-%20Global%20Configurations.html). Specifically:
```python
# Set botocore.config.Config that will be used for all boto3 calls
wr.config.botocore_config = botocore.config.Config(
    retries={"max_attempts": 10}, connect_timeout=20, max_pool_connections=20
)
```
which overrides the botocore config for all clients within the library.
