### ISSUE TITLE
Add support for S3 storage class

### ISSUE THREAD

**Issue by GukjinHan** [aws/aws-sdk-pandas#2958]
**Is your feature request related to a problem? Please describe.**
Currently, awswrangler does not support specifying the S3 object storage_class when writing data to S3. This limits the ability to use different storage classes such as INTELLIGENT_TIERING or GLACIER directly when saving objects.

**Describe the solution you'd like**
Add support for a storage_class option in wr.s3 methods, such as to_parquet and to_csv, that allows users to define the S3 object storage class. This is a feature already supported by the underlying boto3 S3 operations through the StorageClass parameter.

**Example usage**
```
import awswrangler as wr

wr.s3.to_parquet(
    df=my_dataframe,
    path="s3://my-bucket/my-data/",
    storage_class="INTELLIGENT_TIERING"
)
```
This feature would enable more control over storage costs by allowing users to choose the appropriate storage class based on their data usage patterns.

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by jaidisido** [comment]
Under the hood, the library uses `pyarrow` to carry out parquet writes to S3, not the boto3 S3 object class. Specifically, it relies on the [ParquetWriter](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetWriter.html) class which unfortunately does not expose the storage class.

As a workaround, is there a particular reason why you couldn't use a [S3 lifecycle transition rule](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-transition-general-considerations.html) on a prefix to achieve the same thing?

**Comment by GukjinHan** [comment]
Thank you @jaidisido.

I’ve applied an S3 lifecycle transition rule for the entire bucket, but it doesn’t seem to be affecting the files saved by Wrangler. The storage class remains set to Standard for these files, while files saved using other methods (like Trino or Spark) transition correctly.

I was considering adding an option to specify the storage class when saving with Wrangler as a simple solution. I’ll do some more research on this. If you have any additional advice, it would be greatly appreciated.
