### ISSUE TITLE
Glue Data catalog csv files with header parameter cause error GENERIC_INTERNAL_ERROR: Failed to construct table metadata for table xxxx

### ISSUE THREAD

**Issue by ctalucci** [aws/aws-sdk-pandas#2967]
When using  _wr.s3.to_csv_  with glue catalog and the header parameter the corresponding table schema parameter _skip.header.line.count_ is getting set to True which causes an _GENERIC_INTERNAL_ERROR: Failed to construct table metadata for table xxxx_ on querying with Athena. Manually updating the value to 1 fixes the error

https://github.com/aws/aws-sdk-pandas/blob/8cef7504c4b4aadd44306cde49001fcd062c5bb7/awswrangler/s3/_write_text.py#L585C1-L585C68

"skip_header_line_count": True if header else None,  
should be: 
"skip_header_line_count": 1 if header else None,

**Comment by jaidisido** [comment]
Thanks, as far as I can tell from the AWS Glue docs, `skip.header.line.count` should indeed be an integer
