### ISSUE TITLE
Connecting to a redshift cluster that runs in an other aws account

### ISSUE THREAD

**Issue by matteoredaelli** [aws/aws-sdk-pandas#2986]
Hello

I'd like to implement a lambda  in aws account A that connects to a Redshift cluster in aws account B using aws wrangler

```python
import awswrangler as wr
con_redshift = wr.redshift.connect(secret_id="MYSECRET")`
```

The code can retrieve the secret (it is stored in aws account A)  but then it fails with

`botocore.errorfactory.ClusterNotFoundFault: An error occurred (ClusterNotFound) when calling the DescribeClusters operation: Cluster my-redshift not found.`

This is why redshift is in an other aws account. ;-)

I can reproduce it from command line, setting access and secret key of account A at operating system level.

The secret key MYSECRET is like

```json
{
  "host": "myhost",
  "port": "5439",
  "database": "dbname",
  "user-name": "myuser",
  "password": "dummy",
  "engine": "redshift",
  "dbClusterIdentifier": "clustername"
}
```

is it possible? 

Thanks in advance
Matteo

**Comment by jaidisido** [comment]
The simplest path is to breakdown the calls in two.

First [get](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.secretsmanager.get_secret.html#awswrangler.secretsmanager.get_secret) the secret using the boto3 session of Account A:
```python
value = wr.secretsmanager.get_secret_json(name="my-secret", boto3_session="account-A-boto3-session")
```

Then use the secret details from the previous step to create a redshift connector connection to the cluster in Account B:
```python
import redshift_connector

con_redshift = redshift_connector.connect(user=..., database=...)
```

You can then pass that connection to any subsequent redshift call you would be making but using the boto3_session of account B:
```python
df = wr.redshift.read_sql_query(
    sql="SELECT * FROM public.my_table",
    con=con_redshift,
    boto3_session="account-B-boto3-session",
)
```

Alternatively you can [share](https://docs.aws.amazon.com/redshift/latest/dg/across-account.html) data cross accounts with Redshift but that might be more involved.
