### ISSUE TITLE
Release Pip Package: Numpy v2 Support

### ISSUE THREAD

**Issue by adampinky85** [aws/aws-sdk-pandas#2991]
Hi Team, 

We're significant users of AWS and depend on aws-sdk-pandas for our research. Currently, the library does not support Numpy v2 which is blocking the upgrade of our environments.

The PR with the code upgrade has already been merged into main. Can we please have a new pip package release that includes the update, thanks?

Many thanks,
Adam

### PR & Issue
https://github.com/aws/aws-sdk-pandas/pull/2944
https://github.com/aws/aws-sdk-pandas/issues/2943

cc: @LeonLuttenberger, @jaidisido, @kukushking

**Comment by kukushking** [comment]
Hi, thanks for opening this - prepping a release with https://github.com/aws/aws-sdk-pandas/pull/2992

**Comment by MRocholl** [comment]
Hello :)  Is there a schedule for when this release is dropping?

**Comment by jaidisido** [comment]
Now released, thank you
