### ISSUE TITLE
Support modin 0.32

### ISSUE THREAD

**Issue by allemp** [aws/aws-sdk-pandas#3003]
### Describe the bug

Currently the supported versions of modin are (>=0.31.0,<0.32.0) which doesn't include the newest version of modin which is 0.32

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

I expected awswrangler to support the newest version of modin.

### OS

linux

### Python version

not applicable

### AWS SDK for pandas version

not applicable

**Comment by jaidisido** [comment]
In the requirements file, modin is [not constrained](https://github.com/aws/aws-sdk-pandas/blob/main/pyproject.toml#L80) to a minor version as the [carat](https://python-poetry.org/docs/dependency-specification/#caret-requirements) specification constrains to major versions. In other words, modin 0.32.0 is allowed.

However, [pip](https://pip.pypa.io/en/stable/topics/dependency-resolution/) does not always select the latest version of a dependency by default as it is subject to the dependency tree that it resolves. In this case, it resolves to 0.31.0.

You can nonetheless force upgrade to the latest modin version yourself:
```
pip install awswrangler modin==0.32.0 ray==2.36.1
```
