### ISSUE TITLE
Support Ray 2.38

### ISSUE THREAD

**Issue by allemp** [aws/aws-sdk-pandas#3004]
### Describe the bug

Ray has removed ray.data.datasource._default_metadata_providers in a recent commit [12e1325](https://github.com/ray-project/ray/commit/12e1325591872f7cba8205d4c469c18266fbb805) which awswrangler relies on and gives an error.

Ray 2.36 works fine.

### How to Reproduce

Run wr.athena.read_sql_query() with ray@2.38.0 backend.

### Expected behavior

I expected awswrangler to work with ray 2.38 with no errors.

### OS

linux

### Python version

3.11

### AWS SDK for pandas version

3.9.1

**Comment by jaidisido** [comment]
Thanks, it has been fixed in #3007 and will be available in the next release
