### ISSUE TITLE
fill_missing_columns_in_df option in awswrangler.athena.to_iceberg is not working as expected

### ISSUE THREAD

**Issue by git4suman** [aws/aws-sdk-pandas#3036]
I am trying to write a dataframe into an iceberg table using awswrangler.athena.to_iceberg(). When the dataframe schema matches the iceberg table schema the data is written successfully . But when there are some columns missing in the dataframe its erroring out.
So i have used schema_evolution=True,fill_missing_columns_in_df=True. Still I see the same error. Ideally as per the documentation the missing fileds should be populated with Null values.

-- Code snippet

import awswrangler as wr
wr.athena.to_iceberg(df=df,database='mydb',table='my_table_name',temp_path='s3://mybucket/fldr1/temp'
                                          partition_cols=['dt','ts'],schema_evolution=True,fill_missing_columns_in_df=True, additional_table_properties={'write_target_data_file_size_bytes':'536870912','write_compression':'SNAPPY'}
                                          )

Any suggestions?

Note: When there are additional fields in the dataframe compared to iceberg table, setting schema_evolution =True alone is working perfectly. But if dataframe misses some columns its not been handled.

**Comment by jaidisido** [comment]
What is the actual exception raised? We can't really help if that information is not provided as it might not be related to the schema evolution here

**Comment by git4suman** [comment]
Below is the error message I see it in cloudwatch log . Let me know if any other details required

{ timestamp": "2024-12-04 02:24:55.634561",
    "level": "ERROR",
    "location": "awswrangler.athena._write_iceberg.to_iceberg:632",
    "aws_request_id": "my_lambda_function",
    "message": "['column1','column2','column3',....] not in index"
}

**Comment by jaidisido** [comment]
Here is [one](https://github.com/aws/aws-sdk-pandas/blob/main/tests/unit/test_athena_iceberg.py#L429) of our unit tests which shows an example of how to use the feature. My advice would be to start from this example and see at what point the error is raised so we can better understand the sequence

**Comment by git4suman** [comment]
I figured out the issue. The dataframe has columns in uppercase whereas the athena iceberg tables has columns in lowercase hence the issue. I had to convert all the dataframe columns to lowercase and then fill_missing_columns_in_df started working fine.
